### ISSUE TITLE
blackrock files loading error

### ISSUE THREAD

**Issue by Saksham20** [NeuralEnsemble/python-neo#1019]
I have a set of blackrock .nev and .ns3 files that I load using the `BlackrockRecordingExtractor` but it seems the versions of the .nev and .ns3 files are different in the header. It throws the below error in the `BlackrockRawIO` class. Before questioning the integrity of the files in hand I wanted to know if there could be some fixes.  ns3 is version 2.1 and nev is 2.2. Loading only the nev (making the ns3 filename different) or vice versa does not solve the issue as nev will have the voltage scaling info.

Here is the traceback:
```
File "c:\users\saksham\documents\nwb\spikeextractors\spikeextractors\extractors\neoextractors\blackrockextractor.py", line 36, in __init__
    super().__init__(filename=filename, nsx_to_load=nsx_to_load,
  File "c:\users\saksham\documents\nwb\spikeextractors\spikeextractors\extractors\neoextractors\neobaseextractor.py", line 58, in __init__
    _NeoBaseExtractor.__init__(self, block_index=block_index, seg_index=seg_index, **kargs)
  File "c:\users\saksham\documents\nwb\spikeextractors\spikeextractors\extractors\neoextractors\neobaseextractor.py", line 34, in __init__
    self.neo_reader.parse_header()
  File "c:\users\saksham\documents\nwb\python-neo\neo\rawio\baserawio.py", line 185, in parse_header
    self._parse_header()
  File "c:\users\saksham\documents\nwb\python-neo\neo\rawio\blackrockrawio.py", line 321, in _parse_header
    assert all(all_spec[0] == spec for spec in all_spec), \
AssertionError: Files don't have the same internal version
```

**Comment by JuliaSprenger** [comment]
Hi @Saksham20, in principle you should be able to load individual Blackrock files using the `BlackrockRawIO`. If you just need  information from both files I would recommend loading them separately as loading files from different recording systems in one session will lead to inconsistencies at some point. 
Or you receive an error that the scaling info is missing when trying to individual files from your dataset?

**Comment by Saksham20** [comment]
@JuliaSprenger , within the folder, there are two files with the same name but one is nev and other ns3. The `BlackrockIO` or the `BlackrockRawIO` are automatically looking for consistency between the two and throws the above error even if I enter only the .nev/nsx file to open. 
```
bk = BlackrockIO(r'filename.nev')
OR
bk = BlackrockIO(r'filename.ns3')
``` 
same error. Only if I manually change the name of one of the files, then it loads each separately.

**Comment by JuliaSprenger** [comment]
Hi @Saksham20 if you want to load only one specific nev of nsx file you can use the `nev_override` and `nsx_override` arguments. I.e. to not automatically discover all files belonging to the session you could call `BlackrockIO('', nev_override='<myfile>.nev')` to only consider data from that specific nev file.

**Comment by Saksham20** [comment]
@JuliaSprenger okay, that works.
