### ISSUE TITLE
446 tests fail with neo-0.10.0

### ISSUE THREAD

**Issue by TheChymera** [NeuralEnsemble/python-neo#1037]
This is the full build and test log: https://ppb.chymera.eu/f0c5ba.log
I assume some failures at least are due to network access (is there any way to easily skip tests which require network access), and some due to missing dependencies.

One thing I spotted is ipython — this is an interactive shell. Is any functionality of python-neo really dependent on an *interactive* Python shell?

**Comment by TheChymera** [comment]
Hi @samuelgarcia thank you for looking into this! The way many packages do this is that they either:
1. have an environment variable such as `PACKAGENAME_TESTS_NONETWORK` (datalad for instance uses `DATALAD_TESTS_NONETWORK`)
2. mark the tests with e.g. `@pytest.mark.network` so that they can be deselected when running pytest via `pytest -m "not network"`.

**Comment by samuelgarcia** [comment]
OK
I put that on my todo list.
I won't do it immediatly because I am a bit busy next 3 weeks but will do it soon.

**Comment by JuliaSprenger** [comment]
@samuelgarcia Any news on this?

**Comment by TheChymera** [comment]
Still failing very many tests (506) on `0.11.1`: https://ppb.chymera.eu/65897d.log

**Comment by TheChymera** [comment]
Just to update, though it's probably “as expected” given the milestone, network tests still fail in a network sandbox and I can't see how to auto-disable them on 
`0.12.0` https://ppb.chymera.eu/6fae8d.log
