### ISSUE TITLE
Support for multiple Sampling rates for Neuralynx Recordings

### ISSUE THREAD

**Issue by manimoh** [NeuralEnsemble/python-neo#1038]
Currently the NeuralynxRawIO.py doesn't support sessions where there are continuously sampled files with multiple sampling rates. Is there a plan to add this feature in the next release?

**Comment by samuelgarcia** [comment]
@PeterNSteinmetz @JuliaSprenger : any knwoledge on how neuralynx handle multi sample rate ?
In my mind the rate was global and not per channel.

**Comment by manimoh** [comment]
Of course! And thank you along with all the other creators of this wonderful tool!

I also emailed the files to you - let me know if you need something else!

**Comment by PeterNSteinmetz** [comment]
This feature could be implemented at the Neo IO core level, which is likely the most appropriate. It could also be implemented by SpikeInterface making different calls onto the RawIO classes. Really a question for @samuelgarcia or @JuliaSprenger.

I have worked mostly on the NeuralynxRawIO and getting it to work with the different variety of Neuralynx files. If you need something in the shorter term, suggest writing code to manipulate the current versions of the NeuralynxRawIO classes.

**Comment by PeterNSteinmetz** [comment]
For immediate use, I would suggest modifying your code to make calls directly using the RawIO.NeuralynxRawIO class. You can construct as many of these objects as you need to accommodate the differing sampling rate groups of files.

**Comment by manimoh** [comment]
Another use case for multiple sampling rates is that there are experiments (including ours) which use real time spectral analysis and sometimes that software that does this doesn't play well with the wideband sampling that is needed for Automatic spike sorting. In this case, we physically copy the required signals on the acquisition box to an unused input channel on the box and this copied signal can then be sampled at a rate which is compatible with the online spectral analysis tool.
Now this software can stream this differently sampled signal from Neuralynx's acquisition software and do its work. It is worthwhile for us to save this signal too for post hoc analysis.
