### ISSUE TITLE
AnalogSignal transpose breaks array annotations

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/python-neo#1039]
Hi!

I just noticed that it is quite useful to use a transpose to do some array operations with numpy and neo.AnalogSignal, but that breaks the `array_annotations` completely.

I was wondering if it would be desirable to wrap the numpy function (when doing `anasig.T`, or `anasig.transpose()`) so the `array_annotations` also get transposed and are not lost. What do you think?

Best,
Aitor

**Comment by JuliaSprenger** [comment]
Alternatively you can also use scipys detrend function and explicitely generate a new copy of the analogsignal to preserve the metadata

```a_without_mean = a.duplicate_with_new_data(scipy.signal.detrend(a, axis=1, type='constant'))```

**Comment by morales-gregorio** [comment]
Yes yes indeed.

I opened this issue mainly because I thought that transposing arrays is fairly common and that a newer user to neo would struggle to understand what happened to the array_annotations. If you still think that `AnalogSignals` should never be transposed, I would suggest at least raising a warning to let the user know that this operation deletes the array_annotations.

**Comment by JuliaSprenger** [comment]
Since there's no more comments by @samuelgarcia @apdavison I will close this issue for now. Feel free to reopen if you want to continue the discussion.
