### ISSUE TITLE
`TypeError: get_spike_raw_waveforms() got an unexpected keyword argument 'unit_index'` error from Neuralynx reader

### ISSUE THREAD

**Issue by TheChymera** [NeuralEnsemble/python-neo#1046]
Passing a `unit_index` argument to a `neo.io.NeuralynxIO` object:

```
reader = neo.io.NeuralynxIO(...)
waveform = reader.get_spike_raw_waveforms(seg_index=s, unit_index=i)
```

I get the following error:

```
TypeError: get_spike_raw_waveforms() got an unexpected keyword argument 'unit_index'
```

Looking at the code however, it seems this attribute exists: https://github.com/NeuralEnsemble/python-neo/blob/d786a0b2e8542a333b887e8892b99366bb1a2ffb/neo/rawio/neuralynxrawio/neuralynxrawio.py#L521

Any idea what I'm doing wrong?

**Comment by samuelgarcia** [comment]
It is now `spike_channel_index` instead of `unit_index`

**Comment by TheChymera** [comment]
@samuelgarcia thank you, that solved the isssue.
