### ISSUE TITLE
Open neuralynx (.ncs), events (.mrk, .nev) in neo

### ISSUE THREAD

**Issue by JulesGranget** [NeuralEnsemble/python-neo#1060]
Hi !
I wanted to open some .ncs files and events files attached that I have in a folder. I knew that neo could do it so I tried with it and gave the name of my folder as follow :

reader = neo.io.NeuralynxIO(dirname=path_dirname)

But I got this error message :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\neo\io\neuralynxio.py", line 51, in __init__
  File "D:\Anaconda3\lib\site-packages\neo\io\basefromrawio.py", line 75, in __init__
  File "D:\Anaconda3\lib\site-packages\neo\rawio\baserawio.py", line 149, in parse_header
  File "D:\Anaconda3\lib\site-packages\neo\rawio\neuralynxrawio.py", line 111, in _parse_header
    info = NlxHeader.build_for_file(filename)
  File "D:\Anaconda3\lib\site-packages\neo\rawio\neuralynxrawio.py", line 798, in build_for_file
    original_filename = re.search(hpd['filename_regex'], txt_header).groupdict()['filename']
AttributeError: 'NoneType' object has no attribute 'groupdict'

Do you have any idea what could possibly go wrong ? I looked at the doc but didn't find something to help me.
Thanks for your answer !

**Comment by JuliaSprenger** [comment]
Hi @JulesGranget 
It seems like the file header does not contain the filename in the expected format. Probably your file version has not been tested with neo yet. Could you provide (ideally a small) a test file for me to test this locally?

**Comment by JulesGranget** [comment]
Thanks a lot for your answer ! I tried to drag and drop files here but I wasn't able to do it... How can I send you the files ?

**Comment by JuliaSprenger** [comment]
You can, depending on the file size, either send them directly via mail to me or upload them on a file sharing platform and send me the link via mail.

**Comment by JulesGranget** [comment]
I sent you the files by email !

**Comment by JuliaSprenger** [comment]
@JulesGranget Thanks, I will have a look at them as soon as possible.

**Comment by JuliaSprenger** [comment]
Hi @JulesGranget I tested your files and can successfully load them using the Neo master branch. It seems like the continuous signals and events are loaded correctly, only the `mrk` file is not supported by the IO and I also don't have any specifications for this format. Do you know what kind of data is supposed to be stored in there and have a file specification?

Could you test again loading using the neo master branch?

**Comment by JulesGranget** [comment]
Hi Julia, thanks for your reply ! I'm sorry but, what do you mean by "using neo master branch" ? Do I need to reinstall neo specifically ? I tried again but I got the same answer using this line of code :

reader = neo.io.NeuralynxIO(dirname=dirname)

**Comment by JulesGranget** [comment]
Don't hesitate to tell me if you want the whole error or if you need other information, @JuliaSprenger.

**Comment by JuliaSprenger** [comment]
Hi @JulesGranget. First you can tell me which neo version you are currently using (in your python script: `import neo; print(neo.__version__)`).

To see if the error persists on your side with the latest version you can install the latest version by running `pip install --upgrade git+https://github.com/NeuralEnsemble/python-neo.git`.

If the above installation fails with an error telling you that git is not available, then you might need to download the latest code version from the github directly (https://github.com/NeuralEnsemble/python-neo -> green button at the with the label 'code' -> download zip -> unzip the file) and install it using your terminal (`cd <the folder path you just unzipped>` and then `pip install --upgrade .`)

**Comment by JulesGranget** [comment]
I checked my neo version and indeed it wasn't the last one. So I updated as you presented it to the 0.11.0dev0 and now it gives me this error : 
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\neo\io\neuralynxio.py", line 58, in __init__
    BaseFromRaw.__init__(self, dirname)
  File "D:\Anaconda3\lib\site-packages\neo\io\basefromrawio.py", line 74, in __init__
  File "D:\Anaconda3\lib\site-packages\neo\rawio\baserawio.py", line 185, in parse_header
    self._parse_header()
  File "D:\Anaconda3\lib\site-packages\neo\rawio\neuralynxrawio\neuralynxrawio.py", line 287, in _parse_header
AssertionError

**Comment by JuliaSprenger** [comment]
Hi again, It looks like you have multiple ncs files in your folder and at least one of them is sharing the sampling rate with the others. There is a work in progress PR to add support for this case soon (https://github.com/NeuralEnsemble/python-neo/pull/1041), but in the meantime you can try loading only a subset of your ncs files by moving the other ncs files temporarily to another (sub)folder.

**Comment by JulesGranget** [comment]
Hi, you mean that al least one of them does not share the same sampling rate ? Yes I will try to find the one that have not the same and see if it works. In this folder I also have .nev and .mrk file for the trig, I hope it does not raise issues. I will also try separately.

**Comment by JuliaSprenger** [comment]
Yes, that's exactly what I meant. In any case loading an individual ncs file should never raise this error, so if you encounter an issue even when having only a single ncs file left in your folder then tell me. The nev file should not be causing issues like this and the mrk file is currently not loaded by the NeuralynxIO, so it's also irrelevant. Is 'mrk' a standard Neuralynx file format? If you require information also to be read from that file then I would need some sort of specification document from Neuralynx to incorporate this in the IO. Do you have access to anything like this?

**Comment by JulesGranget** [comment]
Perfect ! Unfortunately I don't know for the mrk format and I don't have the information you require... But I will see if I can get them with the people I'm in touch with, if it could help anyway it's nice.

**Comment by JuliaSprenger** [comment]
I will close this issue for now @JulesGranget Feel free to reopen if you get more information regarding the mrk format.
