### ISSUE TITLE
change in loaded annotation with Spike2IO from version 0.9.0 to 0.10.0

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/python-neo#1064]
When loading data from a .smr file with the Spike2IO to (for example from https://doi.org/10.25493/ANF9-EG3), in the upgrade from neo version 0.9.0 to 0.10.0 many of the annotations and array annotations are lost.
```
# python 3.9.6
import neo
filepath = 'doi-10.25493/ANF9-EG3.smr'
io = neo.io.Spike2IO(filepath, try_signal_grouping=False)
asig = io.read_block().segments[0].analogsignals[0]
print(neo.__version__)
print(asigs.annotations)
print(asigs.array_annotations)
```
```
0.9.0
{'channel_id': 0, 'physical_channel_index': 25, 'comment': ''}
{'channel_names': array(['27'], dtype='<U64'), 'channel_ids': array([0]), 'file_origin': array(['doi-10.25493/ANF9-EG3.smr'],
      dtype='<U190'), 'physical_channel_index': array([25], dtype=int16), 'comment': array([''], dtype='<U1')}
```
```
0.10.0
{'stream_id': '0'}
{'channel_names': array(['27'], dtype='<U2'), 'channel_ids': array(['0'], dtype='<U1'), 'phy_chan': array([25], dtype=int16), 'comment': array([''], dtype='<U1')}
```

**Comment by samuelgarcia** [comment]
'physical_channel_index' became array annotation and became 'phy_chan' apparently. I don't remember why.
'file_origin' will be at segment or block level I think.
'channel_names' and 'channel_ids' are still here.
For the 'comment' I don't remember. It look strange to have a comment by channel (so array annotation). Did you have 'comment' at channel level before ?

**Comment by rgutzen** [comment]
Ah ok, so this is the new expected behavior?
At least for the files I worked with the comment entry for the analogsignal channels was empty.

**Comment by samuelgarcia** [comment]
I don't known exactly if this is expected or not.
This new version made a refactoring to handle array_annotation at rawio level and so affected almost all IOs about annotations.
The new way is normaly better because the routing between scalar annotation and array annoation was bad.
For instance 'physical_channel_index' was supposed to be array annoation. I guess that this 'comment' key was there but it was scalar.
