### ISSUE TITLE
circular import error on master branch

### ISSUE THREAD

**Issue by bendichter** [NeuralEnsemble/python-neo#1065]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_469/1217768234.py in <module>
      9 )
     10 from nwb_conversion_tools.utils.conversion_tools import get_module
---> 11 from spikeinterface.extractors import read_spikeglx, read_openephys
     12 
     13 import pynwb

/opt/conda/lib/python3.8/site-packages/spikeinterface/extractors/__init__.py in <module>
----> 1 from .extractorlist import *
      2 
      3 from .toy_example import toy_example
      4 from .bids import read_bids_folder

/opt/conda/lib/python3.8/site-packages/spikeinterface/extractors/extractorlist.py in <module>
      4 
      5 # sorting/recording/event from neo
----> 6 from .neoextractors import (
      7     MEArecRecordingExtractor, MEArecSortingExtractor, read_mearec,
      8     SpikeGLXRecordingExtractor, read_spikeglx,

/opt/conda/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/__init__.py in <module>
----> 1 from .mearec import MEArecRecordingExtractor, MEArecSortingExtractor, read_mearec
      2 from .spikeglx import SpikeGLXRecordingExtractor, read_spikeglx
      3 from .openephys import (OpenEphysLegacyRecordingExtractor,
      4                         OpenEphysBinaryRecordingExtractor, OpenEphysBinaryEventExtractor, read_openephys,
      5                         read_openephys_event)

/opt/conda/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/mearec.py in <module>
----> 1 from .neobaseextractor import NeoBaseRecordingExtractor, NeoBaseSortingExtractor
      2 
      3 import probeinterface as pi
      4 
      5 

/opt/conda/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py in <module>
      3                                  BaseRecordingSegment, BaseSortingSegment, BaseEventSegment)
      4 from typing import Union, List
----> 5 import neo
      6 
      7 

/opt/conda/lib/python3.8/site-packages/neo/__init__.py in <module>
     10 from neo.core import *
     11 # ~ import neo.rawio
---> 12 from neo.io import *
     13 
     14 from neo.version import version as __version__

/opt/conda/lib/python3.8/site-packages/neo/io/__init__.py in <module>
    245 from neo.io.blackrockio_v4 import BlackrockIO as OldBlackrockIO
    246 from neo.io.blkio import BlkIO
--> 247 from neo.io.bci2000io import BCI2000IO
    248 from neo.io.brainvisionio import BrainVisionIO
    249 from neo.io.brainwaredamio import BrainwareDamIO

/opt/conda/lib/python3.8/site-packages/neo/io/bci2000io.py in <module>
      1 from neo.io.basefromrawio import BaseFromRaw
----> 2 from neo.rawio.bci2000rawio import BCI2000RawIO
      3 
      4 
      5 class BCI2000IO(BCI2000RawIO, BaseFromRaw):

/opt/conda/lib/python3.8/site-packages/neo/rawio/__init__.py in <module>
    121 from neo.rawio.intanrawio import IntanRawIO
    122 from neo.rawio.micromedrawio import MicromedRawIO
--> 123 from neo.rawio.neuralynxrawio.neuralynxrawio import NeuralynxRawIO
    124 from neo.rawio.neuroexplorerrawio import NeuroExplorerRawIO
    125 from neo.rawio.neuroscoperawio import NeuroScopeRawIO

/opt/conda/lib/python3.8/site-packages/neo/rawio/neuralynxrawio.py in <module>
    121 from neo.rawio.intanrawio import IntanRawIO
    122 from neo.rawio.micromedrawio import MicromedRawIO
--> 123 from neo.rawio.neuralynxrawio import NeuralynxRawIO
    124 from neo.rawio.neuroexplorerrawio import NeuroExplorerRawIO
    125 from neo.rawio.neuroscoperawio import NeuroScopeRawIO

ImportError: cannot import name 'NeuralynxRawIO' from partially initialized module 'neo.rawio.neuralynxrawio' (most likely due to a circular import) (/opt/conda/lib/python3.8/site-packages/neo/rawio/neuralynxrawio.py)

**Comment by JuliaSprenger** [comment]
Hi @bendichter! Thanks for reporting this. I can't reproduce the error on my side and think that the line numbers in the neo modules are actually not matching the current master branch. Are you sure you have a clean neo installation? It looks like this might be a `master` version from before May 2021 (84952cd2c588c337d8520f4833892e409b9ba00e).

**Comment by JuliaSprenger** [comment]
@bendichter Did you confirm the error on your side with a recent neo version?
