### ISSUE TITLE
Improve tutorials and guidance for conversion of neuralynx .ncs to numpy arrays

### ISSUE THREAD

**Issue by 3man1992** [NeuralEnsemble/python-neo#1066]
Neo has a function NeuralynxIO that ingests a directory of .ncs files and converts into a Neo object. I can't seem to understand how to convert this neo object into a set of numpy arrays. I'm trying to achieve a matrix of (n_sample, n_channel). Please can you provide some example code or an example script to do this.

**Comment by samuelgarcia** [comment]
Hi,
Our doc is not perfect but you should have a look to:
https://neo.readthedocs.io/en/stable/core.html
https://neo.readthedocs.io/en/stable/io.html

```python
reader = NeuralynxIO(dirname='/path/to/my/folder')
seg = reader.read_segment()
anasig = seg.analogsignals[0]
print(anasig)
numpy_sig = anasig.rescale('uV').magnitude
print(numpy_sig.shape)
```

have nice coding.
