### ISSUE TITLE
docs: "List of implemented formats" is empty for IO and RawIO

### ISSUE THREAD

**Issue by bendichter** [NeuralEnsemble/python-neo#1084]
https://neo.readthedocs.io/en/stable/rawio.html#list-of-implemented-formats

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/844306/156467535-cb068878-c925-4844-9f74-e181d5fca6ba.png">

**Comment by bendichter** [comment]
Also true for io: https://neo.readthedocs.io/en/stable/io.html#list-of-implemented-formats

<img width="914" alt="image" src="https://user-images.githubusercontent.com/844306/156467682-037aba89-f573-48d2-8355-aeb180478482.png">

**Comment by samuelgarcia** [comment]
I tried a fix here #1086 
Mets see if it builds.

**Comment by JuliaSprenger** [comment]
It seems #1086 did not fix the issue, since the latest version https://neo.readthedocs.io/en/latest/io.html#list-of-implemented-formats still does not contain the list of formats.

**Comment by samuelgarcia** [comment]
This is fixed now.
https://neo.readthedocs.io/en/latest/io.html
