### ISSUE TITLE
add 'release' workflow to GH actions

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1088]
to speed up the neo release cycle it would help to have a workflow for this. This would need to cover
- [ ] check documentation is compiling
- [ ] check core and io tests are running
- [ ] check package building
- [ ] check pushing and installing from test.pypi
- [ ] push to pypi

this workflow should only be triggered by tagged commits.

**Comment by JuliaSprenger** [comment]
for comprehensive testing of documentation building we could build the doc on actions and only push the resulting html to readthedocs

**Comment by zm711** [comment]
Completed by the combo of #1380, #1373, #1376. I'll close this for now since based on the 13.0 release run on 2/2/24 the automation all seemed to work.
