### ISSUE TITLE
spike2rawio.py broken in pip package

### ISSUE THREAD

**Issue by matiusz** [NeuralEnsemble/python-neo#1089]
The package for Neo available in pip is broken - after installing it on Python 3.10 by `pip install neo` file spike2rawio.py contains some junk leftover code that is broken and prevents the script from working - 
```
/usr/local/lib/python3.7/dist-packages/neo/rawio/spike2rawio.py in _parse_header(self)
     66                 from pprint import pprint
     67                 pprint(chan_info)
---> 68                 exit()
     69 
     70 

NameError: name 'exit' is not defined
```

This piece of code in lines 66-68 is not seen anywhere on the repository and on equivalent (0.10) release on GitHub. Removing this code seems to make the script work fine.

PS. I've never actually used your library and only got interested in the issue by [this SO question ](https://stackoverflow.com/questions/71382933/nameerror-name-exit-is-not-defined-neo/71383605?noredirect=1#comment126174629_71383605), so I'm afraid I won't be able to help with any further debugging of the issue but I think whatever I provided should be enough to fix it.

**Comment by samuelgarcia** [comment]
Hi Mateuz,
this is super strange. This looks something merge in master by error.
Could you update your neo version. `pip install --upgrade neo` ?

**Comment by matiusz** [comment]
I've installed Neo fresh yesterday and the faulty code was there, today after `pip install --upgrade neo` result is the same.

**Comment by samuelgarcia** [comment]
I must have done a mistake while packaging.
I will do it again.

**Comment by samuelgarcia** [comment]
Sorry for this.
I have just push a new release 0.10.2.
