### ISSUE TITLE
Add IgorIO

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#109]
base on matlab and R we could add an igor IO

http://www.inside-r.org/packages/cran/IgorR/docs/read.ibw

https://www.mathworks.fr/matlabcentral/fileexchange/42679-igor-pro-file-format-ibw-to-matlab-variable/content/readIBWheaders.m

**Comment by wvangeit** [comment]
Just want to mention there is also a python reader for igor you could use to implement this: https://pypi.python.org/pypi/igor

**Comment by apdavison** [comment]
Leaving this open until .pxp support is added.
