### ISSUE TITLE
Add support for open ephys version 0.6

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1098]
Have you had exposure to open ephys version 0.6 yet? There appear to be some new file naming conventions, and interesting new corner cases, e.g. "CH{n}" name collisions! I've had to patch things over by parsing the "Continuous_Data.openephys" xml file, and then shimming that output to get consistent outcomes. I do hope there's an easier way that occurs to you!

_Originally posted by @miketrumpis in https://github.com/NeuralEnsemble/python-neo/issues/1055#issuecomment-1063241131_

**Comment by samuelgarcia** [comment]
@miketrumpis : do you have a dataset for dealing this problem ?

**Comment by JuliaSprenger** [comment]
Hi @miketrumpis, thanks for pointing to your custom fixes. However for a general fix it is essential to have a test dataset as reference. Do you know any public dataset in the new format or will you generate one in the future?

**Comment by zm711** [comment]
I think we fixed this recently, but if you test the current version and it is still not working please open a new issue with additional info (we now have a test file for new version and it seems to work so if it doesn't work for you we might need to tweak it a bit more).
