### ISSUE TITLE
problem when saving a block using nixio

### ISSUE THREAD

**Issue by ClaraBesserer** [NeuralEnsemble/python-neo#1102]
Hello,

Recently I encountered a problem when saving blocks with nixio. It's not constant, and I couldn't find any particularity in the data explaining why it sometimes works and sometimes don't. Here is the error message:
![Screenshot_20220318_181217](https://user-images.githubusercontent.com/87136903/159263381-74e4e6a0-b08d-4ede-953c-87855ee47d9e.png)

It seemt that the problem comes from an event's array_annotations. When I go and look at the segment's events, I have this : 
![Screenshot_20220318_181313](https://user-images.githubusercontent.com/87136903/159263511-730f4e8c-a266-4a4d-b50b-bed73a70c123.png)

I assumed that anticip_start was the problem but I re ran the code without this event and it still failed (at TTL_events). There is nothing special about anticip_start 's array_annotations, it's an array of durations (with quantities).

Do you know what could be the problem here? Thanks in advance

**Comment by samuelgarcia** [comment]
Salut Clara,
@JuliaSprenger  will be you best Friend here. She is our best nix expert.
Sam

**Comment by JuliaSprenger** [comment]
Hi @ClaraBesserer In principle it shouldn't be a problem of having a quantities array as array_annotations. Can you check you have no `None` or `NaN` in there that might cause the issue?

Just as a side note: It sounds like you might also be interested in using the `neo.Epoch` object for representing timepoints + durations.

**Comment by ClaraBesserer** [comment]
I think I have found the problem!
The event just before anticip_start is empty (a particularity of this recording) and the array_annotations were 
![Screenshot_20220322_161627](https://user-images.githubusercontent.com/87136903/159519334-5c55a793-cc49-4b4d-8a92-8b5132c90c82.png)
So empty quantity arrays. I have changed them to non-quantity arrays and it seems to work.

**Comment by JuliaSprenger** [comment]
Hi @ClaraBesserer I opened a PR to fix this issue (#1105). Can you confirm the PR solves your issue?

**Comment by ClaraBesserer** [comment]
Hello, yes it works for me!
