### ISSUE TITLE
Broken test on windows

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1106]
Hi @samuelgarcia It seems some block test breaks on windows-latest; python 3.7; numpy 1.20.3. (https://github.com/NeuralEnsemble/python-neo/runs/5659517492?check_suite_focus=true)  I tried to reconstruct the issue on my side without success. Do you have any idea what might go wrong there?

**Comment by samuelgarcia** [comment]
It sounds like it is related to spiketrainlist not being a list in shema comparison.
@apdavison : could you have a look ?

**Comment by JuliaSprenger** [comment]
What is even weirder is that for a new, unrelated PR the tests are still passing, see https://github.com/NeuralEnsemble/python-neo/runs/5659565782?check_suite_focus=true

**Comment by JuliaSprenger** [comment]
With #1105 being merged, the tests in master succeed again. It is still not clear to me why those tests failed earlier, but I will close the issue for now.
