### ISSUE TITLE
Reading raw TDT data

### ISSUE THREAD

**Issue by TdSNielsen** [NeuralEnsemble/python-neo#1110]
I am having problems figuring out how to import TDT data using the extractors sub-package of spikeinterface, which makes use of neo for the data import. In the attached example, I am trying to load data from a specific tank. In the code, folder_path points to the folder representing this tank (i.e., a folder containing all (64) channels and header files). 'eNeu1' is the stream that I wish to load, I have also tried without this argument, which throws the same error. As you can see, the code is not working - I am wondering if it is because I haven't defined "self", but I could not find documentation on this issue...
![TDT_code](https://user-images.githubusercontent.com/100342051/162469261-2687aaa0-fe9b-4030-a44c-8824571f0cce.png)
I am new to Python, so I apologize question is silly :)

**Comment by TdSNielsen** [comment]
So, I figured out what caused this problem:

If the TDT data files are located in ~/folder_1/folder_2/, the the filename of the *.Tbk file must be equal to: folder_1_folder_2.Tbk
This is a bit weird, and is not the case when using TDT's own python functions. However, now that I know this, I was able to correct it.

I am still struggling with another issue, though: If I don't specify stream_id, I get an error that multiple streams are available (['0', '1', '2', '3', '4' ]) and I have to choose one of these. This numerical indexing of the stream is not intuitive since it is difficult to know in which order the recording objects are indexed. When I do set stream_id to any of these values, I get another error further downstream (this time originating from baserecording.py (line 31, data type "<class 'int'>" not understood) instead of neobaseextractor.py). 
Besides this, it does not seem to be possible to provide any additional input arguments (like which channel(s) or time window to import, which is necessary in my case since each of my recordings are >100 GB...

Cheers,
Thomas

**Comment by samuelgarcia** [comment]
Hi Thomas,
for spikeinterface when the format is multistream you indeed to specify which one because Recording object is mono stream.
I think for tdt stream are order by descending sampling rate.
Otherwise you can also loop over then inspect channel names and properties until you find the good one.

**Comment by TdSNielsen** [comment]
Thanks @samuelgarcia, that makes sense. I have indeed been mainly trying with stream='0' because the relevant stream (store='RSn1' in TDT terminology) is first in the TDT header file. Now I just need to figure out why it throws the data type error on dtype in baserecording.py...

Do you know if it is possible to limit what data gets loaded from a stream? The relevant stream contains 64 channels, of which only 32 are relevant, and the recordings are >5 hours long, so I unfortunately wouldn't be able to load all to memory simultaneously...

**Comment by samuelgarcia** [comment]
About the error, maybe @JuliaSprenger could help I haven't play with this format for a while.

About how to limit the data loaded, no worry in spikeinterface bnothing is loaded!! All object are leazy loaded.
So you can reduce time, select some channel one this object and data are still not loaded.
Everything is lazy.
The data is retrieve at the latest moment when the sorter need it.
Have a look to this:
https://spikeinterface.readthedocs.io/en/latest/modules/core/plot_1_recording_extractor.html#sphx-glr-modules-core-plot-1-recording-extractor-py
And this
https://github.com/SpikeInterface/spiketutorials/tree/master/Official_Tutorial_SI_0.90_Aug2021

**Comment by TdSNielsen** [comment]
Thank you very much for your inputs, @samuelgarcia! :)

**Comment by JuliaSprenger** [comment]
@TdSNielsen Is this issue solved for you?

**Comment by TdSNielsen** [comment]
@JuliaSprenger No, I have not been able to resolve it: When using extractors from SpikeInterface, I get a series of errors (neoextractors/tdt.py line 27 and 21 -> neoextractors/neobaseextractor.py line 55 -> spikeinterface/core/baserecording.py line 31). I have tried to use neo.io directly instead (using tdtio and read_block() or read_segment()); this does not return any errors, but the data objects I get seem to be empty (and return errors if I try to, e.g., run preprocessing functions on them)... TDT's own package does work, but does not provide the correct data structure for SpikeInterface.

**Comment by TdSNielsen** [comment]
I never managed to get Neo to work with TDT data directly, but I ended up exporting my data to float32 binary format, which seems to work.

**Comment by JuliaSprenger** [comment]
Hi @TdSNielsen, if you could provide a small test dataset we could extend the tdtrawio to also work for datasets of your type. Feel free to drop them [here](https://amubox.univ-amu.fr/s/5Cd2BedrfJs9BQf) or open a PR to our ephy-testing-data repository on [GIN](https://gin.g-node.org/Neuralensemble/ephy_testing_data) directly.

**Comment by TdSNielsen** [comment]
Hi @JuliaSprenger, I have uploaded a short pre-experiment recording via your first link. It contains continuous recording of 64 channels, where ch. 1-32 are spike data from an MEA array.

**Comment by JuliaSprenger** [comment]
Hi @TdSNielsen! Sorry for the eternal delay. I had a look at the files you uploaded and with the current Neo version I can load these without problems. Is the issue still persisting for you?
