### ISSUE TITLE
partially broken download of test data

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1115]
In the latest runs of GH action the first attempt to fetch a data file from GIN fails with the error
```
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /home/runner/ephy_testing_data [err: 'fatal: path 'remote.log' does not exist in 'git-annex'']
```
See attempt 2 of https://github.com/NeuralEnsemble/python-neo/runs/6325659861?check_suite_focus=true
The same test run in attempt 1 were successfull 17 days earlier. 

The two attempts use the same versions of the datalad, git-annex are the same. `git` differs only in a minor version (`1:2.35.1-0ppa1~ubuntu20.04.1` vs `1:2.36.0-0ppa1~ubuntu20.04.1`). I didn't succeed in running the tests with the older `git` version again, but this seems to unlikely the reason for the failing tests, at it's on the git-annex-gin level. The respective test file on gin did not change in the last year.

@samuelgarcia Do you have any more ideas what to check? Should we removed the cached test files to check if this is the issue?

**Comment by samuelgarcia** [comment]
On spikeinterface side.
Alessio is also fightinh here : https://github.com/SpikeInterface/spikeinterface/pull/621
