### ISSUE TITLE
Compatibility for .pl2 files

### ISSUE THREAD

**Issue by KonKob** [NeuralEnsemble/python-neo#1124]
As Plexon .plx file is supported, will there also compatibility for the newer format .pl2 be implemented?

**Comment by JuliaSprenger** [comment]
Hi @KonKob! Currently we neither have example files in the new format nor precise format specifications. If you can provide those, we can start extending the Plexon support to also cover the new format.

**Comment by vincisLab** [comment]
Hi Julia,

we are also interested in neo compatibility for .pl2 files.
I attached a zip file contaning a short recording. I hope this helps.

Roberto

[CB306_060622.zip](https://github.com/NeuralEnsemble/python-neo/files/9123849/CB306_060622.zip)

**Comment by KonKob** [comment]
Hi, 

in addition: that's what I can find on the format:
https://plexon.com/wp-content/uploads/2017/06/PL2-File-System-Overview.pdf

**Comment by JuliaSprenger** [comment]
> 

That's unfortunately not a format specification as it is not describing the memory layout of the file. If you come across a more detail description, feel free to add a link here.

**Comment by vincisLab** [comment]
> 

Hi Julia,

yes I am going to deposit the file there.
Also, no problem for adding the file to your public repository. Provider is Vincis Lab @ Florida State University.

Best,
Roberto

**Comment by KonKob** [comment]
Hey guys, in the meantime I found the Software Downloads option on the Plexon website (https://plexon.com/software-downloads/#software-downloads-SDKs). Here you can find Software in C, Matlab and Python to open .pl2 files. Maybe that helps you @vincisLab!

**Comment by vincisLab** [comment]
@KonKob 
thanks!
yes we are currently using them.

**Comment by JuliaSprenger** [comment]
Thanks for the reference. I looks like there's no way to read the files without using the plexon dll, the format very secretive. I will look into adding support for pl2 based on the dll in the next weeks

**Comment by CodyCBakerPhD** [comment]
@samuelgarcia was this closed by #1214?
