### ISSUE TITLE
inconsistent parameters of NWBIO.write_block

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1128]
`write_block` methods are expected to take `self, block, **kwargs` as parameters, as. defined in https://github.com/NeuralEnsemble/python-neo/blob/ffde1764b206a8e7122e88ff974cfc40325d3333/neo/io/baseio.py#L192
@legouee Is there a particular reason why you require an additional `nwbfile` argument [here](https://github.com/NeuralEnsemble/python-neo/blob/ffde1764b206a8e7122e88ff974cfc40325d3333/neo/io/nwbio.py#L478) instead of using the `self.filename` to identify the file to write to?

**Comment by legouee** [comment]
Hi @JuliaSprenger. Following the write_block method, I restructured the code. I added all the NWB annotations and the definition of a pynwb file in the __init__ function. This therefore allows me to have the write_block method consistent with the whole python-neo code.
See PR #1166
