### ISSUE TITLE
PlexonIO incomplete event loading

### ISSUE THREAD

**Issue by doesmindmatter** [NeuralEnsemble/python-neo#113]
In Neo-0.3.1-py2.7 PlexonIO has been incompletely loading events for some event channels. (I think that the .plx files were from plexon version 102.) It seems that the imported eventarray has only 1 event for each event type for a total of the number of event labels. Some of the markers have only 0 to 1 events but some event channels should have imported hundereds of events.

**Comment by samuelgarcia** [comment]
If you are using PlexonIO, see my answer in issue #347.
