### ISSUE TITLE
Warning to user when .meta is not found for spikeglx data? 

### ISSUE THREAD

**Issue by D1o0g9s** [NeuralEnsemble/python-neo#1144]
https://github.com/NeuralEnsemble/python-neo/blob/0aa3a68629f9a6d557523c09c903ad699399b3f7/neo/rawio/spikeglxrawio.py#L241-L245

It may be helpful to have a warning when .meta is not found in a spikeglx data directory. Some data download options (e.g. gin) append '.txt' at the end of the filepath which would cause the .meta file not to be found.

**Comment by JuliaSprenger** [comment]
Maybe a good idea. @samuelgarcia wdyt?

The addition of the `txt` extension is an issue you should probably report with gin.
