### ISSUE TITLE
Check spikeglx file size comparison

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1146]
@JuliaSprenger I just checked out all the files that @TomBugnon was using, and everything looks square to me. Using Python 3.7.12, `os.stat(path).st_size` properly reports uncompressed file size, matching SpikeGLX metadata content, for every file. @samuelgarcia How confident are you that this is the check that is leading to the warning in question?

_Originally posted by @grahamfindlay in https://github.com/NeuralEnsemble/python-neo/issues/1125#issuecomment-1172531961_

**Comment by samuelgarcia** [comment]
Finally I think we need to remove it.
We will face many issues just because of this.
#1161
