### ISSUE TITLE
Fully lazy imports of IO submodules

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeuralEnsemble/python-neo#1149]
@JuliaSprenger @samuelgarcia

Hello everyone - a recent [issue on NeuroConv](https://github.com/catalystneuro/neuroconv/pull/71#issue-1330574689) drew our attention to the fact that global module import structures such as https://github.com/NeuralEnsemble/python-neo/blob/master/neo/__init__.py#L10-L11 and https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/__init__.py#L278-L379 will actively import every single format as long as the dependencies are installed.

Both we and you do, thankfully, have always used lazy importing with respect to conditional installation - module will not be loaded if it is not installed, but will through an error on attempting to utilize the IO.

However it occurred to us that as the number of formats grows, and as any tertiary or deeper dependencies in those other packages grow, the total startup time of the package grows as well as the risk that any one of those deeper dependencies may eventually have some platform, Python version, or other configuration problem (using the above issue as a prime example). It would be nice if formats or other submodule imports only occurred on-demand as it is rare for a single use-case to need immediate access to every single IO (rather, it's more typical that it might only need to access one or two).

We are apparently not alone in thinking this - in progress [PEP 690](https://peps.python.org/pep-0690/) involves a rigorous discussion about some common `importlib` tools for this functionality, though existing 5-year old [PEP 562](https://peps.python.org/pep-0562/) already defines a process for doing this. As such we were looking into implementing `__getattr_`, `__dir__`, and `__all__` overrides much like [scikit-image](https://github.com/scikit-image/scikit-image/blob/main/skimage/_shared/lazy.py#L7-L56) recently implemented.

Thing is though, if we implemented this at the NeuroConv level we would still not gain the performance benefit since any time we want to use SpikeInterface with a neo backend, the import structure would become non-lazy unless we also propagated those types of changes down to those levels (which I'd be perfectly fine helping with or doing myself).

What are your thoughts on this?

Also @alejoe91, since (I think?) it would have to occur at the SpikeInterface level as well.

CC: @bendichter

**Comment by samuelgarcia** [comment]
Hi Cody.
I totally agree.
This is something I wanted to do both in neo and spikeinterface : remove import at module level and move to on demand import in function or method.
I will try to do something soon.

**Comment by JuliaSprenger** [comment]
Fixed via #1163
