### ISSUE TITLE
Meaning of the "Block" and "Segment" objects.

### ISSUE THREAD

**Issue by lakesare** [NeuralEnsemble/python-neo#1155]
In what case are there multiple blocks per the reader object?
What does it mean semantically when `blocks = reader.read()` contains more than one `Block` object?

**Comment by apdavison** [comment]
In almost all cases a reader will only return one block. However, certain IO modules (I forget which ones) can in principle store more than one block in a file.

Neo deliberately attaches minimal semantics to the data structures, so a Block can represent whatever a user wishes; however in general a Block is used to represent data from one recording session.

**Comment by lakesare** [comment]
Thank you!
I have a similar question about `Segment`s - what are the conditions for multiple analogsignals to be put into the same `Segment`? What's meant by a "common clock/time basis"? 

![image](https://user-images.githubusercontent.com/7578559/186258624-05cc9a83-c01e-4001-ba7c-a031bab439a5.png)

**Comment by JuliaSprenger** [comment]
Having a common clock / time basis within a segment means that timestamps of objects in that segment (spiketrains, analogsignals) have the same reference time. E.g. you might have a recording that is interrupted after 5 minutes and the interruption leads to a reset of the clock of the recording system. In that case you would end up with two segments, both starting at time `0`, but the times between the segments can not be compared.
