### ISSUE TITLE
Remove the HAVE_PACKAGE logic and module import of extra dependency.

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#1160]
We have this kind of logic for many IOs
```python
try:
    import sonpy
    HAVE_SONPY = True
except ImportError:
    HAVE_SONPY = False

class SomeClass
   def __init__(self):
        assert HAVE_SONPY, 'sonpy must be installed'
```

This make importing many modules for every `import neo` because all extra dependencies are at module level.
I propose to move to "import on demand" logic with this

```python

class SomeClass
   def __init__(self):
        import sonpy
```
I propose to do this (it is easy) for the next release 0.11.0

@JuliaSprenger @apdavison : are you OK with this ?

**Comment by apdavison** [comment]
Yes, for IOs I think this makes sense, since it is rare to use more than one or two IOs in a given script

**Comment by samuelgarcia** [comment]
OK I start this soon.
