### ISSUE TITLE
not all extra_requirements pip installable

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1184]
**What is the problem?**
With the new extra_requirements["all"] field users will try to install neo from pypi using `pip install neo[all]`. However at least one dependency listed can not be installed via this, as `stfio` is not a PyPI package.

**Suggestions for fixing the problem**
We should find a way to either specify the sftio dependency in a way that it can be automatically installed or exceptionally exclude it from the list of "all" extra requirements.

**Comment by samuelgarcia** [comment]
Lets remove the line `'stimfitio': ['stfio'],` from setup if it cannot be installed from pypi.
The error will be run time if it cannot be resolve at install time no ?

**Comment by samuelgarcia** [comment]
@JuliaSprenger : note that in PR #1180 I haven't find a way to handle this all yet.
It is was dynamic (true python code) and the idea to to avoid dynamic for static declaration.
