### ISSUE TITLE
Error opening OpenEphys files with no events

### ISSUE THREAD

**Issue by mkollo** [NeuralEnsemble/python-neo#1188]
**Describe the bug**
Since 11.1.0, due to the change in openephysbinaryrawio.py, neo/rawio/openephysbinaryrawio.py", line 215, OpenEphys files without events cannot be opened:

  File "site-packages/neo/rawio/baserawio.py", line 179, in parse_header
    self._parse_header()
  File "site-packages/neo/rawio/openephysbinaryrawio.py", line 215, in _parse_header
    if states[0] < 0:
  File "site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
IndexError: index 0 is out of bounds for axis 0 with size 0

this:
`if states[0] < 0:
`
in 11.0 used to be : 
`elif 'states' in d:
`

**Comment by JuliaSprenger** [comment]
@mkollo Thank for testing the new release! Can you confirm #1189 fixes the issue?

**Comment by JuliaSprenger** [comment]
@mkollo Did you have time to check if https://github.com/NeuralEnsemble/python-neo/pull/1189 fixes the issue for you?

**Comment by mkollo** [comment]
Hi, Sorry for the delay. Yes, I tested it now, and it does fix it, thank you!

**Comment by JuliaSprenger** [comment]
Thanks!
