### ISSUE TITLE
Neo IO docs mention NeoHDF5 but it's not in the IO list

### ISSUE THREAD

**Issue by Helveg** [NeuralEnsemble/python-neo#1194]
**Which page is the problem on?**
https://neo.readthedocs.io/en/stable/io.html#preamble

> for reading/writing Neo structure in neutral formats (HDF5, .mat, …) but with Neo structure inside (**_NeoHDF5_**, NeoMatlab, …)

**What is the problem?**
This `NeoHDF5` format is nowhere to be found. I'd like to write results in Neo's HDF5 format but I can't find it in the list below.

**Suggestions for fixing the problem**
If it still exists, update the name, or suggest an alternative.

**Comment by Helveg** [comment]
I found NixIO format in the [new documentation ](https://github.com/NeuralEnsemble/python-neo/pull/1178) that suits my needs :)

**Comment by JuliaSprenger** [comment]
@Helveg Thanks for reporting this. We should make sure to remove the reference to the hdf5io the new documentation #1178

**Comment by ChauhanT** [comment]
Hi! I was wondering why the HDF5 format was dropped as it has little overhead over binary storage. Is there a discussion about this as I am really impressed with the design choices in neo and am very curious about this decision !
