### ISSUE TITLE
Error reading open ephys binary data if no event data is present

### ISSUE THREAD

**Issue by teristam** [NeuralEnsemble/python-neo#1199]
**Describe the bug**
An error will occur when reading binary open ephys data if no event data is present

**To Reproduce**
Remove the entry in the `events` field of `structure.oebin` and then try to load a binary open ephys recording

**Expected behaviour**
The recording should still be loaded successfully

**Environment:**
 - OS: Windows
 - 3.8
 - Neo version: 0.12.0.dev0
 - NumPy version: 1.21.0

**Additional context**
The `all_stream` returned from `explore_folder` may not have an `event` field, but in the following line it always assumes it is present without any check.  https://github.com/NeuralEnsemble/python-neo/blob/7fc30cb7e3aea52e9c405475c5cbb7ea96c60f3c/neo/rawio/openephysbinaryrawio.py#L82

**Comment by JuliaSprenger** [comment]
Hi @teristam, thanks for reporting this bug.
I can imaging this could also happen with other modalities. @samuelgarcia @alejoe91 Do you know which files are mandatory in the open ephys format?

**Comment by JuliaSprenger** [comment]
@alejoe91 Can you have a look at this?
