### ISSUE TITLE
module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#1208]
**Describe the bug**
Unable to instal numpy 1.24 and Neo
found with github actions using latest version of all
See: https://github.com/SpiNNakerManchester/sPyNNaker/actions/runs/3881581645/jobs/6620745703

**To Reproduce**
update numpy to latest version
install neo

**Environment:**
 - OS: [e.g. macOS, Linux, Windows]
  Linux
 - Python version
 seen with python 3.9 and python 3.8 but expected in all version 3.8 and up
 - Neo version
 10.2 and 11.1
 - NumPy version
1.24
Does not happen with numpy 1.23

**Comment by apdavison** [comment]
Thanks for reporting this. The problem no longer appears in the current master due to unrelated changes.

I've added NumPy 1.24 to the CI test matrix (see #1209)
