### ISSUE TITLE
"ValueError: time data 'File was' does not match format '%Y/%m/%d %H:%M:%S'"

### ISSUE THREAD

**Issue by eduardosand** [NeuralEnsemble/python-neo#1212]
Hi all,

Starting a project where I need to analyze Neuralynx files. When I tried to use the NeuralynxIO module and load in my data, I'm getting the following error:

`ValueError: time data 'File was' does not match format '%Y/%m/%d %H:%M:%S'`

I then tried to load in specific files and obtained the same error.

Finally, I loaded in the header information by itself to see the problem and I saw that the File Closed portion of the header has the following info:

TimeClosed File was not closed properly

which seems to track with the error.

Is there anyway to bypass this so I can still load in the data itself? I still have the marker for timecreated?

**Comment by zm711** [comment]
@eduardosand, there have been some updates to Neuralynx. Could you try your file after installing neo from source and see if this has now been resolved?

**Comment by zm711** [comment]
We have updated and so if the updates still are causing troubles please just open a new issue!

**Comment by eduardosand** [comment]
This is great! Thanks for doing this. Just checked this and now I can read in these files alright. The one thing that i would suggest going forward, is maybe to allow for empty event files? Currently, when I try to get event_timestamps, I get an indexerror because there are no events.

**Comment by zm711** [comment]
Thanks @eduardosand! That I can double check on. Feel free to ping me on this or open a new issue if it's pressing. We are away next week but happy to work on that the week after :)
