### ISSUE TITLE
Would like permission to push MED format branch

### ISSUE THREAD

**Issue by dancrepeau** [NeuralEnsemble/python-neo#1218]
Hello,

We (at Dark Horse Neuro) would like to push a feature branch with a Neo MED format wrapper.  I have a draft of the code complete, and I believe I just need permission to do the push.

The MED format is documented at (https://medformat.org/) and there is a test dataset uploaded to the electrophysiology dataset at (https://gin.g-node.org/NeuralEnsemble/ephy_testing_data).

Thank you!

**Comment by apdavison** [comment]
Hello, that's great to hear.

We use a pull-request-based contribution workflow. In other words you should push the feature branch to your own fork of the Neo repository, and then create a pull request onto the "master" branch of the main Neo repository (this one).

The new code will then be reviewed before being merged.

**Comment by JuliaSprenger** [comment]
Hi @dancrepeau! Any news on the IO implementation?

**Comment by dancrepeau** [comment]
Hi @JuliaSprenger!  Yes, I have addressed all of your issues, and currently have them pushed up in my fork.  My colleague Matt Stead and I have been verifying that multiple instances of a session can be opened in the dhn_med_py library before proceeding further, as that functionality will be important for lots projects, including Neo.

I will do another pull request in the near future.  Thank you!
-Dan

**Comment by JuliaSprenger** [comment]
@dancrepeau Thanks for putting so much effort in this. Finally #1288 is merged. :champagne:
