### ISSUE TITLE
IntanIO question

### ISSUE THREAD

**Issue by zm711** [NeuralEnsemble/python-neo#1223]
I was looking at the intanioraw.py file since Intan now has a version 3 of their software and just wanted to understand the notch-filter portion of the code. The major change for 3.x for Intan was that the notch filter now occurs at the level of the hardware as the recording is occurring whereas for <3.0 the desired notch filtered was stored in the header as 0 (no-notch), 50 or 60  and then within the python script provided a notch filter was applied. In the intanioraw I didn't see a notch filter function, but it appears the info from the header is saved. But this means that when someone inspected the notch filter section it would say 60Hz (for example), but that wouldn't actually have occurred if loading into Neo. Is that the case or did I miss something? The other problem would be that if a notch was occurring and someone was using >=3 then if they applied a post-hoc notch they would actually be applying a secondary notch over their already notched data.

Which leads to my potential enhancement: if my understanding is correct then could a flag be added to just state whether the notch actually occurred or not (ie a boolean to check for version >=3)--the current int16 supplied would still be important to indicate whether the recording occurred with European or US outlets so someone would know which frequency for a post-hoc notch.

Thanks for the help.

**Comment by JuliaSprenger** [comment]
Hi @zm711,
thanks for looking into this issue. I think the current IO was implemented before version 3 was released, so if you have some time feel free to extend it to also support the recent version.
So you are saying that the filter metadata for files version 2 are not necessarily correct for the signals that are stored in the file, but are filter settings potentially used by some unrelated python script. Neo does not apply any automatic filtering to data but provides the data as raw as possible, but feel free to extend the IO to add an annotation indicating if the filter is already applied or not.
@samuelgarcia Do you agree?

**Comment by zm711** [comment]
Thanks for the quick reply @JuliaSprenger. Happy to try to add that in.

To answer your question yes. Their own processing script (https://intantech.com/downloads.html?tabSelect=Software) has the following line:

```python
if header["notch_filter_frequency"] > 0 and header["version"]["major"] < 3:
```
which applies a software based notch filter to data for version < 3 (so both version 1 and version 2 which neo has currently implemented). So the raw data is stored without the filter until opened in Matlab or Python. As of version 3 they updated their hardware-level software and now once you turn on the filter the raw data is already saved post filter and the non-filtered data is not-saved.

I totally understand that neo doesn't implement the filter, but just didn't want people to be confused by the status of their data, especially since at least for my rig the notch is crucial for recordings.
