### ISSUE TITLE
`joblib` dependency?

### ISSUE THREAD

**Issue by joschaschmiedt** [NeuralEnsemble/python-neo#1224]
I'm currently developing a Neo reader for our in-house HDF5-based data format following the guidance provided in the [developer's guide](https://neo.readthedocs.io/en/stable/io_developers_guide.html#io-dev-guide). I noticed that `joblib` is used in `BaseRawIO.__init__`:
https://github.com/NeuralEnsemble/python-neo/blob/d550b80f08fd28570284413397ed3698b86f704e/neo/rawio/baserawio.py#L158-L162
but not listed as a dependency in [pyproject.toml](https://github.com/NeuralEnsemble/python-neo/blob/master/pyproject.toml). Is that on purpose?

**Comment by JuliaSprenger** [comment]
Good catch, looks like we forgot to list it explicitly. Can you open a PR to add it?

**Comment by joschaschmiedt** [comment]
Sure. I added it as a hard dependency to `pyproject.toml` and the docs as well: #1226

As I'm currently on Windows I cannot run all the tests as DataLad doesn't work at the moment.
