### ISSUE TITLE
Incorrect format string in strftime

### ISSUE THREAD

**Issue by tnowotny** [NeuralEnsemble/python-neo#1235]
**Describe the bug**
It appears that line
https://github.com/NeuralEnsemble/python-neo/blob/8d5d1884378258dfd6fe9b7f878c79beffe5404a/neo/io/nixio.py#L633
uses the incorrect format string "%s" instead of "%S" (capital S is the only valid format string for output in seconds as far as I can see), 
which triggers the error 
```
  File "C:\Users\tn41\anaconda3\lib\site-packages\neo\io\nixio.py", line 633, in write_block
    nix_rec_dt = int(block.rec_datetime.strftime("%s"))
ValueError: Invalid format string
```
when using ```write_block()``` of nixio.
To fix, just replace with the correct format string:
```nix_rec_dt = int(block.rec_datetime.strftime("%S"))```

**Environment:**
 - OS: Windows
 - Python version 3.9.13
 - Neo version 0.12.0 (but the error is present in the current master on github)
 - NumPy version 1.12.5

**Additional context**
Please fix; I can fork the repo and make a pull request if you prefer but it seems overkill for such a minimal change.

**Comment by JuliaSprenger** [comment]
Hi @tnowotny,
thanks for reporting this issue. In fact this a limitation of the formatting options available on Windows. I implemented a fix [here](https://github.com/NeuralEnsemble/python-neo/pull/1236). Can you confirm this solves the issue?

**Comment by tnowotny** [comment]
Hi @JuliaSprenger , I can confirm the new version with ```timestamp()``` appears to work for me. Thanks for the quick fix.
