### ISSUE TITLE
Codejam #6 : remove scalar object

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#124]
Every body agree for removing "scalar" object.

Spike is remove.
Event is remove.
Epoch is remove.
AnalogSignal is remove.

AnalogSignalArray is rename AnalogSignal and can be ND.
SpikeTrain is kept like this.
EventArray is rename Event.
EpochArray is rename Epoch.

**Comment by apdavison** [comment]
This has now been implemented.
