### ISSUE TITLE
Error reading OpenEphys Binary files

### ISSUE THREAD

**Issue by orenwilcox** [NeuralEnsemble/python-neo#1243]
I'm having trouble opening OpenEphys binary data files in Spike Interface- both data files from my own lab as well as the example OpenEphys datasets from Spike Interface. It seems like "openephysbinaryrawio.py" is getting hung up on the folder structure/empty folders if I'm reading it correctly, but I could be totally off!

From [another thread](https://github.com/SpikeInterface/spikeinterface/issues/329) on a similar issue (not the exact same error though), it seems like it's an issue with neo, as the following code results in the same errors:
````
import neo
reader = neo.OpenEphysBinaryIO('/my/folder/')
print(reader)
````
I just installed Spike Interface and all its dependencies this week, so all the versions should be up to date.

Thanks for your help, it's greatly appreciated!
<img width="837" alt="explore_folder_bug_20230329" src="https://user-images.githubusercontent.com/99053750/228709418-15ee712e-d118-4fc0-aad5-ad583570ce94.png">

**Comment by JuliaSprenger** [comment]
I think the problem might be that you are supposed to use the top folder of your dataset as recording folder. Did you try `recording_oe = se.read_openephys("D:/HFWR/OE_Data/OW004/"` or similar?
