### ISSUE TITLE
Example folder needs updating: ChannelIndex is not working

### ISSUE THREAD

**Issue by disadone** [NeuralEnsemble/python-neo#1264]
I am new to neo.
[https://github.com/NeuralEnsemble/python-neo/blob/master/examples/generated_data.py](https://github.com/NeuralEnsemble/python-neo/blob/master/examples/generated_data.py) is written four years ago. `ChannelIndex` is gone but examples are not refreshed.
Hopefully `examples` folder can be refreshed.
Thanks!

**Comment by JuliaSprenger** [comment]
Hi @disadone. Thanks for reporting.
@apdavison Do you want to include this in #1178 or should I open a new PR?

**Comment by disadone** [comment]
> 

Please include this in #1178.

**Comment by JuliaSprenger** [comment]
This issue still persists even with #1178 merged.
