### ISSUE TITLE
Incorrect `all` function used in `AnalogSignal` annotation

### ISSUE THREAD

**Issue by disadone** [NeuralEnsemble/python-neo#1281]
**Describe the bug**
Incorrect `all` function used in `AnalogSignal` annotation

**To Reproduce**
```python
from neo.core import AnalogSignal
sigarr = AnalogSignal(np.array([[1, 2, 3], [4, 5., 6]]), units='Hz',
                            sampling_rate=1*pq.Hz,t_stop=np.array(2000)*pq.ms)
xx=sigarr[:,0]
yy=sigarr[:,1]
print(xx.concatenate(yy))
```

**Expected behaviour**
It should output the concatenated `AnalogSignal`

**Environment:**
 - OS: [e.g. macOS, Linux, Windows]
 - Python 3.10.6
 - Neo 0.11.1
 - NumPy 1.23.5

**Additional context**
I want to fix the problem using pull request, however the link `https://neo.readthedocs.io/en/latest/developers_guide.html` is down.
The line `https://github.com/NeuralEnsemble/python-neo/blob/8da13dce9b8a5869e9e4d85f44a6acda83c03cfc/neo/core/baseneo.py#LL133C45-L133C48`
should be corrected into `elif isinstance(v1, np.ndarray) and np.all(v1 == v2)`

**Comment by apdavison** [comment]
The documentation has been re-written. Information for developers is at https://neo.readthedocs.io/en/latest/contributing.html

**Comment by zm711** [comment]
I'm a bit confused by this use case? Using your example we can see that:
```python
sigarr
AnalogSignal with 3 channels of length 2; units Hz; datatype float64 
annotations: {'t_stop': array(2000.) * ms}
sampling rate: 1.0 Hz
time: 0.0 s to 2.0 s

xx
AnalogSignal with 1 channels of length 2; units Hz; datatype float64 
annotations: {'t_stop': array(2000.) * ms}
sampling rate: 1.0 Hz
time: 0.0 s to 2.0 s

yy
AnalogSignal with 1 channels of length 2; units Hz; datatype float64 
annotations: {'t_stop': array(2000.) * ms}
sampling rate: 1.0 Hz
time: 0.0 s to 2.0 s
```

So xx and yy are two channels which are collected data at exactly the same time. When would it be the case that you would concatenate two channels? A standard use case is given in the `Neo` test suite

```python

signal1 = AnalogSignal([0, 1, 2, 3] * pq.V, sampling_rate=1 * pq.Hz)
signal2 = AnalogSignal([4, 5, 6] * pq.V, sampling_rate=1 * pq.Hz,
                               t_start=signal1.t_stop)

result = signal1.concatenate(signal2)
``` 

with standard order or with reverted order:
```python
signal1 = AnalogSignal([0, 1, 2, 3] * pq.V, sampling_rate=1 * pq.Hz)
signal2 = AnalogSignal([4, 5, 6] * pq.V, sampling_rate=1 * pq.Hz,
                               t_start=signal1.t_stop)
result = signal2.concatenate(signal1)
```

You can see that these are two distinct `AnalogSignal`'s that are being concatenated rather than concatenating two channels occurring at the exact same time. 

More examples at:
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/test/coretest/test_analogsignal.py

**Comment by disadone** [comment]
@zm711  Thank you! I see the problem in my question. The channel in my analysis is treated as a trial, this might be the reason I asked the question.
