### ISSUE TITLE
Googling Documentation leads to old documentation instead of new

### ISSUE THREAD

**Issue by zm711** [NeuralEnsemble/python-neo#1285]
**Which page is the problem on?**
When googling the first option that comes up is [old docs](https://neo.readthedocs.io/en/stable/) and its actually pretty hard to find the [new docs](https://neo.readthedocs.io/en/latest). In fact the new documentation doesn't even appear on the first page of my google search, although the source code is the second option for me.

**What is the problem?**
It's hard to find the current documentation. I thought maybe this was due to me previously visiting old docs, but using incognito also led to old docs. Based on the [rtd docs](https://docs.readthedocs.io/en/stable/versions.html) the url redirect should automatically go to /latest unless it has been set to go to stable instead. When I do the test of typing https://neo.readthedocs.io it auto-redirects to /stable.

**Suggestions for fixing the problem**
I was trying to find where the default branch is set for readthedocs in neo, but couldn't find it. But the default url should be changed to /latest so that it points there instead of to /stable unless the new documentation is not ready yet?

**Comment by apdavison** [comment]
We haven't made a release since updating the docs. Once we do (soon!), then "stable" should point to the new docs.

**Comment by zm711** [comment]
Thanks @apdavison. I thought they looked super nice, so just wanted to make sure that people weren't going to the wrong section. I'll close this.

**Comment by apdavison** [comment]
Thanks @zm711 we really appreciate the feedback!
