### ISSUE TITLE
neo.get_io fails on file yet to be written

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#1287]
**Describe the bug**
Calling neo.get_io no longer works with the name of a file yet to be written
which means it can no longer be uses before a 
io.write(... call

**To Reproduce**
import neo
neo.get_io("tobewritten.pkl")

**Expected behaviour**
return an io

**Environment:**
 - OS: [e.g. macOS, Linux, Windows]
 i think all but found with linux
 - Python version
 found with 3.11
 - Neo version
0.12.0
Worked in neo 0.10
 - 
 - NumPy version
not relevant

**Additional context**
our workaround is
def get_neo_io(file_or_folder):
    try:
        return neo.get_io(file_or_folder)
    except ValueError as ex:
        # As neo.get_io only works with existinf files
        _, suffix = os.path.splitext(file_or_folder)
        suffix = suffix[1:].lower()
        if suffix in neo.io_by_extension:
            writer_list = neo.io_by_extension[suffix]
            return writer_list[0](file_or_folder)

**Comment by Christian-B** [comment]
suffix = file_or_folder.suffix[1:].lower()
will be an empty sting on a directory name so check that rather than is_file() which fails is the file is yet to be written

**Comment by JuliaSprenger** [comment]
Hi @Christian-B,
the `get_io` function tries to return an instance of an io, which fails for for non-existing files for ios without writing capability. If you are just looking for a list of IOs that support a specific format, then the [list_candidate_ios](https://github.com/NeuralEnsemble/python-neo/blob/f608309c5ce031ecd905349c140b07a3dafb057d/neo/io/__init__.py#L413) function might be interesting for you.

**Comment by Christian-B** [comment]
The code just uses the file extension to work out the correct IO
it does not look at the actual file content

This worked fine in previous versions.
Why can that behaviour not be continued.
