### ISSUE TITLE
Read .lf.meta files for Neuropixels 2.0 probes

### ISSUE THREAD

**Issue by emilyasterjones** [NeuralEnsemble/python-neo#1291]
Meta files for ap and lf streams from SpikeGLX are nearly identical, so I'm not certain why [this line](https://github.com/NeuralEnsemble/python-neo/blob/4d4eb85e459c7e35cc1d43ce423fd58907fb3002/neo/rawio/spikeglxrawio.py#L402) in extract_stream_info requires you to be reading an .ap.meta file instead of an .lf.meta file. I commented out `and stream_kind == 'ap':` in my local copy of neo and it read an .lf.meta file without issue. Both .lf.meta and .ap.meta files contain the only item being parsed from meta files by this function (imAiRangeMax).

**Comment by JuliaSprenger** [comment]
@samuelgarcia  Do you know more about this?

**Comment by alejoe91** [comment]
The `lf` is not automatically generated by NP2.0 probes, which record wide-band signals. However, CatGT processing splits the wide-band stream into an `ap` and `lf` one. This should get fixed with #1327

**Comment by guptadivyansh** [comment]
Suggest closing this issue, now that the PR is accepted?

**Comment by zm711** [comment]
Fixed by #1327. Feel free to open a new issue if something else comes up.
