### ISSUE TITLE
Add workflow displatch option to run io tests also on macos

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#1295]
Currently all IO tests are running exclusively on Ubuntu. We could add a workflow version that can be triggered manually once in a while to run the IO tests also on ~~iOS~~ macos.

**Comment by zm711** [comment]
Hey @JuliaSprenger,

This is a super minor point, but just so the wrong tests don't get set up you mean macos? iOS is the Apple phone and ipad operating system (and maybe people want to use neo on mobile devices, but I don't think it would work currently).  Apple also switched over to macos from OSX within the past couple years. I assume for python it would force you to do the tests for macos only, but I'm not sure.

**Comment by JuliaSprenger** [comment]
Hi @zm711 Yes, you are right, just a classic confusion on my side. I will update the title to avoid even more confusion. Thanks for cross checking!
