### ISSUE TITLE
Inconsistent `rescale_spike_timestamp` behavior for spikes in Plexon?

### ISSUE THREAD

**Issue by h-mayorquin** [NeuralEnsemble/python-neo#1304]
In the base class the docstring of the `rescale_spike_timestamp` function claims that it should rescale timestamps to seconds:

https://github.com/NeuralEnsemble/python-neo/blob/4d4eb85e459c7e35cc1d43ce423fd58907fb3002/neo/rawio/baserawio.py#L646-L650

However, looking at Plexon it seems that the private method is in fact returning frames?

https://github.com/NeuralEnsemble/python-neo/blob/4d4eb85e459c7e35cc1d43ce423fd58907fb3002/neo/rawio/plexonrawio.py#L352-L355

This is very confusing, because in SpikeInterface we are using the `self._global_ssampling_rate` as the sampling frequency of the sorting extractor so something does not square. Is there something I am missing

All the other sorting extractors look reasonable even if I don't know everything about them:

Neuralynx:
https://github.com/NeuralEnsemble/python-neo/blob/4d4eb85e459c7e35cc1d43ce423fd58907fb3002/neo/rawio/neuralynxrawio/neuralynxrawio.py#L645-L649

Are the spiketimes of neuralynx naturally in microseconds?

Blacrock:
https://github.com/NeuralEnsemble/python-neo/blob/4d4eb85e459c7e35cc1d43ce423fd58907fb3002/neo/rawio/blackrockrawio.py#L661-L664

I am kind of surpirsed this is not done inside the `_get_spike_timestamps` in blackrock as it seems that `_get_spike_timestamps` naturally does not return timestamps?

Anyway, concerning Plexon, am I misunderstanding?
You have been working [on this recently](#1214) @JuliaSprenger so maybe you have this fresh?

**Comment by h-mayorquin** [comment]
Oh, after thinking more about this I think the behavior above is the correct one.

The central conusion comes from IMHO the very confusing fact that `_get_spike_timestamps` does NOT always return timestamps... so the function _rescale_spike_timestamp` is a patch in top of that behavior. Feel free to close this issue I think it makes sense with this.

**Comment by zm711** [comment]
Want to ping @h-mayorquin for this. Do you want more discussion around this? Or are we okay to close. 

Again simple answer is:

get_*_timestamps: returns the raw data in whatever units it is
rescale_*_timestamps: is suppose to ensure everything is in seconds.

**Comment by h-mayorquin** [comment]
No, I am closing this. I still think the name and return semantics of the function is strange and there might be something worong.  But back then fixed this at Spikeinterface by using class attributes at the level of `NeoBaseSortingExtractor`.

https://github.com/h-mayorquin/spikeinterface/blob/1be4e7e64f2b6a852b72561513b7dfa1dcc2e6b6/src/spikeinterface/extractors/neoextractors/neobaseextractor.py#L351-L365

I don't have to delve into this now so I am closing.
