### ISSUE TITLE
Single vs. multiple parent objects

### ISSUE THREAD

**Issue by toddrjen** [NeuralEnsemble/python-neo#131]
Currently, depending on how you look at it, all objects have a single parent, with the exception of the RecordingChannelGroup/RecordingChannel relationship.

However, this leads to ambiguities in certain situations.  

The most prominent is the "merge" method in container classes.  Should merging the objects change their parent?

The other major case if the user creates new, say segments for grouping their data in arbitrary ways.  Should this erase the previous segment?  This information might prove important to the user for their analysis, especially if the segment holds the data regarding the experimental conditions.  This issue becomes more serious if automatic relationship handling is implemented (see issue #125 )

So it may be a good idea to make all neo core classes support multiple parents, and have some methods provide explicit arguments to overwrite the method.  This would err on the side of preserving data.

**Comment by samuelgarcia** [comment]
Multi parent has gone
