### ISSUE TITLE
Correct handling of Sync channel for SpikeGLX and Open Ephys

### ISSUE THREAD

**Issue by alejoe91** [NeuralEnsemble/python-neo#1321]
**Describe the bug**
Both SpikeGLX and Open Ephys - Neuropix-PXI can **optionally** save a 385th SYNC channel in the binary file.

While both IOs have a `load_sync_channel` option, all cases are not currently handled. In particular:
- SpikeGLX does not check wheter a SYNC channel is present, and just remove the last channel if `load_sync_channel=False` (see [here](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/spikeglxrawio.py#L127-L128)).
- Open Ephys handles it a bit betterr, BUT it doesn't throw an error if `load_sync_channel=True`, but not present in the data (same for SpikeGLX)

**Expected behaviour**
SpikeGLX and OpenEphys correctly handle the SYNC option of NP probes in a similar way, handling all possible cases.

**Additional context**
Currently on GIN we only have:
- SpikeGLX with SYNC
- OpenEphys without SYNC

We need to gather:
- SpikeGLX without SYNC (any volunteer? @DradeAW ? )
- Open Ephys with SYNC (I can get one)

**Comment by samuelgarcia** [comment]
I do not think @DradeAW is the correct candidate for this because he is writting the thesis manuscript!
