### ISSUE TITLE
Handling of quantities

### ISSUE THREAD

**Issue by toddrjen** [NeuralEnsemble/python-neo#133]
I split this off from issue #123 

The current unit-handling class, quantities, has some major issues.  The most pressing is that it is unmaintained, and how well it will deal with future python 3.x releases is unknown.  It also has bugs that are affecting us that are probably never going to be fixed.

However, it has other issues.  For one thing, since it subclasses numpy, it requires multiple copy operations for many tasks we need.  Further, it prevents us from using numpy-like classes that support lazy loading (such as h5py).  That also means we can't attach units to anything other than numpy arrays.  If we want a single number with units, we have to use a numpy scalar.

There are also other problems.  For example, telling if two units are the same type (such as time) is difficult and slow.  Similarly, copying the units from one variable to another is difficult.

I have found another project, pint, that seems to solve most or all of these problems.  It also seems to be a smaller code-based, and is easier to define new units.

https://pint.readthedocs.org/

**Comment by samuelgarcia** [comment]
Close and leave #278 open
