### ISSUE TITLE
Improve necessary_attributes and recommended_attributes format

### ISSUE THREAD

**Issue by toddrjen** [NeuralEnsemble/python-neo#135]
Currently, the attribute list used to check attribute types uses the following format:

(('time', pq.Quantity, 1),
 ('signal', numpy, 3),
 ('datetime', datetime))

Samuel proposed the following format

[{'name' : 'time', 'type' : 'quantities', 'ndim' : 1 },
{'name' : 'signal', 'type' : 'numpy', 'ndim' : 3 },
{'name' : 'rec_datetime', 'type' : 'datetime', },]

I would propose the following alternative:

{'time': {'type': pq.Quantity, 'ndim': 1},
 'signal': {'type': pq.Quantity, 'ndim': 3},
 'rec_datetime': {'type': datetime}}

**Comment by samuelgarcia** [comment]
outdated
