### ISSUE TITLE
Remove `ignore_timestamps_error` in `OpenEphysRawIO`

### ISSUE THREAD

**Issue by alejoe91** [NeuralEnsemble/python-neo#1351]
**Describe the bug**
In #1213 we added the option to ignore timestamps errors in the Open Ephys legacy format. However, it turns out that these discontinuities could be uneven across files, so it's not a good idea to jus ignore them.

**Expected behaviour**
A better solution would be to "fill in" the missing timestamps with zeros (or NaNs) at the `get_signal_analog_chunk` level, so that all data is at least aligned

**Comment by zm711** [comment]
Fixed by #1387.
