### ISSUE TITLE
typo crashes core/analogsignal

### ISSUE THREAD

**Issue by jontis** [NeuralEnsemble/python-neo#1354]
Now, analogsignal.py row 420
                f"{self.shape[0]}; units {self.units.dimesionality.string}; datatype "

Should be:
                f"{self.shape[0]}; units {self.units.dimensionality.string}; datatype "

**Comment by samuelgarcia** [comment]
Hi thanks for this.
I will make patch.

**Comment by samuelgarcia** [comment]
I think this is not anymore the case in master branch https://github.com/NeuralEnsemble/python-neo/blob/b8989a15ff057db062fa5aefecfb7c0d12adde2f/neo/core/analogsignal.py#L420

**Comment by samuelgarcia** [comment]
We canc close.

**Comment by zm711** [comment]
That's a real typo Sam. It should be dimensionality (with an `n`). I made a PR to fix.
