### ISSUE TITLE
NeuralynxRawIO treatment of discontinuous recordings ("ring buffer gaps") [for downstream use in a higher-level API]

### ISSUE THREAD

**Issue by KristijanArmeni** [NeuralEnsemble/python-neo#1357]
### Problem description
We've recently added [support for Neuralynx files to MNE-Python](https://mne.tools/stable/generated/mne.io.read_raw_neuralynx.html) (`mne.io.read_raw_neuralynx()`, for `.ncs` files only). Thanks for providing the Neuralynx module! MNE module is essentially using `NeuralynxRawIO` to read in the arrays via `AnalogSignal.load()`. It concatenates across segments (see below) and shapes it into a format that the downstream MNE-Python functions can work with (for plotting etc.). The result is a single channels-by-time data array and the time-axis is reconstructed from the total number of samples and the sampling rate.

There is one thing we are not clear about:
Should `mne.io.read_raw_neuralynx()` check for ring buffer gaps (discontinuous recordings/invalid samples) or is `NeuralynxRawIO` taking care of that and/or raising a warning in case of temporally discontinuous samples? In other words, are `neo_block[0].segments[:]` (read in with `NeuralynxIO().read(lazy=True)`) expected to be temporally continuous or is that a wrong assumption and we should check on our end before concatenating into one large array?

### Attempted solutions at clarifying
The [neuralynxrawio.py](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio/neuralynxrawio.py#L26C1-L35C16) docstring says:  
> These variations of header format and possible differences between the stated sampling frequency and actual sampling frequency can create apparent time discrepancies in .Ncs files. Additionally, the Neuralynx recording software can start and stop recording while continuing to write samples to a single .Ncs file, which creates larger gaps in the time sequences of the samples.
>
>This RawIO attempts to correct for these deviations where possible and present a single section of contiguous samples with one sampling frequency, t_start, and length for each .Ncs file. These sections are determined by the NcsSectionsFactory class. In the event the gaps are larger, this RawIO only provides the samples from the first section as belonging to one Segment.

This doscstring strongly suggests that gaps are taken care of, but I do not understand what is meant by the last sentence.

I see that this has been extensively discussed before (#819), but I did not get clarity there as to what the current status is.

I see that [ncsssections._parseForMaxGap](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio/ncssections.py#L267) is treating gaps, but fully understanding the code base is beyond me at the moment.

### Additional information about `read_raw_neuralynx()`
In pseudocode, we essentially assume that `NeralynxRawIO.block[0].segments[:]` are all temporally contiguous, such that we simply concatenate the data read in from each neo `AnalogSignal` object (and elsewhere reconstruct the time axis based on total number of samples and sampling rate):
```
# create the channel-by-time array
data = np.concatenate(
            [
            signal.load().magnitude[:]
            for segment in neo_block[0].segments
            for signal in segment.analogsignals
            ]  
)
```

**Comment by PeterNSteinmetz** [comment]
If there are temporal gaps between records this will result in splitting into multiple Neo segments. In short, you should not need to check for the gaps as they will be represented by creating different segments.

You can choose to simply concatenate samples from different segments, but of course the times will not be strictly correct then.

**Comment by zm711** [comment]
We have update neuralynx and slightly changed how the gaps are handled. This will be included in the next release. Let us know if you have any questions, but we will close this issue.
