### ISSUE TITLE
NeoMatlabIO doesn't save groups and imagesequences to .mat

### ISSUE THREAD

**Issue by vonaviv** [NeuralEnsemble/python-neo#1358]
**Describe the bug**
I created a block (recording session) with multiple segments (trials), which include multiple spike-trains and one image sequence. After saving in .mat format and later reloading it there are no image sequence entries. 
Also, I created a group for each channel which were assigned to the block as parent. They are also not retrieved.
If I open .mat file in Matlab there are no groups and image sequences as well. 

**To Reproduce**
from neo.io import NeoMatlabIO

session  # "session" is a block with multiple segments with image sequences. 
session .groups   # has 128 groups
session.segments[0].imagesequences   # a list with one ImageSequence()

w = NeoMatlabIO(filename)
w.write_block(session)

r = NeoMatlabIO(filename)
session = r.read_block()

session.segments[0].imagesequences  # empty list
session .groups  # empty list

**Expected behaviour**
The groups and image sequences are retrieved. 

**Environment:**
 - OS: Linux (pop os)
 - Python 3.11.3
 - Neo version 0.12.0
 - NumPy version 1.24.3

**Additional context**

**Comment by apdavison** [comment]
Thank you for this report.

Indeed, NeoMatlabIO has not been updated to handle recent additions to Neo. 

(The attribute `NeoMatlabIO.supported_objects` contains `[Block, Segment, AnalogSignal, IrregularlySampledSignal, Epoch, Event, SpikeTrain]`, from which `Group` and `ImageSequence` are missing, so this is a known problem).

Any volunteers to make the necessary changes?

**Comment by zm711** [comment]
I linked a PR that can be reviewed to fix this.
