### ISSUE TITLE
Digital Channels are not available in SpikeGLX's 'nidq' stream

### ISSUE THREAD

**Issue by manimoh** [NeuralEnsemble/python-neo#1365]
**Problem Description**
Currently there is no way to access the signal/events that are recorded on the digital I/O channels of an NIDQ breakout box, when using neo (via spikeinterface, see [this issue](https://github.com/SpikeInterface/spikeinterface/issues/2242)). This is a major inconvenience with regards to analysis pipelines downstream because these signals often represent important events (experimental control, behavioral events etc.,) in the context of an experiment. 

**Solution Required**
Currently, `read_spikeglx(spikeglx_folder, 'nidq')` returns only signals from the analog channels ('XA0', 'XA1' and so on)
Ideally, we want it to return analog ('XA0', 'XA1' and so on) as well as digital ('XD0', 'XD1' and so on). 

**Alternatives Considered**
One way to extract these digital signals is to use the functionality of a tool called [catGT](https://github.com/billkarsh/CatGT), provided by the creators of spikeGLX.
Based on the documentation of catGT and how spikeGLX encodes these digital signals, I wrote a little bit of [hacky code ](https://github.com/SpikeInterface/spikeinterface/issues/2242#issuecomment-1824786428)to see how to implement it within the context of spikeglxrawio.

**Comment by yarikoptic** [comment]
@apdavison @alejoe91 ping on this issue

**Comment by alejoe91** [comment]
@yarikoptic sorry we are a bit short on time.. do you know anyone who could take a stab at this? Maybe @manimoh ?

**Comment by manimoh** [comment]
@alejoe91 Added a [PR](https://github.com/NeuralEnsemble/python-neo/pull/1383) to implement this
