### ISSUE TITLE
TDT `gain_to_uV` is incorrect 

### ISSUE THREAD

**Issue by weiglszonja** [NeuralEnsemble/python-neo#1369]
**Describe the bug**
When converting TDT data with NeuroConv noticed that the `gain_to_uV` property of the `TdtRecordingExtractor` is `1e6`. 
This doesn't seem correct, according to [this documentation] (https://www.tdt.com/docs/hardware/omnetics-analog-headstages/#lp32ch-z-32-channel-chronic-headstage) the gain is "Unity (1x)".

Looking at the raw traces they seem like already in microvolts:

<img width="500" alt="Screenshot 2024-01-10 at 15 17 29 (2)" src="https://github.com/NeuralEnsemble/python-neo/assets/24475788/ec9f6f51-7372-4626-bb0e-fdd7a6ef9479">

Neurosift:
<img width="800" alt="Screenshot 2024-01-10 at 13 09 51 (2)" src="https://github.com/NeuralEnsemble/python-neo/assets/24475788/98463a3b-158c-4d46-9146-9cb9f72b3137">

traces dtype: `int16`
traces fs: `24414.0625`

**Environment:**
 - OS: macOS
 - Python version 3.9
 - Neo version  0.12.0
 - NumPy version 1.26.2

**Additional context**

https://github.com/catalystneuro/neuroconv/issues/540

**Comment by zm711** [comment]
Howdy @weiglszonja 

Looks like @samuelgarcia wasn't sure whether it should be in V or not (see link below with note). So the `gain_to_uV` is based on the fact that he thought it was coming in as V's, but you believe it is coming in as uV? Based on your figure that seems correct. But I would let @samuelgarcia weigh in before I open a PR to fix this.

https://github.com/NeuralEnsemble/python-neo/blob/c96ec936049a125d6bedfa26b67514f927bb1ab3/neo/rawio/tdtrawio.py#L285-L289

**Comment by zm711** [comment]
@weiglszonja, I think I'll be a little busy this week, so feel free to submit a PR. Otherwise I can make a patch this coming weekend.
