### ISSUE TITLE
is a new release coming? might be worth 'auto'mating releases to make them easier

### ISSUE THREAD

**Issue by yarikoptic** [NeuralEnsemble/python-neo#1375]
ATM it is 

```shell
❯ git describe
0.12.0-328-g4ef28013
```

with 0.12.0 released (actually -- just tagged, no release on github apparently) for the point in the code from almost a year ago.

If such delays between releases is due to the burden to release, I would recommend automating releases.  There is a number of helpers which are out there and we use
- https://github.com/intuit/auto - e.g. we use it in https://github.com/dandi/dandi-cli .  The point is to
  - make descriptive PR titles which become changelog entries
  - annotate each PR with one of the labels to say what effect on version or what type of non-functionality change it is : https://github.com/dandi/dandi-cli/blob/master/DEVELOPMENT.md#labelling-pull-requests  
  - the gotcha is not to delay releases since there is an unresolved bug in auto which would fail to release if there were too many changes: https://github.com/intuit/auto/issues/1294
- in https://github.com/datalad/datalad/ we went through `auto` but people were not satisfied with such changelogs etc, so there is now https://github.com/datalad/release-action which is used along with the https://scriv.readthedocs.io/en/1.5.1/

I think just going `auto` way  would be the easiest for now, I think I should be able to help -- we migrated a good number of projects to use it .

**Comment by alejoe91** [comment]
Hi @yarikoptic 

Thanks for the pointers! We'll take a look :)

We are actually in the process of improving the release strategy of neo. Good timing for this issue: we are planning to finish up merging a few PRs and releas 0.13.0 very soon (hopefully next week!).

**Comment by zm711** [comment]
I think we have our new system in place for the moment. If there still seems to be too many delays then feel free to reopen and we can reconsider automating.
