### ISSUE TITLE
No Release on Conda-Forge

### ISSUE THREAD

**Issue by zm711** [NeuralEnsemble/python-neo#1398]
So in the documentation it says users can download from pypi or conda-forge, but we only released to pypi. Should we change docs to say that we will no longer release to conda-forge or actually plan a release to conda-forge?

**Comment by apdavison** [comment]
We do release on conda-forge, but with a delay, and we don't test the conda package ourselves.

See https://github.com/conda-forge/python-neo-feedstock

Whenever we make a PyPI release, a PR gets generated automatically, for 0.13.0 this one: https://github.com/conda-forge/python-neo-feedstock/pull/24

All we mostly need to do is update dependencies in `recipe/meta.yaml`. I will ask if you can be added to the list of maintainers, @zm711

**Comment by zm711** [comment]
Thanks @apdavison makes sense. And I owe you an email. I'll try to send next week.
