### ISSUE TITLE
common_rawio_test not respecting the NOSETESTS_NO_NETWORK environment variable

### ISSUE THREAD

**Issue by PeterNSteinmetz** [NeuralEnsemble/python-neo#1406]
The code for common_rawio_test does not presently respect the use_network variable which is set from the NOSETESTS_NO_NETWORK variable. 

This shows up when running any test. 

I would expect that when this variable is set in the environment that no attempt to download or sync the testing data is made. It should be assumed that the testing data is present.

**Comment by zm711** [comment]
See #1263. I think it is still a bit of debate the best way to accomplish this going forward.

**Comment by PeterNSteinmetz** [comment]
OK, I will close this.
