### ISSUE TITLE
Cannot open some .abf files

### ISSUE THREAD

**Issue by shankardutt** [NeuralEnsemble/python-neo#1434]
**Describe the bug**
I am trying the code below to open .abf files, for some it works greatly, while for others it is not working and I am getting error which is also given below. Using Pyabf works, but ofcourse Pyabf is slow and I really like Neo. 

**To Reproduce**
Function I used is as follows:
def load_abf_file(file_path)
        reader = neo.io.AxonIO(filename=file_path)
        block = reader.read_block(signal_group_mode='split-all')
        seg = block.segments[0]
        analogsignal = seg.analogsignals[0]
        data = analogsignal.magnitude.flatten()
        sampling_rate = analogsignal.sampling_rate.magnitude
        return data, sampling_rate

Error I am getting is:

Traceback (most recent call last):
line 173, in on_test_settings_clicked
    data, sampling_rate = self.load_abf_file(file_path)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   line 184, in load_abf_file
    reader = neo.io.AxonIO(filename=file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shankardutt/anaconda3/envs/SD_Apps/lib/python3.11/site-packages/neo/io/axonio.py", line 44, in __init__
    BaseFromRaw.__init__(self, filename)
  File "/Users/shankardutt/anaconda3/envs/SD_Apps/lib/python3.11/site-packages/neo/io/basefromrawio.py", line 77, in __init__
    self.parse_header()
  File "/Users/shankardutt/anaconda3/envs/SD_Apps/lib/python3.11/site-packages/neo/rawio/baserawio.py", line 185, in parse_header
    self._parse_header()
  File "/Users/shankardutt/anaconda3/envs/SD_Apps/lib/python3.11/site-packages/neo/rawio/axonrawio.py", line 64, in _parse_header
    info = self._axon_info = parse_axon_soup(self.filename)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shankardutt/anaconda3/envs/SD_Apps/lib/python3.11/site-packages/neo/rawio/axonrawio.py", line 452, in parse_axon_soup
    assert goodstart != -1, "This file does not contain clampex, axoscope or clampfit in the header"

You can download the file here: https://anu365-my.sharepoint.com/:u:/g/personal/u6591731_anu_edu_au/Ed8PI3vnWiJDrxienTkPQjQBT_vddFVcRwisoyO_rZTDuQ?e=mFFKZY 

**Expected behaviour**
It should load the file

**Environment:**
 - OS: macOS
 - Python version: 3.10
 - Neo version: 0.13
 - NumPy version: 1.26.0

**Comment by zm711** [comment]
Hey @shankardutt, we will check it out soon and see if we can figure out. It could be a new format so we may need to work on the rawio. Was this recorded recently or is this old data?

**Comment by zm711** [comment]
So for our test file we have
```
['', 'clampex', 'C:\\Axon\\Params\\step cclamp.pro', '_Ipatch', 'mV', 'Cmd 0', 'pA', 'Cmd 1', 'mV', 'Cmd 2', 'mV', 'Cmd 3', 'mV', '']
```
for the file you provided we have
```
['', 'OK10MHz', 'I 0', 'nA', 'V 0', 'mV', 'Vc', 'mV', 'Vc', 'mV', '']
```

So could you give us as much information about how this recording occurred since it has quite a different format then the channels we have in our testing repository. More info is better.
