### ISSUE TITLE
Direct assignment of multiple '.ncs' files in neo.io.NeuralynxIO(dirname=session_data)

### ISSUE THREAD

**Issue by NxNiki** [NeuralEnsemble/python-neo#1439]
**Is your feature request related to a problem? Please describe.**
I have Neuralynx data with micro (32k sampling rate) and macro (2k sampling rate) in the same folder. Current `NeuralynxIO` only supports assign `dirname` as a directory or `filename` as a single file. Is it possible to allow users define their files to be processed as a List of strings?

**Describe the solution you'd like**

It seems `filenames` [here](https://github.com/NeuralEnsemble/python-neo/blob/dfebe06aa390e52c51f95833c81e1a74b528b30b/neo/rawio/neuralynxrawio/neuralynxrawio.py#L186) can be directly referenced as an argument.

**Describe alternatives you've considered**

**Additional context**

**Comment by zm711** [comment]
Hey @NxNiki,

You can use the `exclude_filename` which allows you to search for some files, but not others. This is the opposite of what you want, but can be used to obtain your desired result. In this case you would give the dirname, which will scan the directory and then the files you DON'T want should be included as a list in `exclude_filename`. Let me know if that works for you.

**Comment by NxNiki** [comment]
Thank you for your answer. I think it would be better to allow for user-defined files which is more intuitive and flexible. I would like to create a PR to add this feature. Do you have any suggestions before I work on it?

**Comment by zm711** [comment]
Closed by #1440.
