### ISSUE TITLE
Read channel gain from .rec file in SpikeGadgetsRawIO.

### ISSUE THREAD

**Issue by gkBCCN** [NeuralEnsemble/python-neo#1441]
In the doc string for this class, it says:
```
Notes
-----
This file format has multiple version. New versions include the gain for scaling.
The current implementation does not contain this feature because we don't have
files to test this. So now the gain is "hardcoded" to 1, and so units are
not handled correctly.
```
It should be possible to read these from the header and a .rec file was recently added to test this.

**Comment by zm711** [comment]
Also, any interest in opening the PR for this?

**Comment by gkBCCN** [comment]
Do you mean once I have a fix?  Or preemptively?

**Comment by zm711** [comment]
Once you have a fix. One of us will work on this when we have time, but if you have experience with the files/format it would also be great if you wanted to try to make the PR yourself. Up to you :)

**Comment by gkBCCN** [comment]
Gladly.  I'm also making changes to the probeinterface and spikeinterface packages in order to support SpikeGadgets .rec files, so maybe it makes sense for me to do the same for the neo extractor.
