### ISSUE TITLE
Neuroshare.org no longer exists---drop neuroshare support?

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/python-neo#1471]
neuroshare.org no longer exists, and the python neuroshare package has not seen a release since 2016:

https://pypi.org/project/neuroshare/#history

This indicates that neuroshare is no longer an active project. Should we consider dropping it from neo perhaps?

**Comment by zm711** [comment]
I would say as long as people have the format and it is acceptable with python/numpy constraints then we can keep supporting it. Unless you see clear problems with the IO, no?

**Comment by sanjayankur31** [comment]
I wasn't aware that it's a format---the neuroshare pypi page made me think it was primarily to work with the neuroshare.org API, which no longer exists. 

Yeh, can be deprecated whenever the policy allows.
