### ISSUE TITLE
RuntimeWarning: overflow encountered in scalar multiply in axonarawio.py

### ISSUE THREAD

**Issue by SusanL82** [NeuralEnsemble/python-neo#1475]
Hello, 

I'm encountering the following error/warning in a spike-extraction script I made a while ago (also reported here https://github.com/SpikeInterface/spikeinterface/issues/2837):

I am using the detect_peaks function on a concatenated Axona recording, which has worked fine until recently on a different PC.
I've attached the script below. It's a bit long and not very elegant, but the error happens in the 'detect peaks' section, line 95-99. The main goal of the script is to detect spikes and export them so that we can use them in a manual clustering program (SpikeSort3D), I usually run it in Spyder.

For some reason, I now encounter the following:

detect peaks using locally_exclusive:  17%|#6        | 1240/7390 [00:33<02:42, 37.85it/s]
C:\Users\leemburg\AppData\Local\anaconda3\envs\SInew\lib\site-packages\neo\rawio\axonarawio.py:384: RuntimeWarning: overflow encountered in scalar multiply
  offset = i_start // 3 * (bin_dict["bytes_packet"] // 2)
detect peaks using locally_exclusive: 100%|##########| 7390/7390 [02:48<00:00, 43.92it/s] 

I have updated to Python 3.10 and installed the latest version of spikeinterface (within the latest anaconda) and the warning/error persists. Is there anything I can do about this?

**Comment by h-mayorquin** [comment]
Can you print the values over there, `print(i_start, type(i_start), bin_dict["bytes_packet"], type(bin_dict["bytes_packet"]))`

If you are able to share your data I can take a look at it.

**Comment by zm711** [comment]
the bin dict is obtained from this

```
 params = {
            "bin": {
                "filename": self.bin_file,
                "bytes_packet": 432,
                "bytes_data": 384,
                "bytes_head": 32,
                "bytes_tail": 16,
                "data_type": "int16",
                "header_size": 0,
                # bin files don't contain a file header
                "header_encoding": None,
            },
            "set": {"filename": self.set_file, "header_encoding": "cp1252"},
            "unit": {"data_type": unit_dtype, "tetrode_ids": [], "header_encoding": "cp1252"},
        }
```

which is just an int. So based on my reading it has to be `i_start` that is the problem. We feed this in at the spikeinterface level. I  have two hypotheses for this one:
1) nodepipeline get_chunk_with_margin is causing some weird i_start to be given 
2) preprocessing with recording_concatenating (see the spikeinterface issue with full script provided) is not maintaining the proper i_start.

**Comment by h-mayorquin** [comment]
Ahhh, thanks for the pointer, we are passing that as start_frame,  right?

**Comment by zm711** [comment]
To be honest I don't know the nodepipeline stuff. It is class upon class upon class inheriting from each other. So I sometimes it was called start_frame, there is "margin" argument. start_frame2. So I was trying to track this a bit, but I couldn't sort the logic out. I was actually going to ping you, but it seemed like a slog, so I didn't want to volunteer you to track down a super deep numpy value :) But if you're interested. 

I haven't looked a concatenate recording yet. I was wondering if maybe this is an off by one type error where because the recordings are concatenated maybe when we get the margin it adds a margin somewhere it wouldn't if the recordings weren't concatenated, but I wasn't sure the best way to test that at the moment and then Sam responded on the SI side saying we need to look into it more.

**Comment by h-mayorquin** [comment]
I can take a look at the marging stuff, do take a look at concatenation.

**Comment by h-mayorquin** [comment]
I think this is a spikeinterface problem:

https://github.com/SpikeInterface/spikeinterface/pull/2854

**Comment by SusanL82** [comment]
Things have been super busy this week and didn't have time to check in on this. 
I've uploaded my data here: https://owncloud.cesnet.cz/index.php/s/u35wSdcL6qCU4Ie , in case that still helps.

**Comment by zm711** [comment]
Since we discovered this is a spikeinterface problem I'm going to close this here. We are all at a conference this week but we will try to download the google drive files early next week and test our fix on the SI side.
