### ISSUE TITLE
Unable to save neo Block for writing abf file

### ISSUE THREAD

**Issue by clckwrk22** [NeuralEnsemble/python-neo#1489]
I am analysing a single channel voltage clamp trace and load it into a 2D array (sweep;datapoint). Then I perform several calculations and want to export the cleaned file in a format that Clampfit 11.2 will understand. So far I only get errors with my code. Either the directory is not created properly or the write function gives me a "NoneType" error. I am somewhat of a Python beginner, so I would like to know how I resolve this bug and get a working abf file that I can use later for single channel analysis.

This was tested on a Windows 11 machine running Pthon 3.12 via Pycharm. Attached is my code for the saving function:

Thank you for any help and suggestions! 

Best regards,
Paul
```
def neo_abf_save(data, abf_name):
    """
    Save the given data to a new ABF file using Neo.

    Parameters:
    data (numpy.ndarray): The data array with shape (number_of_sweeps, number_of_points).
    abf_name (str): The name for the new ABF file (without extension).
    """
    # Example data array (number_of_sweeps, number_of_points)
    data_f32 = data.astype(np.float32)
    number_of_sweeps = data_f32.shape[0]
    print(data_f32.shape[0])
    number_of_points = data_f32.shape[1]
    print(data_f32.shape[1])
    sampling_rate = 100000  # Hz

    # Create a Neo Block
    block = neo.Block()

    # Iterate over sweeps and create AnalogSignals
    for sweep_index in range(number_of_sweeps):
        segment = neo.Segment(index=sweep_index)
        signal = data_f32[sweep_index, :]
        analog_signal = neo.AnalogSignal(
            signal,
            sampling_rate = sampling_rate * pq.Hz,
            units = pq.pA,  # or other appropriate units
            name = f"Sweep {sweep_index} Channel 0"  # Since there's only one channel
        )
        segment.analogsignals.append(analog_signal)
        block.segments.append(segment)
    print(block)
    # Specify the file path for the new ABF file
    output_directory = "C:/processed-CSVs-SingleChannel/"
    new_abf_file_path = os.path.join(output_directory, f"{abf_name}-corrected.abf")

    with open(new_abf_file_path, 'wb') as f:
        pass

    # Ensure the directory exists
    os.makedirs(new_abf_file_path, exist_ok=True)

    # Save the block to a new ABF file using AxonIO
    try:
        writer = neo.io.AxonIO(filename=new_abf_file_path)
        writer.write_block(block)
        print(f"ABF file saved successfully at: {new_abf_file_path}")
    except Exception as e:
        print(f"An error occurred while writing the ABF file: {e}")
```

**Comment by zm711** [comment]
Hi @clckwrk22,

could you post the actual error trace too. It would help me see which lines of code are breaking so I can help you better :)

**Comment by apdavison** [comment]
Unfortunately AxonIO does not support writing abf files. 
```
In [3]: neo.AxonIO.is_writable
Out[3]: False
```

My recommendation would be to save your data in NWB format, for example using neo.NWBIO or [NeuroConv](https://neuroconv.readthedocs.io/en/main/), and then use the .nwb files as the basis for your further analysis.

**Comment by zm711** [comment]
I'm going to close this since `abf` doesn't support writing through Neo. Let us know if you need more help, but using NWB (in some form) is probably your best bet.
