### ISSUE TITLE
Plexon signal stream_ids are not cosistent across reads

### ISSUE THREAD

**Issue by h-mayorquin** [NeuralEnsemble/python-neo#1523]
The problem is here:

https://github.com/NeuralEnsemble/python-neo/blob/315f485eb24c8d17aaebc5d6b56a336840913b66/neo/rawio/plexonrawio.py#L269-L275

We use set to form unique users group, enumerate over them to determine stream_index and use str(stream_index) as a stream_id. But this does not work because iterating over sets and determining sets is not deterministic.

**Comment by samuelgarcia** [comment]
yep. set is dangerous for that. np.unique() could be a better choice.

**Comment by zm711** [comment]
Fixed with a dictionary strategy in #1524. Closing.
