### ISSUE TITLE
Why is the event channels header dtype is in bytes?

### ISSUE THREAD

**Issue by h-mayorquin** [NeuralEnsemble/python-neo#1525]
So here:
```
_event_channel_dtype = [
    ("name", "U64"),
    ("id", "U64"),
    ("type", "S5"),  <---- HERE ATTENTION THIS IS BYTES
]
```

https://github.com/NeuralEnsemble/python-neo/blob/315f485eb24c8d17aaebc5d6b56a336840913b66/neo/rawio/baserawio.py#L123-L127

I think this might bring problems down the line. Is this intentional? it seems to me that it should be strings and in fact in Plexon is extracted as a string and implicitly converted to bytes when the header is built.

**Comment by samuelgarcia** [comment]
I guess this is me but I do not remember.
I need to read it again to refresh.
Give a couple of days.

**Comment by zm711** [comment]
Sam will comment on this shortly.

**Comment by h-mayorquin** [comment]
Ok, after personal discussion it seems it is unclear why it is this way. It seems that it was bytes so it could be generalized if the need arose. 

We should be watchful because I think the assumption that people make is that those properties are strings or numeric types and it would not play as expected when writing it to other format (like json or nwb).

**Comment by h-mayorquin** [comment]
This for example, was changed in probeinterface because we could not serialize the bytes to json:

https://github.com/SpikeInterface/probeinterface/pull/159
