### ISSUE TITLE
error when importing spikegadget .rec file with multiple NPX 1.0 probes

### ISSUE THREAD

**Issue by RobertoDF** [NeuralEnsemble/python-neo#1548]
Hi,

See SpikeInterface/spikeinterface#3383.

Loading a .rec file with multiple NPX probes, some channels belonging to group1 will have x coords corresponding to group0.

test rec file here: https://www.dropbox.com/s/bsjd1ipx430dr00/20240124_171519.rec?dl=0

```
raw_rec = read_spikegadgets(Path(r"X:\data\12\ephys\20240124_171519.rec\20240124_171519.rec") )
channel_locations = raw_rec.get_channel_locations()
df = pd.concat([pd.DataFrame(channel_locations, index=raw_rec.channel_ids), pd.DataFrame(raw_rec.get_channel_groups(), index=raw_rec.channel_ids)], axis=1)
```
You can see in the df that something is wrong, group and x coord are wrong. you ll have channels with group==1 and xcoord belonging to group 0.

**Comment by zm711** [comment]
Hey @RobertoDF, I'll have to read this carefully. I would assume this be a probe interface issue (but I see you've already linked an issue there), but maybe @alejoe91 knows better where to localize this issue.

**Comment by zm711** [comment]
Fixed at SpikeInterface level 3392.
