### ISSUE TITLE
python-neo fails to load unsorted spike channels from PL2 files

### ISSUE THREAD

**Issue by nikhilchandra** [NeuralEnsemble/python-neo#1549]
**Describe the bug**
python-neo fails to load spike channels from PL2 (Plexon2) files containing only unsorted units.

**To Reproduce**
Find a PL2 file that includes spike channels containing only unsorted units. One candidate is NC16FPSPKEVT_1m.pl2 included in the ephys_testing_data dataset. Upon loading the file using plexon2rawio, you will find that the 4 spike channels that contain spikes (SPK01, SPK05, SPK09, SPK13) are not loaded because they contain only unsorted spikes.

**Expected behaviour**
I expect channels with unsorted spikes to be included.

**Environment:**
 - OS: Windows
 - Python version: 3.11.9
 - Neo version: 0.14.0dev
 - NumPy version: 1.26.4

**Additional context**
I have a potential fix and will submit it soon.

**Comment by zm711** [comment]
thanks @nikhilchandra! We appreciate your work on this!
