### ISSUE TITLE
IntanIO function

### ISSUE THREAD

**Issue by Tevin-yue** [NeuralEnsemble/python-neo#1564]
Hi，

For the IntanIO function, I think there could be a more convenient way to get notes from the data. Currently, I can get that with this code:
~~~
import neo
test = neo.IntanIO(r'F:\MATLAB\DAT_test\info.rhd')
test.raw_annotations['blocks'][0]['segments'][0]['signals'][0]['note1']
~~~
So is there any possibility there can be an easier way to get that?

**Comment by zm711** [comment]
I think the info is also stored in the header. You could work at the rawio level if you aren't worried about blocks and segments. So instead:

```python
from neo.rawio import IntanRawIO
reader = IntanRawIO(r'xx')
reader.parse_header()
header = reader.header
```

header is a dict that should contain that info without going through blocks and segments. So it is flatter than how you are currently accessing the data.

**Comment by zm711** [comment]
@Tevin-yue actually sorry one tiny mistake. you want global info so

```python
global_info = reader._global_info
```
that will have the notes stored as the dict :)

**Comment by Tevin-yue** [comment]
Thanks a lot!
