### ISSUE TITLE
about Maxwell data

### ISSUE THREAD

**Issue by bxy666666** [NeuralEnsemble/python-neo#1570]
**Which page is the problem on?**
The URL of the documentation page where the problem is, and either copy-paste the confusing text (for a short section of text), or give the first few and last few words (for a long section).

**What is the problem?**
Is the documentation (a) confusing or (b) incorrect? In what way?

**Suggestions for fixing the problem**
If the documentation is confusing, can you suggest an improvement? If the documentation is incorrect, what should it say instead?

Hello, How can I read maxwell data to Analyzing and Plotting Data with Neo Structures?

**Comment by zm711** [comment]
We have a `MaxwellRawIO` and a `MaxwellIO` so it depends on what you want to do. 

```python
import neo
data = neo.MaxwellIO('path/to/data').read()
```
would get you all the data. If you want a lower level set of arrays then:

```python
from neo.rawio import MaxwellRawIO

maxwell_reader = MaxwellRawIO('path/to/data')
maxwell_reader.parse_header()
data = maxwell_reader.get_analogsignal_chunk(xxx) # put in values based on what you want
```

**Comment by zm711** [comment]
Let me know if you need more help.
