### ISSUE TITLE
signal_channels in header information not read correctly for Neurolynx .ncs file

### ISSUE THREAD

**Issue by NxNiki** [NeuralEnsemble/python-neo#1574]
**Describe the bug**

Signal_channels in the header are empty when reading the neuralynx file.

**To Reproduce**
I have a neuralynx file and when I read it with this code:

```
reader = neo.io.NeuralynxIO(dirname=folder_path, include_filenames=file_name)
header = reader.header
signal_channels = header.get('signal_channels', [])
signal_channels['name']
Out[20]: array([], dtype='<U64')
signal_channels['sampling_rate']
Out[21]: array([], dtype=float64)
```

The signal_channels and sampling_rate are empty. 

**Expected behaviour**
My neuralynx file has the following header:

######## Neuralynx Data File Header
-FileType NCS
-FileVersion 3.4
-FileUUID ded50ee7-381d-43bf-913d-eaacd544c964
-SessionUUID 3d33ae15-dd0e-4e2a-b44d-c8728eca80c7
-ProbeName 
-OriginalFileName "E:\ATLASData\D562\EXP2_Screening\2023-02-01_12-03-25\A1.ncs"
-TimeCreated 2023/02/01 12:03:25
-TimeClosed 2023/02/01 12:54:09

-RecordSize 1044
-ApplicationName Pegasus "2.1.2 "
-AcquisitionSystem AcqSystem1 ATLAS
-ReferenceChannel "Source 03 Reference 1"
-SamplingFrequency 2000
-ADMaxValue 32767
-ADBitVolts 0.000000091552734375000002
-AcqEntName A1
-NumADChannels 1
-ADChannel 81
-InputRange 3000
-InputInverted True

-DSPLowCutFilterEnabled True
-DspLowCutFrequency 0.1
-DspLowCutNumTaps 0
-DspLowCutFilterType DCO
-DSPHighCutFilterEnabled True
-DspHighCutFrequency 500
-DspHighCutNumTaps 256
-DspHighCutFilterType FIR
-DspDelayCompensation Enabled
-DspFilterDelay_µs 3984

I expect the channel_names to be 'A1' and sampling_frequency to be 2000

**Environment:**
 - OS: macOS Ventura 13.5.1
 - Python version  3.10.14
 - Neo version '0.13.3'
 - NumPy version '1.26.4'

**Additional context**

**Comment by zm711** [comment]
Is this a file you can share with us to debug?

**Comment by NxNiki** [comment]
> Is this a file you can share with us to debug?

Hi Zach, I can read the header of other .ncs files in our project. The one failed seems to be an empty file (as it only has a size of 16k). Can you send me your email so I can share the file? Thank you!

**Comment by zm711** [comment]
Could you try one thing out of curiosity since you have the file.

```python
from neo.rawio.neuralynxrawio.nlxheader import NlxHeader
header = NlxHeader('path/to/file', props_only=True)
```
If the file is empty with just a header our reader may fail, but the header reader portion by itself should work.

**Comment by NxNiki** [comment]
> Could you try one thing out of curiosity since you have the file.
> 
> ```python
> from neo.rawio.neuralynxrawio.nlxheader import NlxHeader
> header = NlxHeader('path/to/file', props_only=True)
> ```
> 
> If the file is empty with just a header our reader may fail, but the header reader portion by itself should work.

Yes, HlxHeader works!

**Comment by zm711** [comment]
Perfect. So that would be the way to read a file if it only has header information. The rest of the code is designed to prevent you from reader a file with just a header. Let us know if you run into anything else!
