### ISSUE TITLE
ebrains mirroring failing

### ISSUE THREAD

**Issue by zm711** [NeuralEnsemble/python-neo#1588]
Our action to mirror to ebrains is failing. Since this was set up by @apdavison do you want to try to figure this out. I just reran again on our most recent commit to main. Is this something that is known and we need to wait it out or should be doing something?

**Comment by apdavison** [comment]
It is currently failing because of floods in Bologna, Italy (which is where the EBRAINS GitLab is hosted).

**Comment by zm711** [comment]
Okay, that's too bad. I hope everyone in Bologna is okay. I'll close this once it's back up and running.

**Comment by zm711** [comment]
Not completely the same, but we are getting more issues with connectivity to GIN. In the past couple days we've had IO test fails due to connectivity multiple times. Do we know of anything affecting GIN hosting?

**Comment by zm711** [comment]
Mirror to ebrains worked on last PR so closing!

**Comment by apdavison** [comment]
I can confirm that the EBRAINS GitLab is back up.
