### ISSUE TITLE
PyNNNumpyIO test failures

### ISSUE THREAD

**Issue by rproepp** [NeuralEnsemble/python-neo#168]
We've known for a while that the PyNNNumpyIO sometimes apparently randomly fails a unit test. It happened again with the most recent commit to the master branch: https://travis-ci.org/NeuralEnsemble/python-neo/jobs/28405196

We need to investigate and fix this.

**Comment by apdavison** [comment]
I thought this was fixed, but apparently not - e.g. https://travis-ci.org/NeuralEnsemble/python-neo/jobs/53315650

**Comment by samuelgarcia** [comment]
@apdavison : is it OK now ?

**Comment by apdavison** [comment]
Added a deprecation warning for PyNNTextIO and PyNNNumpyIO, they will be removed for version 0.7.0

**Comment by apdavison** [comment]
Removed PyNNIO classes
