### ISSUE TITLE
Neo object IDs

### ISSUE THREAD

**Issue by asobolev** [NeuralEnsemble/python-neo#171]
The main idea is to have IOs to always return objects with the same identifiers when while reading the same file. 

This would make possible to also extend IO libraries (or any Neo backend) with new operations like update, delete etc. E.g. it would make possible to save Neo objects to the file or DB without duplicating the whole structure every time.

Technically this could be achieved by creating UUID for every Neo object. But this question is open. There could be different more or less complicated strategies.

**Comment by samuelgarcia** [comment]
Lets close this for now. Feel free to repopen something similar.
