### ISSUE TITLE
Iterating io objects

### ISSUE THREAD

**Issue by toddrjen** [NeuralEnsemble/python-neo#177]
The `read_all_blocks` method has a problem for large files: it requires loading all blocks into memory at the same time.  If implement #176 and add a `read_all` method in `BaseIO`, I would also suggest we implement an `__iter__` method.  This would just read each object in `read_all` one-at-a-time.  In `BaseIO`, `read_all` would just be `list(iter(self))`, and `__iter__` would just be `iter([self.read()])`, but one or both of these could be overrided in other classes.  This would allow a user to just do

``` Python
for obj in ioobj:
   do_something(obj)
```

This would be a good parallel to the built-in:

``` Python
for line in fileobj:
   do_something(fileobj)
```

So people reading standard python docs will be able to easily translate it into neo without needing to know or care about the details of the IO class.

**Comment by samuelgarcia** [comment]
Let close now. And reopen if someone want to implement it.
