### ISSUE TITLE
AnalogSignalArray and numpy.diff

### ISSUE THREAD

**Issue by rmeyes** [NeuralEnsemble/python-neo#192]
I encounterd a problem when changing an `AnalogSignal` to an `AnalogSignalArray` and using `numpy.diff()` function. Here's an example code:

```python
import neo
import numpy as np

anasig = neo.AnalogSignal([0,1,2]*pq.s, t_start=0*pq.s, t_stop=2*pq.s, sampling_rate=10*pq.Hz)
anasigarr = neo.AnalogSignalArray([0,1,2]*pq.s, t_start=0*pq.s, t_stop=2*pq.s, sampling_rate=10*pq.Hz)

np.diff(anasig) # works fine
np.diff(anasigarr) # gives an error
```

The Error occurs in neo/core/analogsignalarray.py 
line 193: j,k = i
ValueError: need more than 1 vlaue to unpack

**Comment by apdavison** [comment]
`AnalogSignalArray` has to be two-dimensional.

If you change the line to 
```python
anasigarr = neo.AnalogSignalArray([[0,1,2]]*pq.s, t_start=0*pq.s, t_stop=2*pq.s, sampling_rate=10*pq.Hz)
```
(note the extra square brackets)

then `numpy.diff(anasigarr)` works.

Really there should be a warning when creating an `AnalogSignalArray` with a 1D array, or it should be automatically coerced to 2D. This is done in the `apibreak` branch, where `AnalogSignalArray` and `AnalogSignal` have been merged.
