### ISSUE TITLE
PlexonIO Index Error

### ISSUE THREAD

**Issue by gcwarner1** [NeuralEnsemble/python-neo#193]
My code:

``` python
import sys
sys.path.append('/space/kgh/1/users/helmer/anaconda/lib/python2.7/site-packages/')
from neo.io import PlexonIO
dir = "/autofs/homes/008/gwarner/Space_vs_Object_Learning_Stim-Flippe-01-06-2010.plx"
reader = PlexonIO(filename=dir)
blks = reader.read(lazy=True, cascade=True)
for blk in blks:
        for seg in blk.segments:
                print seg.name
                for anasig in seg.analogsignals:
                        print anasig
        for seg in blk.segments:
                print seg
                for st in seg.spiketrains:
                        print st
```

Runs for a fairly long time before returning:

``` python
Traceback (most recent call last):
  File "neo_plx_test.py", line 7, in <module>
    blks = reader.read(lazy=True, cascade=True)
  File "/space/kgh/1/users/helmer/anaconda/lib/python2.7/site-packages/neo-0.4.0dev-py2.7.egg/neo/io/baseio.py", line 121, in read
    seg = self.read_segment(lazy=lazy, cascade=cascade,  **kargs)
  File "/space/kgh/1/users/helmer/anaconda/lib/python2.7/site-packages/neo-0.4.0dev-py2.7.egg/neo/io/plexonio.py", line 164, in read_segment
    nb_spikes[chan,unit] +=1
IndexError: index 79 is out of bounds for axis 0 with size 17
```

I added `print [chan,unit]` after line 162 in plexonio.py to try and see what was going on and it returned this:

```
[1, 0]
[2, 0]
[1, 0]
[1, 0]
[1, 0]
[1, 0]
[2, 0]
[1, 0]
[1, 0]
...
...
...
[79, 27]
```

At which point it crashed and gave the aforementioned error. I also get this (https://github.com/NeuralEnsemble/python-neo/issues/188) error when running test_plexonio.py which could be related.

**Comment by samuelgarcia** [comment]
Hi,
oups.
a new bug.
Could you open an issue and send this file ?
If the file is ligth, is it possible to make it public for unitest ?

Samuel

**Comment by gcwarner1** [comment]
Sure, how do I open an issue? I thought that was what this was.

**Comment by samuelgarcia** [comment]
Sorry.
I thougth it was on the list.

**Comment by gcwarner1** [comment]
No problem. How do I upload the file? I tried doing it with GitHub's image upload but it was too big (even when zipped)

**Comment by samuelgarcia** [comment]
try wetransfer.com

**Comment by gcwarner1** [comment]
I just sent it. Please confirm that you received it and let me know if you need anything else.

**Comment by samuelgarcia** [comment]
Hi. I have the file. Thanks.
I merge the PR#190 and it works. Could you also try git pull master.
Sorry not merging #190 before.

**Comment by gcwarner1** [comment]
I just removed neo form /site-packages/ and reinstalled with the current version (https://github.com/NeuralEnsemble/python-neo). I ran my code again and got the same output. Did I pull the wrong thing?

**Comment by gcwarner1** [comment]
After updating my neo package the test_plexonio.py file runs without any problems BUT my code (shown above) gives the same error. I have no reason to believe that the file is corrupted or unreadable for any other reason so I still think there is a bug in the module.

**Comment by gcwarner1** [comment]
We're you able to run the code my Plexon file successfully or just the test_plexonio.py script?

**Comment by gcwarner1** [comment]
I'm still getting the same error (though test_plexonio.py works after pulling from the master). I've tried this on multiple machines.

**Comment by apdavison** [comment]
@samuelgarcia what is the status of this issue?

**Comment by samuelgarcia** [comment]
I don't remenber at all.
Sorry.
I guess we can close since PR#190.

**Comment by samuelgarcia** [comment]
If you are using PlexonIO, see my answer in issue #347.
