### ISSUE TITLE
.kwik file IO

### ISSUE THREAD

**Issue by lepmik** [NeuralEnsemble/python-neo#199]
Is it possible or are there any plans to make it possible to import .kwik files?

**Comment by samuelgarcia** [comment]
Hi.
Now, it is not done.
Kwik files is a feature to have in python-neo of course.
I do not know if anybody is voltunteer for coding this IO. 
It should 2 or 3 days of works.
If nobody do it, I will certanily code it but it is not planed for the next following month.

**Comment by lepmik** [comment]
Ok, I can do it if you want

**Comment by samuelgarcia** [comment]
Really ?
Great!! Welcome to neo!
I can help a bit if you want. This IO is rather complicated because almost all object are supported by the format (RecordingChannel, several Segment in one file, ....)
There is a page for IO developpers.
Start a fork from the matser and propose PR.
You will also need to give some small files for testing. We put that files on a public http and tesing use that files.
Thank you.

**Comment by lepmik** [comment]
Thanks, I will probably have some questions regarding neo preferences, but I guess I can do allot based on the old klustakwikIO. Btw, what should the io be called, its kind of from klustakwik, however the file format can and is used by other systems i.e. Open Ephys - how about DotKwikIO. We have files for testing in my lab which I can happily upload.

Can you give a link for the IO dev. page?

Another question, do you have or do you want a position representation (x,y,t) in neo? For example video tracking of an animal with chronic electrode implants.

**Comment by samuelgarcia** [comment]
I think you should not start with the old KlustakwikIO because it loads only spike times and the spike waveforms PCA projection.
Take ExampleIO and start from sratch.

See:
https://pythonhosted.org/neo/developers_guide.html
https://pythonhosted.org/neo/io_developers_guide.html

**Comment by lepmik** [comment]
@samuelgarcia Hi, I am almost finished writing a KwikIO at least for raw traces and I want to test it out with OpenElectrophy. However there is a strange bug I do not understand - when opening OpenElectrophy I can select Kwik (which is the name of the IO i have made) but when pressing Add files there are no relevant files visible for clicking even though Files of type: read the extensions defined in the io script.

**Comment by samuelgarcia** [comment]
This must be an issue of OpenElectrophy with QFileDialog.
The work arround is to remove filters in the dialog to test.
I will check.
Thnak you for the work.

**Comment by lepmik** [comment]
Hi, here is a [link](https://drive.google.com/folderview?id=0B40lnPhKINCJfkNia0hDczhRMlVmUmpPR1NCQ1o0Vnc1bW5vRGVhcE1ERV9WYWIyUVB1Zk0&usp=sharing) to output files from open-ephys. Maybe KwikTeam has a small file output from phy which we can add as well?

**Comment by lepmik** [comment]
Can you tell me when you have the files so I can delete them from my drive?

**Comment by apdavison** [comment]
I guess we close this since #204 was merged.
