### ISSUE TITLE
backwards compatibility description.py

### ISSUE THREAD

**Issue by lepmik** [NeuralEnsemble/python-neo#203]
I'm trying to run spykeviewer with latest version of neo and get an issue with neo.description, should there be a fix here in neo? (It works with neo 0.3.3 from pip)

**Comment by rproepp** [comment]
I've seen the issue and it should be fixed by updating spykeutils. I was very busy in the last few days, I'll push a fix soon.

**Comment by lepmik** [comment]
ok, nice. Did not mean to stress you... Just thought that there could be other packages depending on description.py as well - nice to have backwards compatibility.

**Comment by samuelgarcia** [comment]
The other one is openElectrophy. And it manage the the two cases: 1) with description.py (0.3.x) 2) description by classes  0.4.0-dev
