### ISSUE TITLE
Why is time_slice in AnalogSignalArray and not BaseAnalogSignal?

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/python-neo#205]
@apdavison `AnalogSignalArray` has a `time_slice` method, but it appears to do exactly what you would expect it to do if it were an `AnalogSignal` method.  In fact, you can paste the same class into `AnalogSignal` and it works.  So I propose moving `time_slice` to `BaseAnalogSignal` so it can be used for both `AnalogSignal` and `AnalogSignalArray`

**Comment by apdavison** [comment]
Since `AnalogSignal` and `AnalogSignalArray` have been merged, this issue is essentially resolved.
