### ISSUE TITLE
RecordingChannel and IrregularlySampledSignal in NeoMatlabIO

### ISSUE THREAD

**Issue by lepmik** [NeuralEnsemble/python-neo#207]
Are there any plans for implementing this? If it is implemented, can someone please tell me how to use it?

**Comment by apdavison** [comment]
Somehow I missed this ticket. @lepmik are you still interested in this feature?

**Comment by lepmik** [comment]
No, sorry, we are not using NeoMatlabIO anymore.

**Comment by apdavison** [comment]
ok, I'll close this ticket then.
