### ISSUE TITLE
SpikeTrains can be created with undefined length.

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#217]
see https://github.com/NeuralEnsemble/elephant/issues/54

**Comment by apdavison** [comment]
The correct behaviour I think would be to create a spike train of length 0.

**Comment by apdavison** [comment]
I can not reproduce this. @rgerkin : is there still a problem?

**Comment by rgerkin** [comment]
@apdavison 
I also can no longer reproduce the gist [here](https://gist.github.com/rgerkin/54aad46550c102b758bc), so it must be fixed, at least in my working copy of 0.4.0dev.
