### ISSUE TITLE
Problems with abf import via AxonIO

### ISSUE THREAD

**Issue by lukerogerson** [NeuralEnsemble/python-neo#219]
We are currently trying to import .abf files using io.AxonIO. While the loading of the file appears to work correctly, subsequent operations all return errors. The .abf version is 1026.00. Our code is as follows:

`from neo import io`
`import os`
`os.chdir('/somedir/') # Directory where file is located`
`r = io.AxonIO(filename='recording.abf')`
`type(r)` 
`# return: 'neo.io.axonio.AxonIO'`
`r.read()` 
`# return: Traceback + 'TypeError: 'str' object cannot be interpreted as an integer'`
`'r.read_segment()` 
`# return: 'AssertionError: This type is not supported by this file format for reading'`

If necessary, we can provide an .abf recording for troubleshooting.

**Comment by samuelgarcia** [comment]
AxonIO.readable_objects = [Block] so AxonIo.read_segment() is not implmented so the second error is natural.

r.read() should return a list of Block. Are you on python3 or python2.
Could you send me the abf file ?

**Comment by lukerogerson** [comment]
Using Python 3.

Abf file: https://mega.nz/#!JZYUCbwT
!_2eJj3rIWCI30qtAuX7uzT0u7rCDzcoPvhSqAhSg8xI

Thanks for your help.

Kind regards,
Luke

**Comment by samuelgarcia** [comment]
The file is c2_bwnoise.h5.
Is it an error ?

**Comment by lukerogerson** [comment]
Error on my part. Correct link:
https://mega.nz/#!JNhyGAxa!ERf1u2-IbdYuIHvpwJsGAkECxMpZbw7M16YgvDBI09g

Kind regards,
Luke

**Comment by samuelgarcia** [comment]
Hi again,
it works for both in python2 and python3



try this script please:

import neo
import numpy as np
bl= neo.AxonIO(filename = 'C2_BG.abf').read()[0]
for seg in bl.segments:
     print(seg)
     for ana in seg.analogsignals:
         print('  ', ana, ana.size, ana.max(), ana.min(), ana.times[0], 
ana.times[-1], ana.sampling_rate)



Note that recetly I push something on github for axonio
https://github.com/NeuralEnsemble/python-neo/pull/209
Could you re install python-neo from lastest git master ?


Samuel

**Comment by Silmathoron** [comment]
Hi, I seem to have a related error in python 3: testing the [doc example for AxonIO](http://pythonhosted.org/neo/io.html#neo.io.AxonIO), I ran into the following error

```shell
/home/me/.local/lib/python3.5/site-packages/neo/io/axonio.py in read_block(self, lazy, cascade)
    155 
    156 
--> 157         header = self.read_header()
    158         version = header['fFileVersionNumber']
    159 

/home/me/.local/lib/python3.5/site-packages/neo/io/axonio.py in read_header(self)
    340         that contain more information.
    341         """
--> 342         fid = struct_file(self.filename,'rb')
    343 
    344         # version

TypeError: 'str' object cannot be interpreted as an integer
```

which comes from the ``bl = r.read_block(lazy=False, cascade=True)`` line.

Lastest ``git master`` does not correct this error.
