### ISSUE TITLE
Add support for the NWB format

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#221]
NWB = "Neurodata Without Borders" https://neurodatawithoutborders.github.io
- specification - https://github.com/NeurodataWithoutBorders/specification 
- Python APIs - (1) https://github.com/AllenInstitute/nwb-api/tree/master/ainwb (2) https://github.com/AllenInstitute/AllenSDK/blob/master/allensdk/core/nwb_data_set.py (3) https://github.com/NeurodataWithoutBorders/api-python 
- sample datasets @ CRCNS - https://crcns.org/NWB 
- sample datasets @ Allen Institute - http://alleninstitute.github.io/AllenSDK/cell_types.html#neurodata-without-borders

**Comment by neuromusic** [comment]
+1

**Comment by wvangeit** [comment]
+1

**Comment by neuromusic** [comment]
as a heads-up @apdavison et al, NWB is going through a major refactor, including a new read/write API. @ajtritt & @oruebel are leading up the effort. the coming months might be a ripe time to get NWB support in Neo

**Comment by apdavison** [comment]
Thanks, @neuromusic, I had gathered something was going on from some of your recent tweets. Is the specification itself being revised much, or just the Python API? Where should I look to follow what's going on?

**Comment by neuromusic** [comment]
everything should settle down by ~ SfN. there's a lot of work being done right now, including on documentation and continuous integration

importantly, the NWB stack has been split up into an API layer, a schema specification layer, and a backend layer.

**pynwb** is the new API
- docs: http://pynwb.readthedocs.io/en/latest/
- repo: https://github.com/NeurodataWithoutBorders/pynwb

**nwb-schema** specifies the schema in a bunch of yml files
- docs: http://nwb-schema.readthedocs.io/en/latest/
- repo: https://github.com/NeurodataWithoutBorders/nwb-schema

There are some backward-incompatible changes to the schema (hence the 2.0 designation) but it's not an overhaul. Maybe we can try to get the NEO schema to become NWB 3.0 😄 

There's a google group setup, but there's nothing there beyond the announcement of the overhaul. You'l probably get more out of watching the issues on those two repos.

**Comment by apdavison** [comment]
Great, thanks for the links!

**Comment by rgerkin** [comment]
@apdavison @neuromusic Has anyone taken this up?  This seems pretty timely.  I could try to get a student on it if no one else has made any progress.

**Comment by oruebel** [comment]
@rgerkin with NWB:N 2.0 now releases, I agree that this is a good time for this. I am not aware of any specific efforts right now with regard to integration NWB with neo. If you need help from the NWB development team then this may also be a good project to consider for the next NWB hackathon in May.

**Comment by bendichter** [comment]
@rgerkin yes this is the perfect time for integration between NWB and neo! I agree with @oruebel that this would be a great project for the next developer hackathon May 15 and 16 at Janelia. Let us know if you are interested in sending people and we'll reserve space for them. If attending that hackathon is not possible, or if you want to get started beforehand, I'm happy to help.

A great way to reach out to the NWB community about these types of things is the nwb-users slack channel. I'd be happy to send invites if you provide emails.

**Comment by JuliaSprenger** [comment]
@legouee: Didn't you start looking into this at one point?

**Comment by JuliaSprenger** [comment]
I think it would be good to include this in the 0.8 release. However there is no set timeline for this release. @apdavison, @samuelgarcia How about aiming for early March?

**Comment by rgerkin** [comment]
Much progress in [this fork](https://github.com/legouee/python-neo/tree/NWB_updated) by @legouee: 
Tasks remaining include:
- [ ] Handle SpikeTrain, ImageSequence, etc. (i.e. not just AnalogSignal, Block, etc.)
- [ ] Write analyses performed on read data to analysis section of file (i.e. not just writing data back to acquisition section)
- [ ] Load and preserve content from disk that can't be read into Neo, so it can be written back into an NWB file intact (i.e. no roundtrip data loss for Neo-incompatible fields in NWB file).

**Comment by apdavison** [comment]
@rgerkin @bendichter @oruebel I've made a PR for a first usable version of NWB support in Neo (based on @legouee's fork). It's rough around the edges, much work still to do, but I think it's ready for people to try.

**Comment by JuliaSprenger** [comment]
A first implementation is merged via #796
