### ISSUE TITLE
better documentation for the `copy` argument

### ISSUE THREAD

**Issue by kylerbrown** [NeuralEnsemble/python-neo#222]
Hi all,
I'm confused about the `copy` argument when creating a new AnalogSignal. The documentation only has the default value, and no description of what it does or why one would choose True or False. I'm guessing False is more efficient?

https://github.com/NeuralEnsemble/python-neo/blob/baf6562593e85a1c041408a57a2234e5febe652a/neo/core/analogsignalarray.py#L90

Thanks!

**Comment by zm711** [comment]
Closing since analogsignalarray no longer exists.
