### ISSUE TITLE
Is it possible to slice an imported file and save only a part as a matlab formatted file?

### ISSUE THREAD

**Issue by cchorn** [NeuralEnsemble/python-neo#224]
I'm using this code to try to select only 300 s of a very long file...

from neo import Block, Segment, AnalogSignal
from quantities import kHz, ms, nA, s, uV
from neo.io import Spike2IO, NeoMatlabIO

r = Spike2IO(filename='Rawdata/nervefile1.smr')
w = NeoMatlabIO(filename='Rawdata/nervefile1.mat')
seg = r.read_segment()
select = neo.AnalogSignal(seg,sampling_rate=20*kHz,units='uV',time_units='ms',t_start=0,t_stop=300)
new_seg = Segment(name='a segment')
new_seg.analogsignals.append(select)
bl = Block(name='a block')
bl.segments.append(new_seg)
w.write_block(bl)

... but I get this error
'int' object has no attribute 'magnitude'

**Comment by samuelgarcia** [comment]
The error is :
```
select = neo.AnalogSignal(seg,sampling_rate=20*kHz,units='uV',time_units='ms',t_start=0,t_stop=300)
```

To write evrything:
```
r = Spike2IO(filename='Rawdata/nervefile1.smr')
w = NeoMatlabIO(filename='Rawdata/nervefile1.mat')
blocks = r.read()
block = blocks[0]
w.write_block(block)
```

To write a selected part:
```
r = Spike2IO(filename='Rawdata/nervefile1.smr')
w = NeoMatlabIO(filename='Rawdata/nervefile1.mat')
bl = r.read()[0]
bl.segment.analogsignals = block.segment.analogsignals[2:5]
bl.name = 'a new name'
w.write_block(bl)
```

**Comment by cchorn** [comment]
Thanks for the fast response but I still have an error ...

AttributeError                            Traceback (most recent call last)
<ipython-input-5-aa873f928f74> in <module>()
      7 w = NeoMatlabIO(filename='Rawdata/nervefile1.mat')
      8 bl = r.read()[0]
----> 9 bl.segment.analogsignals = bl.segment.analogsignals[2:5]
     10 bl.name = 'selected data'
     11 w.write_block(bl)

AttributeError: 'Block' object has no attribute 'segment'

**Comment by samuelgarcia** [comment]
Oups sorry!
```
bl.segments[0].analogsignals = bl.segments[0].analogsignals[2:5]
```

**Comment by cchorn** [comment]
It does produce a mat file with this code change but the mat file, when loaded into OpenElectrophy, only has Segment information and no analogsignals to display.

**Comment by samuelgarcia** [comment]
If you open it in matlab does the .mat file is OK ?

**Comment by cchorn** [comment]
I have not tried this because I was hoping to use OpenElectrophy spike sorting as an analysis platform, and slicing into a mat file was an intermediate step.  Is it possiible to slice spike2 files into a spike2 format using the approprate spike2 neo io, and then use in OpenElectrophy?

**Comment by samuelgarcia** [comment]
.mat file is not a very good choice (few user, used as a bridge for matlab users).
Now you can use neohdf5 but this format will be read only in next version of neo.

If you want to use OE for spike sorting. There is no need to go to an intermediate format.
Insert your data in a OE database and sort then.

If you want to slice your data. Do it in OE directly.

By slicing do mean you mean :
1- having less channel (the code I post here)
2- getting smaller signals

For the 2. you need something like that
```
new_analogsignals = []
for anasig in seg.analogsignals:
    newsig = anasig[3000:150000]


```

**Comment by cchorn** [comment]
Thank you

I did find a different solution so I'll post it here ... mainly worked by a collaborator ..

It involves building a block from scratch to store the new slice of data (from seconds 3600 to 10500).

filename='Rawdata/nervefile1.smr'
r= neo.Spike2IO(filename)
bl = r.read()[0]; asig = bl.segments[0].analogsignals[0]
start = 3600
end = 10500
newfilename = "Rawdata/B2b.h5"
start1 = start * 20000
end1 = end * 20000
new_asig = asig[start1:end1]
seg = neo.Segment()
seg.name = 'New segment'
seg.description = 'Sample'
seg.index = 0
seg.analogsignals = []
seg.analogsignals.append(new_asig)
rec = neo.RecordingChannel()
rec.analogsignals = []
rec.analogsignals.append(new_asig)
recg = neo.RecordingChannelGroup()
recg.recordingchannels = []
recg.recordingchannels.append(rec)
recg.name = 'New group'
b = neo.Block()
b.name = 'New block'
b.segments = []
b.segments.append(seg)
b.recordingchannelgroups = []
b.recordingchannelgroups.append(recg)
w = neo.io.NeoHdf5IO(newfilename)
w.write_block(b)
w.close()

... writing with neohdf5 seems to be an important feature

**Comment by apdavison** [comment]
To clarify about NeoHDF5: the next version of Neo will provide read/write support for two other, more widely used HDF5-based formats - NIX and NWB. We therefore plan to retire the Neo-only NeoHDF5 format in favour of the more standard ones, and any existing NeoHDF5 files will be simple to convert into either NIX or NWB.

**Comment by cchorn** [comment]
Thank you
That should be very useful!
