### ISSUE TITLE
units should not require unit magnitude

### ISSUE THREAD

**Issue by kylerbrown** [NeuralEnsemble/python-neo#226]
Hello,

Right now, neo enforces the `units` attribute to have unit magnitude, e.g. `1*uV`.

There at least two situations where I disagree with this rule.
1) When using fixed gain amplifiers, such as the popular Intan chips used in the Open Ephys, there is a known constant conversion from a binary integer value to a microvolt value. The 16 bit integer is a much more efficient storage option (both in space and speed) than converting all the values to a 64 bit floating point value required to represent the true microvolt magnitude. Therefore, I'd like to store the units as `0.195 uV`.
2) For some event data, the values may be in samples, and the units therefore, are `1/sampling_rate * s`. For the reasons mentioned in (1), and to eliminate any added floating point error. I'd like to be able to store them in there original integer format.

Curious what you think! (And thanks for working on NEO)

**Comment by apdavison** [comment]
I'm not sure this was a deliberate decision. Can you give a short example of code which doesn't work (together with the Traceback), which you think ought to work?

**Comment by samuelgarcia** [comment]
I am agree with this.
But this depend on each IO to implement it or not.

Now the io api have been split in two part. BaseFromRaw is a wrapper for neo.io on top on neo.rawio.

So we could add an option in BaseFromRaw.read_block, for instance **quantity_mode**:
  * **quantity_mode='float_magnitude'** would lead to [0.2, 0.4, .6, .8] * pq.uV
  * **quantity_mode='raw_magnitude'** would lead to [1, 2, 3] * (0.2*pq.uV)

I guess this can be iplemenetd with quantities.CompoundUnit but I am not sur.

**Comment by samuelgarcia** [comment]
This will be implemented in proxy object.

**Comment by samuelgarcia** [comment]
#461 implement this feature but it is postpone to 0.8.
