### ISSUE TITLE
Memmapping not working for TdtIO

### ISSUE THREAD

**Issue by npyoung** [NeuralEnsemble/python-neo#227]
Using memmapping to avoid memory errors as the comments suggest (see https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/tdtio.py#L214) doesn't work. The error comes from `bk` ending up as `None` somehow, so `bl.create_many_to_one_relationship()` fails. No idea how this is happening or why it doesn't just work. Maybe @samuelgarcia can shed some light on this?

**Comment by samuelgarcia** [comment]
Is it still the case with the new TdtIO based on TdtRawIO ?

**Comment by samuelgarcia** [comment]
It passes tests so U guess this is OK now.
