### ISSUE TITLE
SpikeTrain redundancy in neo hdf5

### ISSUE THREAD

**Issue by lepmik** [NeuralEnsemble/python-neo#229]
When saving SpikeTrain in neo hdf5, segment and recordingchannelgroup seems to each require storage space for the SpikeTrain i.e. doubling the size of the hdf5 file.

HDF5 allows for softlinks, could units in rcgs link to spiketrains in its respective segment?

**Comment by rproepp** [comment]
Neo uses HDF5 hard links, so there should not be any duplicate storage use.

**Comment by lepmik** [comment]
I see now that I didn't check this thorough enough,. It was a while ago since I saw an increase in file size but must have done some other error myself. Sorry for taking up your time
