### ISSUE TITLE
Opening Spike2IO files

### ISSUE THREAD

**Issue by SuperSonicHedgehog** [NeuralEnsemble/python-neo#230]
Hi,
I was working on a Spike2IO file and it worked perfectly well, and now, I cannot open any of the other Spike2IO files I want to analyze. The person who gave me the files swears that there is no difference between them.

When I execute this :
reader = neo.io.Spike2IO(filename = '2015_03_12_16_25_47.SMR')
block_list = reader.read()

Python says : ValueError : total size of a new array must be unchanged. (it seems that there is a problem with the "headers").

I saw that someone here https://groups.google.com/forum/#!topic/neuralensemble/n1ws8VoYBaw had exactly the same problem as me but I could not find the answer anyway.

Could someone please help we find a solution ??

Thanks,

Alexia

**Comment by samuelgarcia** [comment]
Hi,
could you send me the file please ?

Samuel

**Comment by SuperSonicHedgehog** [comment]
Here is an example of a file that I cannot open : https://www.dropbox.com/s/3jb0o0rzk04w5q3/2015_03_12_16_25_47.SMR?dl=0

Alexia

**Comment by samuelgarcia** [comment]
Just for helping me debugging : how many channels do you have in the waveforms ?

**Comment by samuelgarcia** [comment]
I try a ptach could you test it by installing this branch.

**Comment by SuperSonicHedgehog** [comment]
It looks like it works. Thank you very much for your help !

**Comment by samuelgarcia** [comment]
I only hope this patch won't break any working files...

**Comment by SuperSonicHedgehog** [comment]
I have checked that the working files still worked before rejoicing. If something goes wrong I'll come back !

**Comment by SuperSonicHedgehog** [comment]
Hi,
I am back with a problem similar to the one I had two weeks ago.

When I execute this :
reader = neo.io.Spike2IO(filename = '2015_03_12_16_25_47.SMR')
block_list = reader.read()

I get either a "ValueError : negative dimensions are not allowed" for one file (I think the problem is the file size, 8.10^6 ko), or a "IndexError : index 0 is out of bounds for axis 0 with size 0" for two other files. Here is one of them (2015_03_05_10_09_45.SMR) : https://www.dropbox.com/sh/jknqkrsy7t2v0be/AACrefyxxrMTPEBLrQrljkB4a?dl=0 . You will also find the file 2015_03_12_16_25_47.SMR, which works. I have four other Spike2IO files that work well. 

I'm using the new patch (and I don't know if the files worked with the old version. I cannot check because I erased the old version while installing the new patch).

I would be very grateful if you could fix it !

Thanks, 

Alexia
