### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#233]
and put on binstar

**Comment by jakirkham** [comment]
I don't know if it is sufficient for you, but this is on `conda-forge`. Here is the repo ( https://github.com/conda-forge/python-neo-feedstock ). I would happily give you permissions on it so you can easily make releases. Just let me know.

**Comment by jakirkham** [comment]
Thanks for this nice package BTW. 😄

**Comment by dizcza** [comment]
Please add a line how to install neo with conda in docs here https://neo.readthedocs.io/en/latest/install.html and https://github.com/NeuralEnsemble/python-neo/blob/master/doc/source/install.rst

`conda install -c conda-forge python-neo`

**Comment by dizcza** [comment]
BTW, it's not good to have different names of the same package for conda and pip. Consider renaming conda's `python-neo` to just `neo` to be consistent with pip.
