### ISSUE TITLE
Empty Eventarrays - Spike2

### ISSUE THREAD

**Issue by razi000** [NeuralEnsemble/python-neo#236]
Hi,

I am a researcher in cardiac electrophysiology and stumbled across the neo project. Its actually quite exciting - cardiac EP is niche and faces similar issues to neuro EP. A cross platform pure python API like neo is ideal! However, I am having trouble reading in the eventarrays/accessing the eventarrays in the Spike2 implementation - they all seem to be empty (unless I am missing something very basic!). Some example code:

from neo.io import Spike2IO
reader = Spike2IO('myfile.smr')
bl = reader.read(cascade = True, lazy = False)[0]
print(bl.segments[0].eventarrays[0])

returns 
<EventArray: >

bl.segments[0].eventarrays[0]

returns 
EventArray
annotations: {'channel_index': 2,
  'comment': b'',
  'physical_channel_index': 0,
  'title': b'Stim'}

but there doesnt seem to be any values in the array! This is the case for multiple files I have. I dont seem to have a problem accessing other classes of objects - analogsignals and their attributes all behave as I expect them to etc.

Am I missing something very obvious here?

**Comment by apdavison** [comment]
Which version of Neo are you using?

**Comment by razi000** [comment]
So using pip freeze command I get 

neo==0.3.3

I have done some further tests on different files, and all the same:

`print(bl.segments[0].eventarrays[0]) `
returns
`<EventArray: >`

In files with multiple event arrays, all event arrays are empty.

**Comment by samuelgarcia** [comment]
Hi,
could you try the master branch ?
here:
https://github.com/NeuralEnsemble/python-neo/archive/master.zip

Samuel

**Comment by razi000** [comment]
installed successfully 
neo==0.4.0.dev 
Same problem unfortunately

**Comment by samuelgarcia** [comment]
Could you send one file please ? (dropbox or wetransfer or whatyou want )

**Comment by razi000** [comment]
https://drive.google.com/open?id=0Bw8fKhYt0YfUMmg1Zm1PX0ttQnc

**Comment by samuelgarcia** [comment]
Hi,
thanks.


I am able to see some event in your dataset.
Could you try this:

```
bl = neo.Spike2IO(filename = 'razi000 spike2/test.smr').read()[0]
seg = bl.segments[0]

for anasig in seg.analogsignals:
    print anasig.shape
    print anasig.sampling_rate

for ea in seg.eventarrays:
    print 'ea'
    print ea.name, ea.times.size, ea.annotations
    print ea.times  # this is a quantity array
    print ea.times.magnitude  # this is a numpy.array
    print ea.labels # this a numpy.array (empty in your case)

```

**Comment by razi000** [comment]
Thanks, thats great!

Didnt realise the eventarrays class had those methods - I was going by how the other objects in neo worked (eg analogsignals). My mistake.

Though perhaps it would be good to update the documentation to show this?

**Comment by samuelgarcia** [comment]
neo APi for that version is not consitent because for analogignal and spiketrain the data hold by inheritence. For EventArrat and EpochArray data are attributes. this is bad. Sorry.

This is more or less describe here https://pythonhosted.org/neo/core.html
See inheritance.
If you have better idea send PR for the doc.

**Comment by apdavison** [comment]
Just a note that in Neo 0.4 (currently under development), EventArray and EpochArray will work the same way as AnalogSignal/SpikeTrain (using inheritance).
