### ISSUE TITLE
Blackrock 2.2 support on Python 3.x

### ISSUE THREAD

**Issue by jakirkham** [NeuralEnsemble/python-neo#243]
I see that we are currently constrained to using Blackrock 2.1 files. Is it possible to have support for 2.2 files?

**Comment by jakirkham** [comment]
Just saw this in the mailing list ( https://groups.google.com/forum/embed/#!topic/neuralensemble/kUlwtYAoXAk ) and am acquanting myself with PR ( https://github.com/NeuralEnsemble/python-neo/pull/181 ) to see if this will solve my problem.

**Comment by jakirkham** [comment]
Turns out this pretty much worked out of the box. I needed a few tweaks for Python 3.x, but otherwise this seems to be doing well. See this PR ( https://github.com/NeuralEnsemble/python-neo/pull/244 ) for the changes.

**Comment by samuelgarcia** [comment]
There is a new V4 BlackrockIO made by Lyuba and Michael here:
https://github.com/NeuralEnsemble/python-neo/pull/239

It is comatible with the very (and simplifyed) new neo object model made by Andrew recently in the branch apibreak.
https://github.com/NeuralEnsemble/python-neo/tree/apibreak


Maybe you should go for it.

**Comment by jakirkham** [comment]
Sure, I can give it a try.

Though the only issues I had were Python 3.x compatibility really. It seems a few minor tweaks via this PR ( https://github.com/NeuralEnsemble/python-neo/pull/244 ) was sufficient to get it working on Python 3.x. Python 2.x still works with those changes too.
