### ISSUE TITLE
Backport IgorProIO into 0.4.x?

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/python-neo#261]
@apdavison  I'm interested in using the IgorProIO module and possibly expanding it to include other IgorPro file formats (such as importing all traces from a given path in a .pxp file).  Would you let me backport it into 0.4.x?  Or do I need to suck it up and get my projects working with 0.5 first?

**Comment by apdavison** [comment]
@rgerkin Here's the deal: if you add .pxp support in 0.5* you have my permission to backport it to 0.4 (-;

*which should be easy since the underlying `igor` module supports .pxp already

**Comment by rgerkin** [comment]
@apdavison 
I've added preliminary support for importing data from .pxp files [here](https://github.com/rgerkin/python-neo/commit/6dcc78c3009131018a34be13eb2115e3acd0a853), demonstrated [here](https://github.com/rgerkin/python-neo/blob/igor-pxp-support/igorio.ipynb).  
Could you assign this issue to me, so I can see it in my dashboard and be sure to finish it?

**Comment by rgerkin** [comment]
Implemented in #363 (and I no longer need to backport to neo 0.4 since I am moving my things to 0.5).
