### ISSUE TITLE
issue in creating protocol signals in read_protocol() of io/axonio.py

### ISSUE THREAD

**Issue by lbologna** [NeuralEnsemble/python-neo#272]
Hi, 

I am using neo for reading .abf files and extracting step stimuli start and end times.
I noticed that in the last line of the following for loop (lines 578:587 of _read_protocol()_ in _io/axonio.py_, ) the _epoch['lEpochDurationInc'] * epiNum_ is not taken into account when updating the _i_last_ index.
Shouldn't the last line be: _i_last = i_end_ so that epochs with increasing duration are not overwritten by the following ones?

Thanks in advance for your answer.

Best regards,
Luca

                    for epochNum, epoch in iteritems(epochInfo):
                        i_begin = i_last
                        i_end = i_last + epoch['lEpochInitDuration'] +\
                            epoch['lEpochDurationInc'] * epiNum
                        dif = i_end-i_begin
                        ana_sig[i_begin:i_end] = np.ones((dif, 1)) *\
                            pq.Quantity(1, unit) * (epoch['fEpochInitLevel'] +
                                                    epoch['fEpochLevelInc'] *
                                                    epiNum)
                        i_last += epoch['lEpochInitDuration']

**Comment by lbologna** [comment]
Ok,
Thanks a lot!

Luca

**Comment by samuelgarcia** [comment]
Should #396
