### ISSUE TITLE
Unique id attribute to ChannelIndex

### ISSUE THREAD

**Issue by lepmik** [NeuralEnsemble/python-neo#273]
Hi,

Currently `ChannelIndex.name` is the only attribute that has a reference or id to a set of channels. When making software that refer to a specific set of channels you have to either rely on user defined names or annotations. I would thus suggest to add a `group_id` attribute to `ChannelIndex` which is `int` and if not set by the user, then set automatically as a counter such that one can always refer to `ChannelIndex.group_id`.

**Comment by samuelgarcia** [comment]
This is outdated.
