### ISSUE TITLE
nixio file not closed

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#275]
When using the nixio in an ipython notebook, written files are only valid after the kernel is restarted. If one tries to load a nix file created in a separate notebook without explicitly stopping the kernel of that notebook, the file turns out to be corrupted and can not be read.

Suggestions
- A quick fix for this is to manually close the file after writing to file by calling nixio.nix_file.close(). However, I think a nixio.close() function, which closes all files would be more intuitive.
- In the long run it would be nice to use the nixio as a context manager, so one does not need to close files explicitly. Currently python returns an AttributeError: __exit__ when calling
```
with neo.NixIO('data.nix','ro') as nix:
    pass
```

**Comment by achilleas-k** [comment]
Hello @JuliaSprenger.

The lack of an explicit `close()` method is indeed an issue. I'm not sure how I feel about a `nixio.close()` function on the entire namespace. Given that the general convention with importing IOs is `from neo.io.Xio import X` or as you mentioned in the last example, simply importing neo and using `neo.NixIO(...)`, a method that closes all open NixIO files might not be directly accessible. 

I like the context manager idea, though. This would be especially nice given how there's no real reason to keep the file open after reading or writing. So a common use case would be:
```python
with neo.NixIO("data.nix", "ro") as nix:
    blocks = nix.read_all_blocks()

...
<work with blocks>
...

with neo.NixIO("newdata.nix", "ow") as nix:
    nix.write_all_blocks(blocks)
```

and there would be no issue with open files.
