### ISSUE TITLE
Problem reading AxonIO files from within python3.4

### ISSUE THREAD

**Issue by ctigaret** [NeuralEnsemble/python-neo#288]
Hello all,

I'm trying to use neo from within python3.4 to read AxonIO files and I keep getting the following error, both on an axon file dowloaded from the abf files provided as examples on your site, and also from an ABF file generates in my lab using Clampex 10.1. Using Python 3.4.5 (default, Jul 03 2016, 13:32:18) [GCC] on linux (OpenSUSE Leap 42.1)

>>> import neo
>>> fileio = neo.io.AxonIO("File_axon_1.abf")
>>> fileio.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cezar/.local/lib/python3.4/site-packages/neo/io/baseio.py", line 116, in read
    return [self.read_block(lazy=lazy, cascade=cascade, **kargs)]
  File "/home/cezar/.local/lib/python3.4/site-packages/neo/io/axonio.py", line 261, in read_block
    nbchannel)).astype('f')
TypeError: 'float' object cannot be interpreted as an integer

>>> baseio = neo.io.AxonIO("base_0000.abf")
>>> baseio.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cezar/.local/lib/python3.4/site-packages/neo/io/baseio.py", line 116, in read
    return [self.read_block(lazy=lazy, cascade=cascade, **kargs)]
  File "/home/cezar/.local/lib/python3.4/site-packages/neo/io/axonio.py", line 261, in read_block
    nbchannel)).astype('f')
TypeError: 'float' object cannot be interpreted as an integer.

PLEASE NOTE, this does not happen from python 2.7 (Python 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC] on linux2)
>>> import neo
>>> fileio = neo.io.AxonIO('File_axon_1.abf')
>>> baseio = neo.io.AxonIO('base_0000.abf')
>>> fileio.read()
[<neo.core.block.Block object at 0x7f598b9945d0>]
>>> baseio.read()
[<neo.core.block.Block object at 0x7f598b994690>]

I would very much like to continue using python3 in my project, so any help would be very much appreciated.

Many thanks,

Kind regards,

Cezar

**Comment by ctigaret** [comment]
Well, tt turns out that the culprit is the code on lines 260 & 261 in module neo.io.axonio:
subdata = subdata.reshape((subdata.size/nbchannel,
                                               nbchannel)).astype('f')

and in particular the division subdata.size/nbchannel; both are indeed int, but in python 3 this generate a float, whereas in python 2 this generates an int.

A quick workaround is to write instead, the following:
subdata.size//nbchannel

where the result (on both versions of python) will be an int

or coerce the result by writing 
 int(subdata.size/nbchannel)

It seems to me this was flagged as an issue sometime long ago, but is still present in neo 0.4.1 package (either downloaded manually from here https://pypi.python.org/pypi/neo or by using pip3)

**Comment by samuelgarcia** [comment]
Hi,
which version of neo do you use ?
I think this is already fixed in the master branch.
Could you try to install from git ?

Best,

Sam
