### ISSUE TITLE
Scipy / quantities not a dependency

### ISSUE THREAD

**Issue by wvangeit** [NeuralEnsemble/python-neo#307]
Is there a reason why the scipy, quantities and numpy modules are not a dependency of neo in the setup.py ?

They are used in e.g.
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/neomatlabio.py

Because of this I had to make them a dependency of eFEL, https://github.com/BlueBrain/eFEL (which now uses neo). Ideally I would like to defer these dependencies to the first package that needs it.

Thanks.

**Comment by apdavison** [comment]
`numpy` and `quantities` _are_ declared in setup.py

`scipy` is not declared as it is optional: it is only needed for certain IO modules.

**Comment by wvangeit** [comment]
Oops, yes sorry, I missed that, didn't see the declaration on the lines above.
But so I guess scipy will not be added as a dependency ?

**Comment by apdavison** [comment]
That's right, scipy won't be added as a required dependency since it is not needed for most Neo users.

However, we could declare scipy as an "extra" (http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) - would that be helpful?

**Comment by wvangeit** [comment]
Yeah, that sounds like a good idea indeed.
Maybe I will also add neo as an extra to eFEL in the same way.

**Comment by wvangeit** [comment]
Ok, latest version of eFEL now has neo as an 'extras' dependency.

**Comment by apdavison** [comment]
I've just opened a pull request to declare extras for Neo: https://github.com/NeuralEnsemble/python-neo/pull/319
