### ISSUE TITLE
ChannelIndex __init__() and related documentation

### ISSUE THREAD

**Issue by pietromarchesi** [NeuralEnsemble/python-neo#309]
I am confused by the [documentation](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/core/channelindex.py) of ChannelIndex. In particular, under 'Usage 2', it suggests that the class can be initialized with the argument `channel_indexes`, whereas that seems to have been changed to `channel_ids`. In addition, even correcting the name, you still have to pass a `index` argument (the current version throws a TypeError), and it's not clear which argument one should use when grouping channels (whether `channel_ids` or `index`). 

On a perfectionist note, `from quantities import mV` should be added to the example as well.

**Comment by schmitts** [comment]
I've also trouble understanding the correct usage of ChannelIndex. I want to link AnalogSignals with Units. In the tests I see channel_indexes used as an attribute: https://github.com/NeuralEnsemble/python-neo/blob/master/neo/test/coretest/test_segment.py#L723 - How does this relate?

**Comment by apdavison** [comment]
@pietromarchesi  This is a typo. It should be `index`, not `channel_index`. I've updated the documentation in the master branch.

The `index` argument indicates which channels in the AnalogSignal are being grouped. The `channel_ids` and `channel_name` arguments allow you to assign integer and string identifiers (respectively) to the channels.

Is this now clear? Can you suggest where the documentation could be improved?

**Comment by pietromarchesi** [comment]
@apdavison Thank you for your reply, I saw the updated documentation and it is much clearer. A thing that could be shown in the documentation is that to ensure that you have a bidirectional relation between unit and channel you need to do both `chx.units.append(unit)` and `unit.channel_index = chx`, as you show in your example above. 

It is also not clear to me how you would allow for a unit to have multiple parent channels (think of a unit recorded from one of multiple tetrodes on a bundle, where you have one channel for the whole bundle but also separate channels for each tetrode). In fact, a unit seems to only have the attribute `channel_index`, and not `channel_indexes`.

**Comment by apdavison** [comment]
A `ChannelIndex` object contains an array, so that it can be used to link a unit to multiple channels. This does require that all the signals are contained in a single (multichannel) `AnalogSignal`. Does the latter condition not hold for your use case?

**Comment by pietromarchesi** [comment]
@apdavison Do you mean the 'index' attribute? In any case, it is clear to me that you can have two `ChannelIndex` objects which contain the same unit, but when you assign channels to a unit with `unit.channel_index = chx` it's not clear how you would extend to multiple channels. 

My use case is as follows: I have spike trains for a number of cells. These were recorded from 4 bundles, each with 8 tetrodes. I would like channels to group the bundles and channels to group the tetrodes, whereby a unit belongs to both a tetrode channel and a bundle channel. 

The rationale is that for some analysis you want to quickly group spike trains by bundle (each bundle corresponds to a different recording area) and in other cases you need to make a finer distinction between tetrodes. The tetrode information could be relegated to the annotations but that feels like a suboptimal solution, and ends up filling your code with list comprehensions. Do you have any suggestions?

**Comment by pietromarchesi** [comment]
@apdavison Hi Andrew, just a polite reminder of whether you can recommend a strategy for the use case described above. Cheers

**Comment by JuliaSprenger** [comment]
@apdavison @pietromarchesi I would also be interested in the solution of this problem, did you find one in the meantime? I guess you can always access the spiketrains coming from the level of the channel_indexes and group them in this way, but for the opposite direction I also don't see an obvious solution except for annotations.

**Comment by apdavison** [comment]
Sorry, I haven't had time to think about this. I don't understand @pietromarchesi 's usecase. Do I understand that you have 128 recording channels, (4 bundles, each with 8 tetrodes, each of which presumably has 4 recording points)? The signals should then have shape (n, 128) (for n sample times)?
A unit may be detected on one or more of these channels.

When you say "one channel for the whole bundle but also separate channels for each tetrode", does that mean that there is a signal which is the sum of all currents recorded in a given bundle?

**Comment by JuliaSprenger** [comment]
Let's say there are 128 electrode contacts, which then corresponds to the shape of the AnalogSignal (n,128). Now, after spike extraction, there for each tetrode there are multiple units, let's say 2. In total this makes 64 Units, each linked to one of the 32 ChannelIndex Objects collecting the Units of a tetrode. However, it would also make sense to introduce one ChannelIndex Object per tetrode bundle consisting of 8 tetrodes.
A Unit Object however can only link to a single ChannelIndex object and not both ChannelIndex objects, even though it might be useful to access both the bundle information as well as the tetrode information given by the corresponding ChannelIndex.
@pietromarchesi Please correct if I understood something wrong.

**Comment by apdavison** [comment]
The idea of a ChannelIndex is that the `index` attribute lets you select the relevant channels from the `AnalogSignal` by slicing, e.g. `signals_unit0 = signals_all[:, channel_index_unit0.index]`

With 64 Units, the most general case is that you would have 64 ChannelIndexes. I think you can only have a ChannelIndex for a tetrode or for a bundle if you also decompose the (n, 128) AnalogSignal into one (n, 8) AnalogSignal per tetrode and one (n, 32) AnalogSignal per bundle, and you would then have duplication of data.

Anyway, it seems that the current ChannelIndex does not meet the needs of @pietromarchesi 's use case. We need to figure out if we need a new class (perhaps revisit the idea of "collections", as in #138) or if we just need more helper functions.

**Comment by pietromarchesi** [comment]
@JuliaSprenger That is exactly what I meant. @apdavison Depending on the type of analysis, it might suffice to grab all the units from the same bundle, or you might need to be more specific and select them based on the tetrode. It would be nice to be able to do 
```
unit.channel_indexes = [bundle_channel, tetrode_channel]
```
so that later you could easily access both levels. For now the best solution I could come up with is to leave the tetrode information in the unit annotations, and write my own helper functions to select the units. Thanks a lot for the feedback in any case!

**Comment by samuelgarcia** [comment]
Hi all,
For me this is clear that a Unit have only one ChannelIndex.
So in your case, if I anderstand correctly, you have some Units roughtly detect with 32 channels and some Units finely detected with 4 channel (tetrodes).

You need many  (1+4+32) ChannelIndex to cover all cases:
```
all_ch = ChannelIndex(index=np.arrange(0,128), name='All channel')

bundle0 = ChannelIndex(index=np.arrange(0,32), name='Bundle0')
...
bundle3 = ChannelIndex(index=np.arrange(96,128), name='Bundle3')

bundle0_tetrode0 = ChannelIndex(index=np.arrange(0,4), name='Bundle0_tetrode0')
bundle0_tetrode1 = ChannelIndex(index=np.arrange(4,8), name='Bundle0_tetrode0')
...
bundle1_tetrode0 = ChannelIndex(index=np.arrange(32,36), name='Bundle1_tetrode0')
...
bundle3_tetrode7 = ChannelIndex(index=np.arrange(124,128), name='Bundle3_tetrode7')

```

And you associate a Unit depending how it have been detected:

```
# detected with all the bundle (32ch)
unitA.channel_index = bundle0
unitB.channel_index = bundle0
unitC.channel_index = bundle1

# detected using tetrode
unitD.channel_index = bundle0_tetrode1
unitE.channel_index = bundle3_tetrode7
unitF.channel_index = bundle0_tetrode0
```
Hoping, I am helping.

**Comment by pietromarchesi** [comment]
Hi @samuelgarcia, thanks for your input. I find your solution a bit convoluted to be honest, both to set up and to use afterwards. Suppose for instance I want to select all units from bundle 0: would I have to go through all the channel indexes and find the ones with names whose beginning matches the string `bundle0`, and then get their units? Or is there a smarter way?

**Comment by apdavison** [comment]
Leaving this open as a reminder to revisit and hopefully simplify the ChannelIndex concept.
