### ISSUE TITLE
Modify objects in place

### ISSUE THREAD

**Issue by tristanstoeber** [NeuralEnsemble/python-neo#324]
Dear python-neo community,

is there a way to modify neo objects, without having to replace them.
Lets say I want to remove some spikes from a SpikeTrain object. When I try to modify the spike times, it says "Can't set attribute".
What is the recommended way?

Best,
Tristan

**Comment by samuelgarcia** [comment]
By design neo.SpikeTrain inherits pq.Quantity (and so numpy.ndarray).

So, it is like in numpy : you cannot extend/decrease the array itself (and its related memory). You need a new object that will point to the new memory mapping.

**Comment by tristanstoeber** [comment]
Cheers Samuel for your answer.
That makes totally sense.
So do you then recommend to change a spiketrain by replacing it with a modified copy with the command duplicate_with_new_data?

**Comment by apdavison** [comment]
@tristanstoeber yes, I think that using duplicate_with_new_data is a good approach.
