### ISSUE TITLE
Cannot write files

### ISSUE THREAD

**Issue by kzapfe** [NeuralEnsemble/python-neo#327]
Estimated Neo v0.5 Team:

First, I would like to congratulate you on this excelent open source alternative to many propietarie software programs. I have been using it here for helping some of the students at the CINVESTAV-IPN  in México. I am proponent of using Open/Libre Sofware whenever possible, but propietary software is much ingrained in the Pharmacobiology realm (I come from physics, so I am more exposed to such ideas than here).

We have been experimenting with it it succesfully to open experimental data files in abf2 and other formats without trouble, but, confusingly, we still don't understand how to use it to write our data into other files, and the examples in readthedocs are not very clear. 
[I have a jupyter notebook on github](https://github.com/kzapfe/AprendiendoComputoLibre/blob/master/Python/AprendiendoNeo_v05-02.ipynb)
where the errors are shown, but I can give you a more minimal example here.  

We open some data:

```
from neo import io
from neo import (Block, Segment, ChannelIndex,AnalogSignal)
nombre="../DatosIntraCelularesFelipe/C1_21_2_17/PP1_L06hz_C1_21_2_17.abf"
archivo=io.AxonIO(filename=nombre)
LosDatos=archivo.read_block(lazy=False, cascade=True)

```

We check its size:

```
LosDatos.size['segments']
```

Then we manipulate the data to estract subsegments of the signal:

```
def detectaestimulo(datos, umbral=100):
    "Funcion que da el primer estimulo que pasa de un umbral de un analogsignal"
    primer=np.where(datos>umbral)[0][0]
    primer=int(primer)
    return primer

def recortasegnal(datos, indice, desde=50, hasta=500):
    "Funcion que nos recorta una señal a partir de un indice"
    result=datos[indice-desde:indice+hasta]
    return result

def nuevobloque(bloqueviejo,umbral=100, desde=50,hasta=500):
    "funcion que a partir de un Bloque de neo crea otro recortado y alineado"
    result=Block()
    for j in bloqueviejo.segments:
        #Toma el primer canal (activo), de cada analogsignal y la recorta
        estimindex=detectaestimulo(j.analogsignals[0], umbral)
        cacho=recortasegnal(j.analogsignals[0],estimindex, desde, hasta)
        result.segments.append(cacho)
    return result

```
Applying the function gives a succesful result:

```
bloquealineado=nuevobloque(LosDatos)
```

But then, I cannot save the new block "bloquealineado"....

```
guardar2=io.NixIO("guardadito.nix", 'rw')
guardar2.write_block(bloquealineado)
```
gives error.

```
from neo.io.neomatlabio import NeoMatlabIO
w = NeoMatlabIO(filename='myblock.mat')
w.write(bloquealineado)
```
Also gives error...

Could you give me some advise?

Karel Zapfe

**Comment by samuelgarcia** [comment]
I guess you have a problem in your object tree.

In nuevobloque:
  * **result** is a neo.Block
  * **cacho** is neo.AnalogSignal

So you can't do ```result.segments.append(cacho)```

You need a neo.Sement in between.

The tree is:
  * One Block have several Segment
  * One Segment have several AnalogSignal
