### ISSUE TITLE
Confusing logic in BlackrockIO

### ISSUE THREAD

**Issue by rohanshah** [NeuralEnsemble/python-neo#333]
Hi I have a question about some logic in the BlackrockIO reader that I'm a little confused by.

The piece of code in question is here: https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/blackrockio.py#L1466-L1480

reproduced here is:
```
def __transform_channels(self, channels, nsx_to_load):
        """
        Transforms the input argument channels to a list of integers.
        """
        all_channels = []
        nsx_to_load = self.__transform_nsx_to_load(nsx_to_load)
        if nsx_to_load is not None:
            for nsx_nb in nsx_to_load:
                all_channels.extend(
                    self.__nsx_ext_header[nsx_nb]['electrode_id'].astype(int))
        else:
            hdr = self.__nev_ext_header
            elec_id = self.__nev_ext_header[b'NEUEVWAV']['electrode_id']
            all_channels.extend(elec_id.astype(int))
        all_channels = np.unique(all_channels).tolist()
```

It seems that when `nsx_to_load` is specified such as with `"all"`, then only the analog signal channels are loaded, even if `channel` is set to `"all`".

It currently isn't possible to load both the spike and analog channels in this function.

So when I do `read_block(..., channels='all', nsx_to_load='all')` I can only read the analog signals and only when I do `read_block(..., channels='all', nsx_to_load='none')` can I get the spike channels.

It seems like the channels returned by `_transform_channels` should contain both the analog and spike channels when `channel='all'` and `nsx_to_load='all'`.

Is there a reason this isn't the case? If not, I can fix it. But it seems like the logic was specifically written that way so I wanted to double check that I wasn't missing something.

CC: @apdavison

**Comment by rohanshah** [comment]
PR to address this: https://github.com/NeuralEnsemble/python-neo/pull/334

**Comment by JuliaSprenger** [comment]
Hi rohanshah, I think the BlackrockIO was implemented this way since in the testing data the spiking channels are a subset of the the analogsignal channels. I guess this is not the case for your data. I will have a look at your PR.
