### ISSUE TITLE
New neo install fails due to Quanity install error

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#337]
We are no longer able to do fresh installs of neo  For example in Travis
This is because Quantity is now broken.

See:
https://github.com/python-quantities/python-quantities/issues/129

**Comment by Christian-B** [comment]
Doing
pip install --upgrade git+git://github.com/python-quantities/python-quantities.git@master
gets around this issue but is ugly.

**Comment by apdavison** [comment]
Fixed in quantities 0.12.0

**Comment by samuelgarcia** [comment]
Yeah!!! Thank you.
