### ISSUE TITLE
AttributeError: 'BlackrockIO' object has no attribute '_BlackrockIO__nev_ext_header'

### ISSUE THREAD

**Issue by JohnV7** [NeuralEnsemble/python-neo#338]
Hi all,
when trying to import certain BlackRock files I get this error message:

> AttributeError: 'BlackrockIO' object has no attribute '_BlackrockIO__nev_ext_header'

The same code works for other files though:
`session = neo.io.BlackrockIO(filename=fname)
seg = session.read_segment(n_start=0*ms,n_stop=10*ms,channels=1,units='all')`

I also have problems to import continuous waveforms. I only can get spiketimes and spike-waveforms.
Are there any example scripts for blackrock data available?

neo: 0.5.1
python: 2.7.12
ubuntu: 16.04

Thanks,
John

**Comment by caseus-viridis** [comment]
Same problem here.

**Comment by cboulay** [comment]
Try removing the '.nev' from your filename.

**Comment by JuliaSprenger** [comment]
Did you solve the problem? I think this error is thrown when no blackrock files could be found, so removing the '.nev' extention could actually resolve the error in your case. There is a PR dealing with this #367.

**Comment by samuelgarcia** [comment]
I think this is resolved
