### ISSUE TITLE
NeoMatlabIO.write_block does not write channel indexes

### ISSUE THREAD

**Issue by pietromarchesi** [NeuralEnsemble/python-neo#348]
I am wondering why the Matlab IO module only provides supports for writing the segments within a block, but does not write the channel indexes of the block. The `NeoMatlabIO.write_block` method in fact only iterates through the segments, and ignores the channel indexes. Is there a reason for this, or is it just not yet implemented?

**Comment by samuelgarcia** [comment]
ChannelIndex is not in NeoMatlabIO.supported_objects.
And yes, in the code, IO do not deal with ChannelIndex.

I guess the main reason is leasiness...

**Comment by pietromarchesi** [comment]
Fair enough. Is it going to be supported in the future or not necessarily? And how difficult do you think it would be to implement it? Given that so much neuroscience still (sadly, I know) happens in Matlab, it would be quite important to have a full bridge with Python. I could consider submitting a PR at some point.

**Comment by samuelgarcia** [comment]
My speculative guess is : the use of the IO is very mariginal. So if you want to invest time in neo maybe this IO is not the top priority. Nevertheless feel free to do a PR.

**Comment by pietromarchesi** [comment]
Really? I would have thought the IOs to be quite important, especially if Neo is to be used for publishing data. In particular, my lab is split between Python and Matlab, so a good IO is actually top priority for use with regards to the adoption of Neo.

**Comment by samuelgarcia** [comment]
OK.
So, my speculative guess is maybe wrong, sorry.

Maybe for publishing data nix would a better choice (using nix-mx from matlab).

**Comment by mdenker** [comment]
I think the main difficulty is the way that the current matlabIO transforms the Neo object hierarchy (which is actually a very complicated "non-feedforward" hierarchy) into a Matlab struct -- which is a strictly top-down structure. In other words, a Matlab struct is per se not flexible enough to represent the Neo data model. For example: where in the struct would you put the AnalogSignal and/or SpikeTrain data objects, as children of the Segment or of the Channelindex? 

Therefore, I think it is very non-trivial to include Channelindexes (and Units, for that matter!). The only solutions I see are:

* Create ChannelIndex/Unit objects in the matlab struct, but do not link them to the data objects (Spiketrains/AnalogSignals/..). That's probably very easy to implement, but not so satisfying.
* Create ChannelIndex/Unit objects in the matlab struct, and use an ID of some kind to link them to the data objects (Spiketrains/AnalogSignals/..). This is comparatively easy to implement, is at least complete, but not really nice either.
* Come up with an entirely new structure for the Matlab representation of the Neo object. This would however, essentially boil down to a "Neo for Matlab" project, which I assume is quite a major undertaking.

**Comment by pietromarchesi** [comment]
@mdenker Thanks for the clarification, Micheal. I think it in principle it would be a good idea to at least have the channel index and unit information in there _somehow_, even in a much less elegant way, to preserve the integrity of the data set. 

On a side note, this should be mentioned explicitly in the docs, don't you think? When I read the docs a while back it sounded like you could expect an almost seamless conversion of the Neo model to a Matlab representation (admittedly, I did not think too hard about how exactly the hierarchy was going to be converted), whereas you actually end up losing significant information along the way, and you only find out by going to the source code of the IO. The `write_block` function could also print a warning if called on a block that contains units and channel indexes.

**Comment by mdenker** [comment]
Yes, I'd also hope for a better way to get Neo data into matlab. There are several other problems with the matlab IO, e.g., annotations are not transferred, and the file size of the mat files (as supported by scipy.savemat) is limited so that larger data cannot be stored, etc. 

For that reason I would tend to agree with Samuel that one should seriously consider whether it's simpler to use nix as a tunnel between python and matlab, rather than .mat files. Nonetheless, the matlab IO should definitely fix those issues you raised so that it is a "minimal" export of *all* information. 

Btw, I actually also have a number of small changes to the IO to fix the missing annotations in the mat file, I hope I can manage to make this a PR soon.

**Comment by pietromarchesi** [comment]
Do you plan to include the export of all information in your PR, or will that be left for future work?

**Comment by zm711** [comment]
@apdavison recently reworked how neomatlabio traversed through Neo objects and coupled with the reworking of much of the neo object hierarchy I'm going to close this.
