### ISSUE TITLE
"List of implemented formats" section in docs is empty

### ISSUE THREAD

**Issue by mgr0dzicki** [NeuralEnsemble/python-neo#358]
"List of implemented formats" section on Neo IO documentation page on readthedocs.org (latest version) is empty: [http://neo.readthedocs.io/en/latest/io.html#list-of-implemented-formats](http://neo.readthedocs.io/en/latest/io.html#list-of-implemented-formats).

**Comment by apdavison** [comment]
This seems to have fixed itself!
