### ISSUE TITLE
t_start/t_stop in read_segment(...) for some IO (or t_starts/t_stops for read_block(...))

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#374]
In, some IOs like BlackRockIO and NeuralynxIO, 2 kargs have been freely added for ```BlackRockIO.read_segment()```:
  * t_start = a time (quantities)
  * t_stop = a time (quantities)

The behavior is that all object inside this segment are clipped to this 2 values.
This is very usefull (for computer's memory and the user's nerve ).

With the same idea 2 kargs have been added for ```BlackRockIO.read_block()```:
  * t_starts = [...] a list of times (quantities)
  * t_stops = [...] a list of times (quantities)

The behavior is that instead returning the real number of segments inside the file ```read_block()``` return some artificial Segments that are bounded by these two list.

This is very usefull too.

It would be great to have this at the neo.io API level. It would means that all IO could have this behavior and would raise an error when requested by user in case it is not implemented. This would not break compatibilities.

With the new neo.rawio in construction this would be very easy: only some lines of code inside ```BaseFromRaw``` would be necessary.

For **read_segment**, my suggestion would be to change **t_start/t_stop** by something else to avoid confusion maybe something like a tupple **clip_time=(123*pq.s,  125*pq.s)** or **time_slice=(123*pq.s,  125*pq.s)**.

For **read_block**, my suggestion would be to add a specific function for that because having list artificial segment returned **read_block(...)** will lead to lot of confusion for new user. I really would prefer something like ```MyIO.read_split_into_segment(...)``` but with shorter name.

@mdenker @JuliaSprenger : what do you think,  since you are primary authors of that concept in neo.io ?

Best

**Comment by JuliaSprenger** [comment]
Thanks for suggesting this, I think it is a good idea to make the t_start/t_stop mechanism also available on the neo.io API level.
I agree that it would be better to use tuples for defining individual start-stop time ranges.

For **read_segment**, I would be happy with any of your suggested keyword names, however using `time_slice` would be more consistent with the naming of `time_slice(...)` method of neo data objects.
For **read_block**, I would suggest to use then **time_slices** as keyword, expecting a list of tuples of the type used in **read_segment(...)**. Why do you think returning a block with multiple segments attached will lead to a lot of confusion for new users? This should be rather intuitive with the notion of a segment containing data of a certain time range.

Maybe @lzehl has an opinion on this?

**Comment by samuelgarcia** [comment]
**read_segment(..., time_slice=(XX, YY))** have been implemented in PR #355.

If someone can have a look...

**read_block(time_slices=[(), (), ()])** is not done yet.

This is more difficult because we need to alocate each slice to real correspondign segment when there is already several segments.

**Comment by samuelgarcia** [comment]
read_block(time_slices=[(), (), ()]) is now also done in PR #355

**Comment by samuelgarcia** [comment]
Close by #355
