### ISSUE TITLE
Remove support for version of python<2.7

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#375]
We have lot of line in neo code to support old version of python like these:

```
from neo.io.tools import iteritems
```

```
try:
    import unittest2 as unittest
except ImportError:
    import unittest
```

I think we could clean our code by removing support for python 2.6 and before.
We could have so better code to support both 2.7 and 3.x serie.

I guess that very people are still using python 2.6.

**Comment by apdavison** [comment]
👍 NumPy no longer supports 2.6 anyway.

(`iteritems` is still probably needed for 2.7 and 3.x, but `unittest2` can be dropped)

**Comment by samuelgarcia** [comment]
dict.items() is valid on python2.7, no ?

I will do changes.

**Comment by apdavison** [comment]
`dict.items()` returns a list for Python 2.x but an iterator for Python 3.x. You need `dict.iteritems()` to get an iterator for Python 2.x

**Comment by samuelgarcia** [comment]
Yes but this is very often used when reading header in situations with few overhead of creating a list:
```
for k, v in channel_info.items():
  do_something(k,v)
```

**Comment by apdavison** [comment]
Yes, if there is no particular need to have an iterator, we should just use `.items()`

**Comment by samuelgarcia** [comment]
I will start the big clean!!

**Comment by samuelgarcia** [comment]
And what about python 3.3 ?
Do we keep travis for that ?
