### ISSUE TITLE
Implemented a generic cache system for neo.rawio

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#376]
For some IOs (and RawIOs) sometimes it is very long to parse the header because the entire file
need to be parsed a first time. For instance to detect gaps. Or to get all possible unit_ids.

For NeuralynxIO, it is very long to detect internal gaps (and so new segments).
For so there is an implementation of its own cache sytem to store theses gaps indexes.

Many rawIO are concern by this slow parse_header() (Plexon, Tdt, Spike2...)

It should be great to have an internal cache for all RawIO that need it.

Some open questions:
   * with joblib ?
   * which format ? (pickle.dump, loblib.dump)
   * which hash ? filename+file datetime, full hash ?
   * where ? (/tmp/neo_cache, near by the file, /home/user/neo_cache, all of theses ?)

**Comment by JuliaSprenger** [comment]
For the NeuralynxIO we implemented multiple hashes, however only the filename + file datetime has a reasonable runtime. Loading the complete file for a full hash is definitely not a practical solution for real data files, however we didn't know about joblib, so might speed things up.
Also,storing the cache near by the file might not always be possible since data files might be on read-only partitions.

**Comment by samuelgarcia** [comment]
The #355 implement a small cache system based on joblib.

The hash system is very simple = (filename+datetime) in md5.

NeuralynxRawIO is using it to cache 'gap_indexes' because it take long time to compute them.

Could someone have a look ?

```python

#explicit path
reader = NeuralynxRawIO(dirname='mydata', use_cahe=True, cahe_path='/explicit/path/location')

#explicit somewhere hidden in home
reader = NeuralynxRawIO(dirname='mydata', use_cahe=True, cahe_path='home')

#nearby the file or dir
reader = NeuralynxRawIO(dirname='mydata', use_cahe=True, cahe_path='same_as_resource')
```

**Comment by samuelgarcia** [comment]
Done in 

BaseRawIO.setup_cache/add_in_cache/dump_cache with joblib.dump.

See NeuralynxRawIO that use cache for "gap_indexes".
