### ISSUE TITLE
Cutting Blocks/Segments by Epoch

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/python-neo#387]
as discussed in Lausanne, details to follow

**Comment by JuliaSprenger** [comment]
some example code exists already here: https://web.gin.g-node.org/INT/multielectrode_grasp/src/master/code/neo_utils.py

**Comment by samuelgarcia** [comment]
Do we want this for 0.8 ?

**Comment by samuelgarcia** [comment]
Already impleemented. If not please re-open.
