### ISSUE TITLE
Advanced filter functionality

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/python-neo#391]
as discussed in Lausanne, details to follow
--  Better syntax to specify complex search queries
-- Output of search

**Comment by JuliaSprenger** [comment]
- write filter functions, which are based on lists of neo objects rather than as function of specific neo objects (multiple filters can be applied sequentially)
- filters should be able to filter based on annotations (eg. return only objects, which have a specific item in a list of an annotation)
