### ISSUE TITLE
Multiy diminesnional slice returning wrong shaped array

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#407]
Example code:
```python
import numpy as np
from quantities import Hz
from neo import AnalogSignal as AnalogSignal

n = np.array([[0.1, 0.1, 0.1, 0.1],
    [-2.0, -2.0, -2.0, -4.0],
    [0.1, 0.1, 0.1, 0.1],
    [-0.1, -0.1, -0.1, -0.1],
    [-0.1, -0.1, -0.1, -0.1],
    [-3.0, -3.0, -3.0, -3.0],
    [0.1, 0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1, 0.1]])

a = AnalogSignal(n, sampling_rate=1000*Hz, units='V')

print n
print n[1, 3]
print n.shape
print n[:, 0]

print a
print a[1, 3]
print a.shape
print a[:, 0]

```

The slice [:, 0] on the numpy array returns 
```[ 0.1 -2.   0.1 -0.1 -0.1 -3.   0.1  0.1]```

While the AnalogSignal returns
```
[[ 0.1]
 [-2. ]
 [ 0.1]
 [-0.1]
 [-0.1]
 [-3. ]
 [ 0.1]
 [ 0.1]] V
```
===
neo 0.5.2
quantities 0.12.1
numpy 1.13.1

**Comment by apdavison** [comment]
This is the correct behaviour. AnalogSignal objects always have two dimensions.

**Comment by Christian-B** [comment]
This is extremly confusing to everyone and BREAKS the claim that AnalongSignal Arrays behave like NUMPY!

**Comment by Christian-B** [comment]
Please add a warning to http://neo.readthedocs.io/en/0.5.2/api_reference.html#neo.core.AnalogSignal that the slicing of an AnlogSignal Array returns different arrays to the slice of the similar shaped numpy array.

**Comment by apdavison** [comment]
The decision to make slicing work this way was not taken lightly. With the NumPy behaviour, all downstream code would have to treat signals with a single channel as a special case. Set against that is the consideration you raise that many people are already familiar with the NumPy behaviour (note that a signal can be converted into a real NumPy array very easily with `signal.magnitude`).

It was a tough call, but on balance we thought that ensuring signals are always 2D would produce the least confusion and require the least book-keeping code to be written by users.

I agree that this should be better documented, and I am happy to consider re-opening this discussion in a new ticket.

**Comment by Christian-B** [comment]
Thank you I can conform that print a.magnitude[:, 0] does produce the expected behavior.

Will open a seperate ticket on the documentation as this behavior is confusing and DIFFERENT to how neo 4.0 works for the exact same code.

**Comment by Christian-B** [comment]
Also who would you get the quantities object from a single channeled AnalogSignal?

**Comment by apdavison** [comment]
Neo 0.4 --> 0.5 was indeed a big change. This is why we had such a long alpha phase (Neo 0.5.0alpha1 was released in September 2016), and why the PyNN version was bumped from 0.8 to 0.9.

`a.as_quantity()` gives a 2D quantity array. Perhaps we should change the behaviour to match that of `magnitude`
