### ISSUE TITLE
`spiketrain.times - <compatible time quantity>` raises Value error

### ISSUE THREAD

**Issue by dEvasEnApati** [NeuralEnsemble/python-neo#412]
I get a Value error as below with neo v0.5.0:

    >>> from neo import SpikeTrain
    >>> import quantities as qu
    >>> tr = SpikeTrain([3, 4, 5] * qu.s, t_stop=10, t_start=2.5)
    >>> tr.times - 1.5 * qu.s
    Traceback....
    ValueError: The first spike ([ 1.5  2.5  3.5] s) is before t_start (2.5 s)

From [the documentation](http://neo.readthedocs.io/en/0.5.0/api_reference.html#neo.core.SpikeTrain), spiketrain.times must return a quantities array. However, it returns a neo.spiketrain object which complicates things (as is being discussed [here](https://github.com/NeuralEnsemble/python-neo/issues/369)). I think this can be fixed by casting spiketrain to a quantities object when the attribute times is read. What do you think?

**Comment by lungsi** [comment]
This error also occurs with neov05.1 ( same as [elephant issue #116](https://github.com/NeuralEnsemble/elephant/issues/116) )

**Comment by samuelgarcia** [comment]
I agree that tr.times should be a quantities object.

**Comment by apdavison** [comment]
Fixed in #483
