### ISSUE TITLE
tdtrawio._get_signal_t_start returns same start time for all segments in test data

### ISSUE THREAD

**Issue by cboulay** [NeuralEnsemble/python-neo#415]
I'm using the aep_05 test data directory.
During _parse_header, there is a _global_t_start captured for each segment.
Then, `._sigs_t_start` is populated with a list of segment start times after subtracting the segment-specific _global_t_start. It is these values that are returned by `_get_signal_t_start`

Concretely: (outer index is seg_index, inner index is group_id).

```Python
{0: {0: 9.5367431640625e-07, 1: 9.5367431640625e-07, 2: 9.5367431640625e-07},
 1: {0: 9.5367431640625e-07, 1: 9.5367431640625e-07, 2: 9.5367431640625e-07},
 2: {0: 9.5367431640625e-07, 1: 9.5367431640625e-07, 2: 9.5367431640625e-07}}
```

For comparison, the Neuralynx test data file has the following in `._seg_t_starts`: `[8129.2206690000003, 8142.9306690000003, 8158.3796689999999, 8173.4726689999998]` and it subtracts from each of those a common `self.global_t_start` during `_get_signal_t_start`

**Comment by samuelgarcia** [comment]
I don't the issue.

To clarify:
  * **get_segment_t_start/t_stop** is limit of all object in a segment.
  * **get_signal_t_start** is the time of the first sample in second for analogsignals in one segment
  * neo do not impose anything about global time across segment. So you can have 0 for all segment_t_start or something else depending on the IO. So Neuralynx have some kind of global time but Tdt have not this.
  * For many IO segment_t_start==signal_t_start but there is not garanty, in Tdt it is diferent value because event can occurs before sigs.
  * I have kept the same logic as before IO by IO

**Comment by cboulay** [comment]
I have not used the old IO for Neuralynx or TDT. I happened to start using neo only a couple weeks before you submitted the PR for rawio, and rawio works a lot better for my application.

I'm sorry that in my original post of the issue I was mixing seg_t_starts and sigs_t_start. I am interested only in `get_signal_t_start`. I was diving into the code and the different implementations use either seg_t_starts or sigs_t_start so that's why I have those in my post above, but that is confusing the issue.

Perhaps this is clearer:

```Python
import os
from neo.rawio.neuralynxrawio import NeuralynxRawIO
from neo.rawio.tdtrawio import TdtRawIO
data_folder = os.path.join('/', 'media', 'chad', 'WORK', 'Tools', 'TestData')
test_files = [
    (os.path.join(data_folder, 'neuralynx', 'Cheetah_v5.7.4'), NeuralynxRawIO),
    (os.path.join(data_folder, 'tdt', 'aep_05'), TdtRawIO)
]
for test_ix, test_tuple in enumerate(test_files):
    neo_io = test_tuple[1](dirname=test_tuple[0])
    neo_io.parse_header()
    n_segs = neo_io.segment_count(0)
    print([neo_io.get_signal_t_start(block_index=0, channel_indexes=[0], seg_index=seg_ix) for seg_ix in range(n_segs)])

[1.5999999959603883e-05, 13.710015999999996, 29.15901599999961, 44.252015999999458]
[9.5367431640625e-07, 9.5367431640625e-07, 9.5367431640625e-07]
```

The different IOs return conceptually different things. The NeuralynxRawIO returns the time since some common global (this is useful and intuitive). The TdtRawIO returns a time that is essentially useless.

>neo do not impose anything about global time across segment. So you can have 0 for all segment_t_start or something else depending on the IO. So Neuralynx have some kind of global time but Tdt have not this.

To help improve the usefulness of the API, shouldn't this be the same no matter the IO?

So I guess I propose that [this line](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/tdtrawio.py#L168) be changed:

```Python
# t_start = data_index['timestamp'][0] - self._global_t_start[seg_index]
t_start = data_index['timestamp'][0] - self._global_t_start[0]
```

**Comment by samuelgarcia** [comment]
The fact is that for some IO there is no global time at all so this behavior cannot be for all IOs.


> t_start = data_index['timestamp'][0] - self._global_t_start[0]

This can be done for TDT. Are you sure that it will lead to a global time ?


> The TdtRawIO returns a time that is essentially useless.

The time is not useless because it is need to align event/spike/signals on the same time basis inside a segment.

**Comment by cboulay** [comment]
If we simply use self._global_t_start[0] instead of the segment-specific global, then this should act as a de facto global, shouldn't it? It looks like this should work for events, spiketrains, and signals. I'm still fairly new to neo so it's highly likely that I'm missing some important detail.

[_get_signal_t_start returns a member variable that is earlier set to](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/tdtrawio.py#L168): `t_start = data_index['timestamp'][0] - self._global_t_start[seg_index]`

[_get_spike_timestamps](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/tdtrawio.py#L360): `timestamps -= self._global_t_start[seg_index]`

[_get_event_timestamps](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/tdtrawio.py#L405): `timestamps -= self._global_t_start[seg_index]`

**Comment by cboulay** [comment]
@samuelgarcia , do you think subtracting self._global_t_start[0] instead of self._global_t_start[seg_index] makes sense? Would you like me to make a PR?

**Comment by samuelgarcia** [comment]
If you have a dataset where we are sur that make there is some kind of global time in TDT yes, this make sens. 

Otherwise, I would prefer something with no ambiguity. time is reset for each segment.

**Comment by cboulay** [comment]
I've contacted TDT and asked for their input.

**Comment by cboulay** [comment]
@samuelgarcia , I received a reply from Mark Hanus at TDT. 

To summarize, the tsq file has separate start and stop global timestamps relative to 1970. The start timestamp indicates the time that the Record button was pressed. Is this what you mean?

He provided some Matlab code. I would like to forward you the e-mail. Can you please contact me? My e-mail address is on my profile page.

**Comment by cboulay** [comment]
After looking at his Matlab code while interacting with the test data through tdtrawio, I think that maybe Mark Hanus misunderstood what tdtrawio was doing and tdtrawio is in fact getting the global (since 1970) timestamps correctly. He suggested we look for the tsq rows that have (what tdtrawio calls) 'store_name' == 01 for starttime and == 02 for stoptime, but tdtrawio is currently checking 'code_type' for `0x8801`, and the only 2 rows that it matches are the same rows as above. So this should be fine.

From reading code comments a little more, I think I'm starting to understand what you meant above. `_get_signal_t_start` is often equal to `_segment_t_start` except in cases where the actual signal recording might start some time after the segment's start time. Either way, they should still be relative to the same clock.

In neuralynxrawio, this clock is `self.global_t_start`, which is the same for all segments in a block. For tdtrawio, the clock is 'reset' for every segment, so each segment starts at t=0. I guess this was done because the segments are loaded in whichever order `os.listdir` returns, and not necessarily in chronological order. Instead, we can inspect each segment's tsq file and get its start time, which is a timestamp since 1970, and then re-order the segments chronologically before doing the full import. Then we can use the 0'th segment's timestamp as a common self.global_t_start. How does that sound?

**Comment by samuelgarcia** [comment]
This sound very good. Thank you for this investigation on the filr format.

I would be very happy to review your PR.
