### ISSUE TITLE
neuroexplorerrawio missing internal_unit_ids

### ISSUE THREAD

**Issue by cboulay** [NeuralEnsemble/python-neo#416]
All of the other rawIOs with spike data have the internal_unit_ids member variable and I've been relying on it.

Also, the unit-naming format is different from some of the other rawIOs. e.g., blackrockrawio uses `"ch{}#{}".format(channel_id, unit_id)`, but the 3 test .nex data files I have (2 from neo's repo + 1 from neuroexplorer.com) use e.g. `'Neuron05b'`. I guess that 05 is the channel number and a-d is the unit identifier, but I haven't verified this at all. But that third file also has a neuron named `'sig01i_wf'
`; I'm not sure what to do about that.

**Comment by samuelgarcia** [comment]
unit naming is not imposed by neo.io or neo.rawio API but try to render what is in the file with less transformation possible.
So a users can compare neo.rawio output and the real name they have in the software.

In neuroexplorerrawio, name come from the enity name and I guess this make sens. No ?

**Comment by cboulay** [comment]
Yeah, I agree that it makes sense to keep any intrinsic unit names.

But what about the internal_unit_ids member variable? From what you remember about the neuroexplorer data format, is there any way to know which channel a unit comes from? Maybe in `entity_header['WireNumber']`? I'll take a look tonight.

**Comment by cboulay** [comment]
Sorry I didn't comment after I tested. ['WireNumber'] didn't have anything useful. In the end, in the provided test data files, I couldn't figure out the relationship between channels and units. I don't have any real NeuroExplorer data files so I'm going to have to abandon this pursuit for now.

**Comment by samuelgarcia** [comment]
I think you should not rely on internal_unit_ids of some IO.

It is an internal trick, generally a list for getting internal (chan_id, unit_id) when having neo unit_index.
This is in case when multi unit by channel (and this is IO dependent) so the unit count is not the channel count.

For some format like neuroexplorer, internal the mapping one channel = one unit is clear so no need for that trick. In neuroexplorer channel is more an entity.
