### ISSUE TITLE
BlackRockIO file version 2.1 not loading

### ISSUE THREAD

**Issue by bjoern1001001** [NeuralEnsemble/python-neo#417]
Using the latest BlackRockIO, loading fails for file version 2.1, because in BlackrockRawIO '__read_nsx_data_variant_a' wants to call 'self.__nsx_databl_params' (line 754), which does not exist. I think it should be contained in the dictionary that is created in lines 180 ff.. In the old IO it was included there (see lines 289 ff.) and referenced a method named '__get_nsx_databl_param_variant_a' (lines 1323 ff.) which is also not implemented in BlackrockRawIO.

This is the error I get: 
File ".../blackrockrawio.py", line 754, in __read_nsx_data_variant_a
    self.__nsx_databl_param['2.1']('nb_data_points', nsx_nb),
AttributeError: 'BlackrockIO' object has no attribute '_BlackrockRawIO__nsx_databl_param'

**Comment by samuelgarcia** [comment]
Thanks again for testing all this.

Do you have a file 2.1 small enougth ?

**Comment by bjoern1001001** [comment]
This discussion is going on in pull request #435. The files for testing have been uploaded to g-node (https://portal.g-node.org/neo/blackrock/blackrock_2_1/).

**Comment by samuelgarcia** [comment]
Close by #435
