### ISSUE TITLE
Code sprint with MNE team for common IOs.

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#432]
Dear Neo user and developers,

As you may have noticed, the Neo master branch now has a new internal API called rawio. This is a low level API, which makes it possible to read some data files faster and in a more flexible way. It should also make it easier to add new Neo IO modules in future. This new API will be released in Neo 0.6, when it is mature enough.

The [MNE](https://github.com/mne-tools/mne-python) package for analysis and visualization of EEG, MEG, ECoG data supports some of the same file formats as Neo (Brainvision, Micromed, ...)
To avoid duplicated effort in maintaining file format readers, Alexandre Gramfort and Denis Engemann from the MNE team proposed a code sprint to develop shared code for this.
The main idea would be to have a rawio in common, on which both neo.io and mne.io could be based.

The MNE team invites us for a code sprint from 9th-11th January 2018 on the Saclay campus (45 min. from Paris). More details about the venue soon...
Anyone interested in helping out with Neo, MNE, or both, or in using a shared rawio in their own Python tools, is invited to participate in this code sprint.
Let us know by replying to this post, or by contacting us individually.

If you are interested but won't be able to physically attend the code sprint, you can also open issues on GitHub to enrich the discussions.

Best regards,

Andrew and Samuel

**Comment by achilleas-k** [comment]
I wont be able to attend but would like to contribute, or at least follow it remotely. Will it be possible to contribute beyond opening issues? I understand splitting discussions between online and offline is hard and even counterproductive; there's a reason these things happen in person. Just letting you know in case more people are joining remotely and we can make an effort to coordinate online on some aspects.

**Comment by samuelgarcia** [comment]
Hi Achileas.
Maybe a way to contribute would be to port the actual neo.io.NixIO to neo.rawio.NexRawI at least for reading (rawio do not support write).

Doing this you would  discover the rawio API by coding an this nixrawio, so you you could give a feedback before the meeting and make a first list a point that need to to be discuss.

For online vs offline discussion, maybe we can make a list  at each end the end of day here on this issue that everyone can give feedback for the next day.

Best,

Samuel

**Comment by achilleas-k** [comment]
Good idea(s). I'll have a look at the API and will watch for news. Thanks.

**Comment by samuelgarcia** [comment]
Great.

You could start with:
  * doc/source/rawio.rst
  * neo/rawio/examplerawio.py
  * neo/rawio/baserawio.py

And then to:
  * neo/io/exampleio.py

And if you are conrageaous:
  * neo/io/basefromrawio.py

rawio test are inside rawio/tests.

Good luck.

I can help.

Samuel
