### ISSUE TITLE
ChannelIndex.index inconsistent

### ISSUE THREAD

**Issue by bjoern1001001** [NeuralEnsemble/python-neo#443]
According to the neo documentation (http://neo.readthedocs.io/en/latest/api_reference.html#neo.core.ChannelIndex), ChannelIndex.index should point to the corresponding traces of AnalogSignals that are connected to the ChannelIndex. For example, if a ChannelIndex has an AnalogSignal with 5 traces, index should be range(5). 
For multiple AnalogSignals with possibly multiple traces each, the best implementation should be discussed. Our suggestion would be to make it a list of lists, with each sublist containing the indices for one AnalogSignal. For example if the ChannelIndex has an AnalogSignal with 4 traces and one with 2 traces, ChannelIndex.index would be [[0, 1, 2, 3], [0, 1]].
However, this would make it more complicated if there is only a single AnalogSignal per ChannelIndex because the lists would have to be nested in spite of that.
I would be happy about alternative suggestions/solutions/ideas.

**Comment by apdavison** [comment]
The idea was that 1 ChannelIndex <--> 1 AnalogSignal, so the question of a ChannelIndex with multiple AnalogSignals does not arise.

Please can you explain the use case?

**Comment by JuliaSprenger** [comment]
I was not aware that the idea of ChannelIndexes was a one to one mapping to AnalogsSignals. This implies that there is no mechanism to group AnalogSignals across  Segments. However, this seems to be one of the first cases for which I would use a ChannelIndex, eg. to group Signals recorded on the same physical contact.
Also the current version of the ChannelIndex documentation is showing 3 use cases (https://github.com/NeuralEnsemble/python-neo/blob/master/neo/core/channelindex.py line 23ff), the first one using ChannelIndexes to group AnalogSignals across Segments, for exactly the case described above.

**Comment by apdavison** [comment]
My apologies, I expressed that incorrectly. Yes, ChannelIndexes group AnalogSignals across Segments. In that case, however, my expectation is that each of these AnalogSignals will have the same channels.

**Comment by bjoern1001001** [comment]
The solution for this is part of the proposal to split ChannelIndex in issue #456, so the discussion should continue there and this issue can be closed.

**Comment by samuelgarcia** [comment]
Ok thanks.
