### ISSUE TITLE
Add a script to keep version numbers in sync

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#449]
The version number appears in multiple places: in `neo/version.py`, `setup.py`, `doc/conf.py` and `doc/install.rst`

To simplify making releases, we should make it easier to update all these files at the same time, e.g. with a script.

**Comment by samuelgarcia** [comment]
I take it.
 * neo/version.py and setup.py are already sync
 * doc/conf.py is easy with import neo in conf.py. Is that OK ?
 * Is it OK to have a generic ```unzip neo-X-Y-Y.zip``` in doc/install.rst that it is always OK ?

**Comment by apdavison** [comment]
For doc/install.rst, you can probably use the substituion `|version|`

see http://www.sphinx-doc.org/en/master/markup/inline.html#substitutions

**Comment by samuelgarcia** [comment]
Done in #479.
In code block it is no simple simple but with a bit of hacking in rst_epilog it is OK.
I hope this will build on readthedocs.

**Comment by apdavison** [comment]
Build failed on readthedocs: https://readthedocs.org/projects/neo/builds/6832928/

**Comment by apdavison** [comment]
Fixed in d9209fc52f27729e6550d6d4063ff33e819cb0dc
