### ISSUE TITLE
BUG/ENH: some readers cannot be deepcopied.  

### ISSUE THREAD

**Issue by dengemann** [NeuralEnsemble/python-neo#453]
This makes life difficult on the MNE side.

Try for example in Python 3:

```Python
from copy import deepcopy

reader = BrainVisionRawIO(filename='my_file')
reader.parse_header()
deepcopy(reader)
```

**Comment by samuelgarcia** [comment]
I close this. feel free to re open if needed.

**Comment by JuliaSprenger** [comment]
@samuelgarcia So you don't think that deepcopying of IOs will be possible with the current IO architecture?

**Comment by samuelgarcia** [comment]
I don't think it is a need anymore.
