### ISSUE TITLE
Proposal: Split ChannelIndex into View, Group and Multiannotations

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#456]
**Current State**
The current implementation of ChannelIndex is trying to provide a number of functionalities within the neo structure:
- providing information about individual traces of AnalogSignals like the channel id and the channel name (labelling)
- grouping a subset of traces within an Analogsignal via the index attribute (masking)
- linking between / grouping AnalogSignals (grouping)

_Problems_
However the implementation of all of these features in a single object lead to a number of inconsistencies and limitations (see also Issue #443). One of the limitation is, that if multiple AnalogSignals are attached to a ChannelIndex, they have to have the same number of traces. This does not allow to group AnalogSignals occurring within a single neo Segment. Another limitation is introduced by AnalogSignals only having a single parent ChannelIndex, which provides a general (global) channel ID and a general channel name. Additional / alternative channel numbering / naming is not possible this way.

**The Proposal**
The proposal is to split the different aspects of the ChannelIndex into different neo objects and features.

_Labelling_
A simple mechanism for providing channel ids and channel names is already proposed in Issue #390. Multiannotations (array-valued annotations) would allow each trace in the AnalogSignal to be labelled with a general channel ID as well as additional alternative ids using different keys of the multiannotaion dictionary. The actual keys to use are a matter of convention and up to discussion.

_Masking_
For selecting data (traces) of a data object we propose to implement a new neo object named 'View'. This object should have a single object of type AnalogSignal/IrregularSampledSignal as attribute and provide a mask for the data contained in the data object (eg. only selecting a subset of traces of the AnalogSignal/IrregularSampledSignal). It should also provide a method to actually return the corresponding slice of the linked object. For simplicity reasons the view object is linking to the data object, but not in the opposite direction. This simplifies the neo structure, but also introduces new limitations, which a more powerful implementation of the filter functionality should be able to overcome.

_Grouping_
Finally, the grouping aspect will be taken over by a new neo group object. This object should be able to link to multiple object of types AnalogSignal, IrregularSampledSignal, SpikeTrain and View. The group object can also take over the role of the neo Unit object, by only having SpikeTrains as children. Groups have a single neo Block as parent, but a neo Block can have multiple Groups attached.

Ideas / comments / feedback appreciated!

**Comment by samuelgarcia** [comment]
@JuliaSprenger : I think that we should put the miletones of this to 0.7 or 0.8 again because it imply a change in th object model. The 0.6 is more related to rawio and should be released soon (in february ??).
If we add this in 0.6 it will take mnay more times. No ?

**Comment by JuliaSprenger** [comment]
@samuelgarcia: Yes, I completely agree. It was just a misclick. Sorry for the confusion.

**Comment by JuliaSprenger** [comment]
Implemented in #817. :fireworks:
