### ISSUE TITLE
Hitting Spike2IO asserion on sampling_rate

### ISSUE THREAD

**Issue by matham** [NeuralEnsemble/python-neo#466]
I'm trying to import a spike2 smr file using `Spike2IO(filename=filename)` but am hitting an assertion:

```
Traceback (most recent call last):
  File "G:/Python/libs/Playground/src/playground2.py", line 3, in <module>
    reader = Spike2IO(filename=r'G:\Python\1-9-2018-mouse-left-odor mixture-10 trials.smr')
  File "E:\Python\Python35-x64\lib\site-packages\neo\io\spike2io.py", line 10, in __init__
    BaseFromRaw.__init__(self, filename)
  File "E:\Python\Python35-x64\lib\site-packages\neo\io\basefromrawio.py", line 71, in __init__
    self.parse_header()
  File "E:\Python\Python35-x64\lib\site-packages\neo\rawio\baserawio.py", line 155, in parse_header
    self._parse_header()
  File "E:\Python\Python35-x64\lib\site-packages\neo\rawio\spike2rawio.py", line 199, in _parse_header
    assert sampling_rate.size==1
AssertionError
```

So I printed the value of `sampling_rate` and it's `[ 1000.  2000. 10000.]`. Is it unable to use channels with different sampling rates?

**Comment by samuelgarcia** [comment]
Oh yeah. So it exists.
Could you send me the file to try something ?
rawio level support multi sample rate but needs some more code.
Do you have a small file (<10Mo) that could put on our testing suite and that would publicy availble ?

**Comment by matham** [comment]
Thanks for getting back. Here's the file: [multi_sampling.zip](https://github.com/NeuralEnsemble/python-neo/files/1639685/multi_sampling.zip).

**Comment by samuelgarcia** [comment]
I will try something to fix this. At least to have the buffer for each channel groups. (same sampling rate)

The main problem is that we can't garanty how channel with differents rate are align in time.

The actual code assume that al signal channel start at t_start=0.
We can assume that for the same clock but with differents clock this is not sure.

Maybe you should also contact ced to ask them how channels with differents sampling rate are align in time. Assuming that they are synchronize is not good.
Maybe the code is missing some timestamps information...

**Comment by matham** [comment]
I'm not sure what you mean by aligning. When Spike2 records data (e.g. when you tell it to write the data), it starts recording all channels at the same time, even those with different rates. Maybe it can be manipulated programmatically from spike2 scripts, but by default it seems to start all at the same time.

I also noticed that in the file we have like 10 trials, with data recording turned ON/OFF before/after every trial so that only the trial is recorded. But what is returned by neo is only the first trial worth of data.

**Comment by samuelgarcia** [comment]
Hi @matham,
s.
I have push a patch to solve this.

Could you test this PR #475 and see if signals/sampling_rate/shape correspond to what you have in your ced system ?

I have put you file at  https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data

In the file neo/tests/iotests/test_spike2io.py you can have the shape of each signal groups.
Do you have the same with other reader ?

**Comment by samuelgarcia** [comment]
About the multi trial, I was aware that spike2 was able to do multi segmetn inside the same smr file.
Is there some spec somewhere ?
The current Spike2IO only read one segment. It is hardcoded.

**Comment by matham** [comment]
Thanks for the fixes!

I checked the sampling rates and it seems to match the sampling configuration in Spike2.

But I'm not sure about the signal length, you seem to be by about a factor of 10 off: according to Spike2, the file contains 10 trials (segments) of about 10 seconds each. So there should be 10 segments of 10 seconds each (in the screenshot, the dark-green is the trials during which data is saved): 
![untitled](https://user-images.githubusercontent.com/1644286/35705862-b7a1d474-0771-11e8-9c30-10876b357edd.png)


But neo prints:

```
[Block with 1 segments, 11 channel_indexes
 annotations: {'system_id': 5}
 file_origin: 'G:\\Python\\1-9-2018-mouse-left-odor mixture-10 trials.smr'
 # segments (N=1)
 0: Segment with 3 analogsignals, 3 events, 8 spiketrains
    annotations: {'system_id': 5}
    # analogsignals (N=3)
    0: AnalogSignal with 1 channels of length 135812; units V; datatype float32 
       name: 'Channel bundle (Respirat) '
       sampling rate: 1000.0
       time: 0.0 to 135.812
    1: AnalogSignal with 4 channels of length 264846; units dimensionless; datatype float32 
       name: 'Channel bundle (,,,) '
       sampling rate: 2000.0
       time: 0.0 to 132.423
    2: AnalogSignal with 2 channels of length 1146180; units dimensionless; datatype float32 
       name: 'Channel bundle (,) '
       sampling rate: 10000.0
       time: 0.0 to 114.618]
```
I'm not sure where the 114+ seconds of data is coming from? Either neo reads the data for all the trials thinking it's one trial or something is going on.

What I'm currently doing is exporting the data from spike2 into matfiles (hdf5). In those it also only exports the first trial (see the h5 file attached), but the number of samples seem correct. E.g. channel 29, labeled `Respirat` in neo, has 14295 samples, or 14.3 secs of data (see the `values` attribute of that channel) in the h5 file. But in neo it reports channel 29 as having 135812 samples.

[1-9-2018-mouse-left-odor mixture-10 trials.zip](https://github.com/NeuralEnsemble/python-neo/files/1687401/1-9-2018-mouse-left-odor.mixture-10.trials.zip)

Regarding any spec, I'm not aware of any, but then again, I'm just using spike2 so I don't really know its internals. How did the person who wrote the original `spike2rawio.py` file get the file spec? Is there a document? If so I can see if it was updated. I tried searching for one but couldn't find it in the Spike2 installation folder.

**Comment by samuelgarcia** [comment]
Hi.
thank you for theses details.
This is very annoying because this means that the actual IO is wrong for non continuous datasets.

It should raise an error in your case and not give fake signals that concatenate all trials.
The information about trial must somewhere in the file.

I wrote spike2io lon time ago, spikerawio is just a port to the new API to be faster. As written in the doc of spikerawio.py the code was originallly based on sonpy and son library.

The internal specification must have change since.

How do you export to mat hdf5 file ? Is it with spike2 itself ? Or do you have some matlab code for this ?

Another source of error is the true sampling rate of spike2. My guess is that there is the wanted sampligng rate  (1kHz) and the real sampling rate by the device with online decimation.

With 10 segment of 10 second you should have 10000 sample for the first segment even in matlab files. This is not the case (14295). Here matlab and psike2io have the same signal length becasue 114+/10 s ~ 14s. The two possible reasons are: it is not 10.0s but 14.s or it is not 1kHz but 1.4kHz.


At least the multi sampling_rate is OK...

**Comment by samuelgarcia** [comment]
I inspect a bit the hdf5 you gave me.

The situation is worst : the t_start is not the same for all channels.
For each channel there is a time vector + value vector. The first value of times is the neo t_start.

If you inspect it, you see that it is not the same for all channels.

In short, the actual IO do not align correctly in time all channels.

We really need the true specification of the smr fiel format to have a reliable Spike2Io in neo.

**Comment by samuelgarcia** [comment]
I have opened your file with [ephyviewer](http://ephyviewer.readthedocs.io/en/latest/overview.html) in standalone mode and signal are clearly note aligned on event and spikes...

**Comment by samuelgarcia** [comment]
I think I have the solution.
But each channel will be independ at reading time even if they have the same samplign rate.

**Comment by matham** [comment]
I think the sampling rate is correct, it's just the different channels record data for different duration. E.g. following is screenshot from Spike2 of the first trial:
![untitled](https://user-images.githubusercontent.com/1644286/35744809-4a45f0f6-080f-11e8-9b91-f46d61af7835.png)
You can see that the top traces start earlier and record for about 14.5 secs while the bottom two traces start recording about 1 sec later and record for only 11.5 secs. So the h5 file shows signals of the correct length for each channel as the trial is not exactly 10 secs.

The h5 is generated from within the Spike2 interface. Looking in the spike2 help file, this is what it says about the son library:

```
Spike2 data is stored in CED SON files. This file format was originally designed around 1987 and has been much extended since. There have been 9 major version changes (so far). We have always tried to make sure that more modern versions of Spike2 will read older file versions. Unless you are interested in history, or you have an old version of Spike2 and cannot read a data file, you can stop reading this page now.

If you are interested in the technical details of the library, or need to interface to it, there is documentation and header files on the CED web site (follow links to Downloads and then Son library).

Version 1
The original SON filing system, in Pascal, supported waveform and Event data only.

Version 2
New Marker data type. Extra space was added to the file header for future expansion. The version 2 library was much faster dealing with large data files as it remembered the last access point for each file during reading.

Version 3
The FilterMarker function was added with this version and the meaning of the divide element of the channel record for waveform data was changed to prevent an apparent change of sampling rate if a waveform channel was added or deleted.

Version 4
The AdcMark data type was added, the use of FilterMarker was changed and the library now remembers the data block currently in the data buffer to avoid reading the disk when the required block is already in memory.

Version 5
The TextMark and RealMark data types and the MaxTime and ChanMaxTime functions were added. Versions were also written in C for both the IBM PC in DOS and under Windows and for the Macintosh. The version 5 libraries write version 3 and 4 files as appropriate to prevent unnecessary conflict between library versions.

In 1998, the C version of the library was extended to cope with read-only files by adding iMode to SONOpenOldFile and the SONCanWrite function was added. The return type and max argument of the SONWriteXXXXData routines were changed from WORD to long. Added lookup tables into the file to speed up data access in long files and to provide write buffering. Write buffering removes the need for FastWrite mode, allows peri-triggered sampling, optimises use of disk space and speeds up writing data to disk. The file commit mechanisms were improved.

Version 6
This version of the library is documented for C/C++ use only, with information on how it can be used as a DLL by other languages. The RealWave channel type is added, AdcMark channels are allowed to have multiple channels, waveform sample rates are set by lChanDvd and the previous v.adc.divide now sets the interleave for AdcMark data. We have added support for a file time and date stamp, a file basic time unit and support for an application identifier. Files will still be written to be compatible with versions 3, 4 or 5 if they do not use version 6 features. The API was maintained, but some argument types changed: TDataKind is an enumerated type and buffer sizes are long not WORD.

Version 7
You can choose to round the sizes of AdcMark and TextMark extended marker types up to a multiple of 4 bytes so that we can build the library on systems that insist on aligned data access. See the new SONExtMarkAlign() function.

Version 8
Altered storage of channel numbers so that we avoid the bit used to hold the initial state for a level channel, plus extended the maximum number of channels possible to 451. Extended the lookup table system so that the table for a channel starts small and grows up to the limit (larger than the fixed size used previously).

Version 9
Added support for big files (up to 512 GB), rewrote the internal lookup table system to improve speed and now saves the table as part of the file in Big file mode. Support for the Macintosh was removed. Linux support is added. In a version 9 file, all pointers to disk space that were previously byte pointers (but multiples of 512) are now used as block pointers. That is, a pointer value 10 means byte 5120 in the file. This allows us to increase the maximum file size by a factor of 512. There are changes to the file header to support a lookup table on disk and to channel headers to track the block counts. Some type changes to allow compiling with 64-bit code on Windows and Linux.

```

This seems to say that their website has the spec of the son file?

**Comment by matham** [comment]
The son library they are talking about seems to be a matson.exe file. After installing it seems to only contain dll files and a bunch of matlab wrappers for calling the dlls. There doesn't seem to be a son spec file there.

**Comment by samuelgarcia** [comment]
I have push a long patch to auto detect gaps on signals (rec pause) and so create new segment.
Theses segment limits are also applied on event and spike channels.

Could you try it ?

**Comment by matham** [comment]
Hey thanks a lot for the fixes! It seems to match the timestamps and data durations.

I did notice two issues though. The first is that it's missing the spiketrains, there should be 8 spike trains I believe in the data, and master has them.

The other one is that although the data is of the proper duration, when visualizing, the data is zero for the last few seconds. You can see it in the image attached.
![figure_1](https://user-images.githubusercontent.com/1644286/36234525-6c636fd4-11b9-11e8-8318-41d38dcb0a34.png)

**Comment by samuelgarcia** [comment]
That should be fixed.
Could you run another test please ?

**Comment by matham** [comment]
That indeed fixes the issue, everything is working perfectly now!

Thanks a ton

**Comment by matham** [comment]
Btw, how did you figure out the internal structure? Did you find some spec?

**Comment by samuelgarcia** [comment]
No, I don't really have spec.
I read again the internal crappy structure in the code and I figure out that each block data have a timestamp start/stop. 
So just looping over all blocks and detect gaps in between blocks that are bigger than the sampling interval made the trick. NeuralynxIO have simular code for detecting gaps because they also allow pause when recording but it is not written anywhere in the file.
Note that it means run through the whole fiel and the rocess is slow.

I guess that if I am lucky to meet you a day I have deserved a bier :)
