### ISSUE TITLE
py3 support KlustaKwikIO 

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#467]
KlustaKwikIO still no compatible with py3.
We must change do it.

**Comment by apdavison** [comment]
What are the differences between KlustaKwikIO and the more recent KwikIO? Do we need to keep both?

**Comment by apdavison** [comment]
So let's deprecate KlustaKwikIO in 0.6 and remove in 0.7, and not bother making it Py3 compatible unless someone asks for it.
