### ISSUE TITLE
Remove support for some IOs

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#469]
I think some IO should depreciated in neo 0.6 and remove in next version (0.7 or 0.8).

Here a list to be discussed:
  * asciispiketrainio.py
  * asciisignalio.py
  * blackrockio_v4.py
  * neuralynxio_v1.py
  * pynnio.py -> PyNNTextIO
  * ...

**Comment by JuliaSprenger** [comment]
I agree that the blackrockio_v4 and the neuralynxio_v1 can be marked as deprecated, but removal requires a working implementation of ProxyObjects and corresponding utility functions.

**Comment by apdavison** [comment]
Added deprecation warning for both PyNN IOs.

**Comment by apdavison** [comment]
I still come across various ascii-based ephys data files, so I think we should improve, rather than remove asciispiketrainio.py and asciisignalio.py

**Comment by samuelgarcia** [comment]
Close by #504
