### ISSUE TITLE
Remove time_slices args in BaseFromRaw.read_block(...)

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#473]
In rawio PR #335, time_slice wa added to read_segment() and time_slices to read_block() in BaseFromRaw. The idea was to mimic a behavior present in BlackrockIO and NeuralynxIO.

See #374 for more discussion.

**time_slice** in read_segment in OK.

**time_slices** in read_block() is ambiguous because they do not target specific segment. Some IOs do not support absolut time along segment, so assign a slice to a segment imply some magic code. Since this behavior will be useless will the upcoming new lazy mode and proxy object and since release 0.6 should be soon, I propose to remove this time_slices in read_block(..) before 0.6 and not waiting the proxy branch to be included.

@mdenker  @JuliaSprenger @apdavison @bjoern1001001: are you OK ? or do you prefer a release 0.6 with this behavior ?

**Comment by JuliaSprenger** [comment]
I am ok with removing time_slices in read_block before the 0.6 release as long as the blackrockio_v4 and old neuralynxio are kept until the same functionality is implemented an tested via the proxyobject mechanism.

**Comment by samuelgarcia** [comment]
Done in #474.

**Comment by samuelgarcia** [comment]
Close by #474
