### ISSUE TITLE
rawio example fails to run (latest code from master, python 3.6.0)

### ISSUE THREAD

**Issue by aizvorski** [NeuralEnsemble/python-neo#485]
I installed the latest neo from master:

```
$ git clone https://github.com/NeuralEnsemble/python-neo/
$ cd  python-neo
$ python setup.py install
```

Then, I tried to run the rawio example:

```
$ python examples/read_files_neo_rawio.py
Traceback (most recent call last):
  File "examples/read_files_neo_rawio.py", line 8, in <module>
    from neo.rawio import PlexonRawIO
ModuleNotFoundError: No module named 'neo.rawio'
```

I'm running python 3.6.0 from Anaconda 4.3 on Ubuntu 16.04.

I had installed neo from pypi before this, it did the same thing.

The non-raw io example works fine, as far as I can tell.

This by the way also stops ephysviewer from running.

P.S. Thanks for the awesome package; I have Axon files I need to open, I don't know how I'd do it without neo.

**Comment by samuelgarcia** [comment]
This sound strange.
There is maybe a double install conda+pip).
Could you do ```pip list``` or ```conda list``` and check that it is the good neo ?

**Comment by aizvorski** [comment]
I fixed it, `pip uninstall neo` and then it worked... huh.

This is what I got when it was still broken:

```
$ pip list | grep neo
neo (0.5.2)
$ conda list | grep neo
neo                       0.6.0                     <pip>
neo                       0.5.2                     <pip>
```

Now they both show 0.6.0 only.  I don't understand how this happened or why the fix worked, but glad it works now.

**Comment by samuelgarcia** [comment]
The magic of conda vs pip fight!!
