### ISSUE TITLE
AxonIO can not read the right instrument offset and scale 

### ISSUE THREAD

**Issue by zixuanweeei** [NeuralEnsemble/python-neo#491]
Hi,
I think the AxonIO's reader can not read the right offset and scale.
I have use it for reading my .abf file. It gived me a signal with contrary sign, unsuitable offset and scale compared to that opened by the official program Clampfit.

**Comment by samuelgarcia** [comment]
Thank you for the feedback, could you send us a small file (<5Mo) that we could put our testing repo files to debug this ?
Could you also give the same dataset exportedwith another format or a screen copy to get the good scaling ?

**Comment by zixuanweeei** [comment]
@samuelgarcia I am using Axon pCLAMP 10 software, but recently the official website has released a new version. You can search it on their [website](https://www.moleculardevices.com/systems/axon-conventional-patch-clamp/pclamp-11-software-suite) for some resources. And below is the screen copy that a .abf file opened by Clampfit 10. You can download the file from [this link](https://1drv.ms/u/s!AgvhA1GZHIaDn33s6pkmF7_wEG4H).
![clampfit](https://qbtf0q.bn.files.1drv.com/y4mSbHlL48z5DpNZc0MkJbzP_cfxUVHifuIxi-I4Nhll80cS7qHHY-WAPwldxr2AZLtg0mVbVPQPt5q9ljJkpgRWQFTbfWCEOHxsrJIAO9_pftE5y7DQsLr4oDjQGwApR8JXz_xwGyR2zaLBQJQ_1AuQHXKj7VZgu0zbSBT8uZZn__3ZYaG_gJla6z1JpSsn3RgKwT1g-rzuYY6FPY09WRfaQ?width=1366&height=728&cropmode=none)

**Comment by samuelgarcia** [comment]
Thank you for teh file, the bug is confirmed.
Offset and gain and totaly wrong for taht file.

**Comment by samuelgarcia** [comment]
There was a stupid bug in AxonRawIO that invert gain and offset. It is fixed here:
https://github.com/samuelgarcia/python-neo/tree/fix_axon_bug

but I still have a difference between your gain and the one extracted by neo.Axon see this figure:
Do you have an external gain ?

![axon_gain](https://user-images.githubusercontent.com/815627/37594421-55f3a64e-2b75-11e8-9a14-7b829ece2395.png)

**Comment by zixuanweeei** [comment]
@samuelgarcia Thanks a lot! But perhaps there are still some mistakes with your code. And I think the test file I offered has some information losed. Because it was converted by a .atf file which was cutted off from origin .abf file in order to make it small. So I offer a new little large file. Download it from [this link](https://1drv.ms/u/s!AgvhA1GZHIaDn351TYIt4VoewJ8H). 
P.S. [Matlab abf reader](https://cn.mathworks.com/matlabcentral/fileexchange/6190-abfload) seems working for me and the file in the first link.

**Comment by zixuanweeei** [comment]
@samuelgarcia I forgot providing a screen shoot. Sorry for that. But it is same as the picture before.
![github.com](https://qrtf0q.bn.files.1drv.com/y4mLGnepf8FKK88O2mHbwc_rx8sNhBNgBXQpuRDkLb2iXAFtxhumMRJ2nOPRDA4deniN8_-FjiIlcMHbuc-Y_9LXsP98k2DjU0hPkzCiFBw_Ytby2v4-K7gNKgyTa0vLJGsch7Cgtrz-g4iAhsXX9zhmkorCVAW-RL5PePjREP7s6XGqVT6shbE4ZblO9E3cjSEPWqPk4obWR2ij7vYMdMPww?width=1366&height=728&cropmode=none)

**Comment by samuelgarcia** [comment]
With the new ABF file, now the scale is correct. See the figure
So the fix for stupid bug (invert gain and offset) is OK.

![figure_1](https://user-images.githubusercontent.com/815627/37708512-3ee85cc2-2d07-11e8-9669-f296d728276e.png)

For the first abf file, I guess that ABF>ATF>shorten>ABF break somewhere the gain/offset.
I guess if you open it with matlab you also have strange scale, no ?

Could you test ?

**Comment by zixuanweeei** [comment]
Great job! @samuelgarcia 
I became cofused with github. I cloned the version of your work. But it still remains the situation before at Line 197 of axonrawio.py actually. So I corrected the order of `gain` and `offset`. Then I got the right signal.
By the way, I got the right signal with the shorten file using matlab.
