### ISSUE TITLE
improve code style

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#494]
I suggest to adjust the code style of the whole project before releasing 0.6. See also #452.

**Comment by apdavison** [comment]
This was already done in #471 (I used autopep8 rather than yapf)

I agree though it should probably be done again before v0.6., as some non-PEP8 style has crept in through recent PRs

**Comment by JuliaSprenger** [comment]
Did you use specific settings for autopep8? Do you have a config file we should maybe add to the project?

**Comment by apdavison** [comment]
I believe I ran `autopep8 --recursive --aggressive --in-place --max-line-length 99`

**Comment by samuelgarcia** [comment]
Personnaly I am not a big lover of that code style stuff but you are volonters to clean, lets go. Thanks a lot.
In my opinion, in recent PR, the few violation of pep8speak were better that the strict pep8.

**Comment by massich** [comment]
> Do you have a config file we should maybe add to the project?

We mainly added `.pep8speaks.yml` limiting `max-line-length: 99` the rest is pep8 defaults.

**Comment by samuelgarcia** [comment]
Close by #508.
