### ISSUE TITLE
[NixIO] Support multidimensional annotations

### ISSUE THREAD

**Issue by achilleas-k** [NeuralEnsemble/python-neo#501]
See #476 
This will be tricky since NIX metadata does not support multidimensional property values. One option might be to serialise it somehow, though this would make it hard to read outside of Neo. Another option is to make multiple properties that are somehow grouped together, either as a child segment, or by sharing a name prefix with sequential suffixes.

**Comment by achilleas-k** [comment]
Array annotations #472 are a different story and should be much easier to implement.
Signals stored in nix are separated into multiple DataArrays (one per signal), so the array annotation for each signal will be stored in a separate metadata section, one for each DataArray.

**Comment by JuliaSprenger** [comment]
This issue has been fixed in https://github.com/NeuralEnsemble/python-neo/commit/9dc27cf21d7508d408b07dede72d7ba930d36a23.
