### ISSUE TITLE
Neo 0.6.1: error in reading .abf file header (same as #302)

### ISSUE THREAD

**Issue by mqclark** [NeuralEnsemble/python-neo#511]
Hello,

I'm sorry, but I think I'm having the same issue as a user in a previous thread. I keep getting the following error:

File "/Users/matt/anaconda3/lib/python3.6/site-packages/neo/rawio/axonrawio.py", line 458, in parse_axon_soup
'This file does not contain clampex, axoscope or clampfit in the header'

AssertionError: This file does not contain clampex, axoscope or clampfit in the header

I checked the solution previously stated, however it appears in the latest version I downloaded on Monday (3.26.2018) that that had been fixed, e.g. in the latest version it says:
goodstart = -1
for key in [b'AXENGN', b'clampex', b'Clampex',
b'CLAMPEX', b'axoscope', b'Clampfit']:
# goodstart = big_string.lower().find(key)
goodstart = big_string.find(key)
if goodstart != -1:
break
assert goodstart != -1, 
'This file does not contain clampex, axoscope or clampfit in the header'
big_string = big_string[goodstart:]
strings = big_string.split(b'\x00')

Here is the .abf in the hopes it can be looked at.
https://drive.google.com/open?id=1CAXLYRNwLsg5vXIH8SABKod1TCrvwJK0

Thank you,
Matthew Clark

**Comment by samuelgarcia** [comment]
Thank you for report.

This is fix in  #513.
Could you try ?

You are unlucky we have just made a release.

**Comment by mqclark** [comment]
looks like fix in #513 solves that issue but then I have error as stated in issue #219 https://github.com/NeuralEnsemble/python-neo/issues/219
A colleague suggested I try using python2.7 and it seems to be working as expected, so I guess I will use this solution for now.

**Comment by samuelgarcia** [comment]
What error do you still have ?
The #219  mention that read_segment do not work.
But it is not the case now.
Could you send message ?
