### ISSUE TITLE
UnicodeDecodeError in axonrawio.py (0.6.1)

### ISSUE THREAD

**Issue by a-ambrosini** [NeuralEnsemble/python-neo#514]
Hello,

I've recently starting having a problem where some abf files fail on load with a unicode decode error in the header.  I haven't been able to figure out what features cause the failure, but here are two links to files that fail: [1](https://www.dropbox.com/s/erc4b9251iay6xm/p1-1.abf?dl=0) [2](https://www.dropbox.com/s/ufu5a9s5z0xee6g/P1%20sweeps.abf?dl=0).  I've been able to work around the issue by re-exporting the files as pclamp9 rather than pclamp10 abfs, but this isn't a viable fix overall as I'll have students who'll need to process their data without access to pclamp.

Thanks for your help!
A.

```
//anaconda/lib/python3.5/site-packages/neo/rawio/axonrawio.py in _parse_header(self)
    196                                  sig_dtype, units, gain, offset, group_id))
    197 
--> 198         sig_channels = np.array(sig_channels, dtype=_signal_channel_dtype)
    199 
    200         # only one events channel : tag

UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 0: ordinal not in range(128)
```

**Comment by samuelgarcia** [comment]
Thank you for report.
I will have look very soon.
Are you using py2 or py3 ?

**Comment by samuelgarcia** [comment]
Other question : is theses files directly come from official Axon/molecular device software or is it issue from a unofficial format convertion software ?

**Comment by a-ambrosini** [comment]
Hi Samuel,

Thanks for the quick response.  We are using the official pclamp10 and py3.

**Comment by samuelgarcia** [comment]
I find the reason.
The patch is in that PR #516.
Could you test it ?

**Comment by a-ambrosini** [comment]
Hi!  Yes, this fixes that problem.  Thank you!
