### ISSUE TITLE
can't open winwcp file  [Errno 24] Too many open files

### ISSUE THREAD

**Issue by patriciorojasm** [NeuralEnsemble/python-neo#515]
I use neo in two linux boxes with no problem, but in the third I was unable to open winwcp files due to this previous issue https://github.com/python-quantities/python-quantities/issues/129
SO I updated neo and quantites and have a weird error : error: [Errno 24] Too many open files.
But there is only one file to open! 
Do I need to upgrade another package besides neo and quantities?
Below is my code and the  output 

`import numpy as np
from neo import io
#import quantities as pq
import matplotlib.pyplot as plt
%matplotlib inline  

#plt.rcParams['agg.path.chunksize'] = 1000000
file_to_import="130305_004.wcp"
r = io.WinWcpIO( filename = file_to_import)
bl = r.read_block(lazy = False, cascade = True)
data_t = bl.segments[0].analogsignals[1]`

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-1-e2b2bcc6be27> in <module>()
      7 #plt.rcParams['agg.path.chunksize'] = 1000000
      8 file_to_import="130305_004.wcp"
----> 9 r = io.WinWcpIO( filename = file_to_import)
     10 bl = r.read_block(lazy = False, cascade = True)
     11 data_t = bl.segments[0].analogsignals[1]

/usr/local/lib/python2.7/dist-packages/neo/io/winwcpio.pyc in __init__(self, filename)
     17     def __init__(self, filename):
     18         WinWcpRawIO.__init__(self, filename=filename)
---> 19         BaseFromRaw.__init__(self, filename)

/usr/local/lib/python2.7/dist-packages/neo/io/basefromrawio.pyc in __init__(self, *args, **kargs)
     71     def __init__(self, *args, **kargs):
     72         BaseIO.__init__(self, *args, **kargs)
---> 73         self.parse_header()
     74 
     75     def read_block(self, block_index=0, lazy=False, signal_group_mode=None,

/usr/local/lib/python2.7/dist-packages/neo/rawio/baserawio.pyc in parse_header(self)
    149 
    150         """
--> 151         self._parse_header()
    152         self._group_signal_channel_characteristics()
    153 

/usr/local/lib/python2.7/dist-packages/neo/rawio/winwcprawio.pyc in _parse_header(self)
     71                 self._raw_signals[seg_index] = np.memmap(self.filename, dtype='int16', mode='r',
     72                                                          shape=(NP, header['NC'],),
---> 73                                                          offset=offset + header['NBA'] * SECTORSIZE)
     74 
     75                 all_sampling_interval.append(analysisHeader['SamplingInterval'])

/usr/local/lib/python2.7/dist-packages/numpy/core/memmap.pyc in __new__(subtype, filename, dtype, mode, offset, shape, order)
    262         bytes -= start
    263         array_offset = offset - start
--> 264         mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
    265 
    266         self = ndarray.__new__(subtype, shape, dtype=descr, buffer=mm,

error: [Errno 24] Too many open files

**Comment by patriciorojasm** [comment]
Just checked and works with neo 0.5.2 and 0.4 (the one I have in the other machines).
Here is a datafile and a small code that I use for plotting


[170523_008.wcp.zip](https://github.com/NeuralEnsemble/python-neo/files/1892679/170523_008.wcp.zip)

`import numpy as np
import matplotlib.pyplot as plt
from neo import io
%matplotlib inline  

file_to_import="170523_008.wcp"
r = io.WinWcpIO( filename = file_to_import)
bl = r.read_block(lazy = False, cascade = True)
# 
y_s=bl.segments[0].analogsignals[0]
n_rec=np.size(bl.segments)
dt=4.985e-5

plt.figure(figsize=(14,n_rec))
x=np.linspace(0, np.shape(y_s)[0]*dt, np.shape(y_s)[0])

for i in range(0,n_rec):
    #---trace to plot-----
    y_s=bl.segments[i].analogsignals[0]
    plt.subplot(n_rec+1,1,i+1)
    plt.plot(x,y_s, 'k-')
    plt.ylim(-50, 50)
    plt.xlim(0, x[-1])`

**Comment by samuelgarcia** [comment]
Thank you for the file.
This file work onlinux but I guess that widnows do not allow too much memmap on the same file so I made a patch that should be fix your problem.

Could you test ?

With theses command, you can install the WIP fix:
```
pip uninstall neo
git clone https://github.com/samuelgarcia/python-neo.git
git checkout fix_winwcp_515
cd python-neo
python setup.py develop
```

**Comment by patriciorojasm** [comment]
I tried your in two linux machines ans it says


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-30cfaaa1cf81> in <module>()
     10 file_to_import="170523_008.wcp"
     11 r = io.WinWcpIO( filename = file_to_import)
---> 12 bl = r.read_block(lazy = False, cascade = True)
     13 #
     14 y=bl.segments[0].analogsignals[0]

TypeError: read_block() got an unexpected keyword argument 'cascade'

Thanks a lot for taking time to fixing this

**Comment by samuelgarcia** [comment]
**cascade** keyword have disapear in neo 0.6. It is always True.
Just do
```
 bl = r.read_block(lazy = False)
```

**Comment by samuelgarcia** [comment]
Keep this one open.
No problems.

**Comment by JuliaSprenger** [comment]
@patriciorojasm: Does this solve your problem? Can we close this issue?
