### ISSUE TITLE
Update requirements for `nixio`

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/python-neo#519]
In a future release, the version requirement for nixio should be increased. Neo asks for the `nix.__version__` property, which seemingly does not exist in earlier versions of the library and therefore importing Neo fails. 
@achilleas-k Do you know which version of nixio should be required by Neo?

**Comment by achilleas-k** [comment]
1.4.3

Given how nixio it is the current latest release and the neo-nixio depends on a recently added feature (arbitrary unit support), I see no reason to be flexible about the version requirement and have it any lower than that..
