### ISSUE TITLE
overflow encountered in long_scalars

### ISSUE THREAD

**Issue by FGabrielli** [NeuralEnsemble/python-neo#528]
Got a RuntimeWarning: overflow encountered in long_scalars on spike2rawio.py:89 : 
chan_info['t_start'] = block_info['start_time'] * \
                        info['us_per_time'] * info['dtime_base']

while loading a 10500s / 850Mo smr file

I'll try with several files to check whereas the issue is repeatable

**Comment by samuelgarcia** [comment]
@FGabrielli : thank you for reporting.
In #600 I made a very quick patch could you test it with your long file ?

**Comment by FGabrielli** [comment]
Just tested it. Worked ok on a VERY large file (16500s, 1.93Go). Thx Samuel :)

2 warnings remain : 

C:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\anaconda\lib\site-packages\neo\rawio\spike2rawio.py:89: RuntimeWarning: overflow encountered in long_scalars
  info['us_per_time'] * info['dtime_base']

**Comment by samuelgarcia** [comment]
Thank you very much.
I will make the change for the warning.
