### ISSUE TITLE
AnalogSignal.time_slice() does not always return AnalogSignals with the same shape

### ISSUE THREAD

**Issue by grg2rsr** [NeuralEnsemble/python-neo#530]
I am trying to extract spike waveforms by slicing an AnalogSignal at time points from a SpikeTrain
the Problem: the returned slices are not always of the same shape. It seems like there is some rounding problem.

A test snipped to reproduce the problem
```python
import scipy as sp
from scipy import signal
import neo
import quantities as pq

# generate some random AnalogSignal
AnalogSignal = neo.core.AnalogSignal(sp.randn(25000)*pq.uV,t_start=0*pq.s,sampling_rate=25*pq.kHz)

# get the indices of all spikes
spikes_inds = signal.argrelmax(AnalogSignal > 3.25*pq.uV)[0]

# get the spike time points by slicing into AnalogSignal.times and make a SpikeTrain
spike_times = AnalogSignal.times[spikes_inds]
SpikeTrain = neo.core.SpikeTrain(spike_times,t_start=AnalogSignal.t_start,t_stop=AnalogSignal.t_stop,sampling_rate=AnalogSignal.sampling_rate)

# extracting spike shapes by AnalogSignal.time_slice
wsize = 3*pq.ms
expected_shape = int((wsize * AnalogSignal.sampling_rate).simplified.magnitude)

for t in SpikeTrain:
    Asig = AnalogSignal.time_slice(t-wsize/2, t+wsize/2)
    print(expected_shape,Asig.shape[0],Asig.duration.rescale(pq.s))
```
output:
```
75 75 0.003 s
75 74 0.00296 s
75 74 0.00296 s
75 76 0.00304 s
75 75 0.003 s
75 75 0.003 s
75 74 0.00296 s
75 76 0.00304 s
75 74 0.00296 s
75 76 0.00304 s
75 76 0.00304 s
75 76 0.00304 s
75 74 0.00296 s
75 75 0.003 s
75 76 0.00304 s
75 75 0.003 s
75 74 0.00296 s
75 75 0.003 s
75 74 0.00296 s
75 75 0.003 s
```

`expected_shape` is sometimes not equal `Asig.shape[0]` if for odd numbers of `wsize`.

note that this code example produces an unrelated error if the spikes fall too close to the borders of the time segment, but no handling of this is included for brevity reason. Just rerun it in that case.

The issue is somehow related to the indexing into `Analogsignal.times` with the `spike_inds`. If random Spikes are used (such as `SpikeTrain = neo.core.SpikeTrain(sp.rand(10)*pq.s,t_start=0*pq.s,t_stop=1*pq.s,sampling_rate=AnalogSignal.sampling_rate)`) the problem does not occur.

**Comment by JuliaSprenger** [comment]
I agree that using the duration would be a good solution here. But I suggest also to round when converting the duration to integers instead of using int, as done in self.time_index.
```i_stop = i_start + int(np.rint((t_stop-_tstart)*self.sampling_rate))```
