### ISSUE TITLE
[NixIO] Error when writing block with datetime set on file_datetime

### ISSUE THREAD

**Issue by will-hart** [NeuralEnsemble/python-neo#548]
I've built an [`AxographIO`](https://github.com/will-hart/python-neo/tree/axograph_rawio) io module using [`axographio`](https://github.com/CWRUChielLab/axographio). I'm inserting the axograph file's modified time as `block.file_datetime` as follows:

```python
my_block.file_datetime = datetime.fromtimestamp(os.path.getmtime(self.filename))
```

Later, when calling `nix_io.write_block(my_block)`, using a `NixIO`  instance, I get an exception:

    TypeError: Invalid value type: <class 'datetime.datetime'>

<details>
  <summary>Expand for full exception</summary>
<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
&#x3C;ipython-input-3-36e6afb47fb4&#x3E; in &#x3C;module&#x3E;()
      3 try:
      4 #     axo_blk.file_datetime = axo_blk.file_datetime.timestamp()
----&#x3E; 5     writer.write_all_blocks([axo_blk, abf_blk])
      6     axo_blk2 = writer.read_block()
      7 finally:

D:\Code\test_axo_import\neo\io\nixio.py in write_all_blocks(self, neo_blocks)
    497         &#x22;&#x22;&#x22;
    498         for bl in neo_blocks:
--&#x3E; 499             self.write_block(bl)
    500 
    501     def write_block(self, block):

D:\Code\test_axo_import\neo\io\nixio.py in write_block(self, block)
    530             )
    531         if block.file_datetime:
--&#x3E; 532             metadata[&#x22;file_datetime&#x22;] = block.file_datetime
    533         if block.annotations:
    534             for k, v in block.annotations.items():

D:\Anaconda\lib\site-packages\nixio\section.py in __setitem__(self, key, data)
    160 
    161         val = list(map(lambda x: x if isinstance(x, Value) else Value(x),
--&#x3E; 162                        data))
    163         dtypes = functools.reduce(
    164             lambda x, y: x if y.data_type in x else x + [y.data_type],

D:\Anaconda\lib\site-packages\nixio\section.py in &#x3C;lambda&#x3E;(x)
    159             data = [data]
    160 
--&#x3E; 161         val = list(map(lambda x: x if isinstance(x, Value) else Value(x),
    162                        data))
    163         dtypes = functools.reduce(

D:\Anaconda\lib\site-packages\nixio\value.py in __init__(self, value)
     69             self.value = value
     70         else:
---&#x3E; 71             raise TypeError(&#x22;Invalid value type: {}&#x22;.format(type(value)))
     72         self.uncertainty = 0
     73         self.reference = &#x22;&#x22;

TypeError: Invalid value type: &#x3C;class &#x27;datetime.datetime&#x27;&#x3E;
</pre>
</details>

---

Presumably this is because nix/NixIO don't currently support higher level value types (See [issue 665 here](https://github.com/G-Node/nix/issues/665) and [issue 8 here](https://github.com/G-Node/python-neo/issues/8))

However, if I change my IO module to:

```python
my_block.file_datetime = os.path.getmtime(self.filename)
```

the tests for the module fail:

```
======================================================================
FAIL: test_assert_readed_neo_object_is_compliant (neo.test.iotest.test_axographio.TestAxographIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Code\python-neo\neo\test\iotest\common_io_test.py", line 506, in test_assert_readed_neo_object_is_compliant
    assert_neo_object_is_compliant(obj)
  File "D:\Code\python-neo\neo\test\tools.py", line 142, in assert_neo_object_is_compliant
    (attrname, classname, type(obattr), attrtype)
AssertionError: ("file_datetime in Block is <class 'float'> should be <class 'datetime.datetime'>", 'from File_axograph.axgd with lazy=False')
```

I can swap out the `datetime` for a `float` before writing the nix file and then swap it back again, but this is a bit of a pain. 

Is this a known limitation of NixIO, or should I be doing something else on the import?

**Comment by achilleas-k** [comment]
Hi. This seems to be an oversight in the Neo NixIO. It is a known limitation and everything you mentioned is correct. The straightforward approach of converting back and forth is tedious, I agree, which is why the IO is supposed to do the conversion for you. It seems the `file_datetime` attribute specifically is missed in this conversion check.

I'll have a fix for it soon.

Thanks!
