### ISSUE TITLE
when reading NIX file, channel order are disorganized

### ISSUE THREAD

**Issue by carmagnole** [NeuralEnsemble/python-neo#578]
When loading AnalogSignals from NIX files, the channel order is wrong. Instead of [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23...], the channel order will be loaded in [0 1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 23 ...]

**Comment by achilleas-k** [comment]
Looks like it's sorting lexicographically by channel_id. A similar issue was raised about AnalogSignals a while ago (see #545) and I guess I didn't think to check for other occurences when I fixed that one. Thanks for reporting. I'll have a look.

**Comment by achilleas-k** [comment]
@carmagnole I'm not seeing the issue but it might be for a few reasons. Can you paste some code that demonstrates the issue so I can reproduce? Also can  you make sure you're working with a version of the library that includes this fix fd73dd277dec3d8febf32f06dde743c0eb7009c5 from July?

**Comment by apdavison** [comment]
@carmagnole It seems we are unable to reproduce this. Please could you paste some code that demonstrates the issue?

**Comment by rdarie** [comment]
Hi,

I think I've run into something similar to this using nixrawio. There seems to be something weird happening during parse_header(). I paused the debugger on line
https://github.com/NeuralEnsemble/python-neo/blob/26a747c67597355b55204ea76ddf739f9c0cf141/neo/rawio/nixrawio.py#L64
And found this inconsistency between da_idx and seg.data_arrays:
```
(Pdb) w
  <stdin>(2)<module>()
  c:\users\radu\documents\github\python-neo\neo\io\nixio_fr.py(16)__init__()
-> BaseFromRaw.__init__(self, filename)
  c:\users\radu\documents\github\python-neo\neo\io\basefromrawio.py(81)__init__()
-> self.parse_header()
  c:\users\radu\documents\github\python-neo\neo\rawio\baserawio.py(151)parse_header()
-> self._parse_header()
> c:\users\radu\documents\github\python-neo\neo\rawio\nixrawio.py(75)_parse_header()
-> sig_channels.append((ch_name, chan_id, sr, dtype,
(Pdb) da
DataArray: {name = seg0_elec6#0_fr.0, type = neo.analogsignal, id = a9256a9c-dd6a-4092-92b8-497da9ebf9c0}
(Pdb) da_idx
55
(Pdb) seg.data_arrays[da_idx]
DataArray: {name = seg0_elec44#0_fr.0, type = neo.analogsignal, id = 6e981101-a2a2-42a8-a93b-8339cecfbfa4}
```

**Comment by hkchekc** [comment]
@rdarie Unfortunately, we could not reproduce the problem you mentioned. Could you provide some code where the problem occurs and tell us how the NIX file is created? Thanks

**Comment by apdavison** [comment]
As far as I can see, this has been fixed at some point. Please re-open if you still have the problem.
