### ISSUE TITLE
Proposal: extend AsciiSignalIO to allow extra information in a JSON file or in file header

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#579]
At present, `AsciiSignalIO.read_segment` takes several optional arguments describing how the CSV file is structured.

I propose to add support for having this information either:
(i) in a JSON file that would accompany the text file with the data, or
(ii) in a "header" block in the file, with a simple "# name = value" format

The name of the JSON file could either be specified alongside the filename, or could follow a standard pattern, e.g. if the datafile was named "foo.txt" then the IO would automatically look for a file called "foo_about.json" or "foo_map.json"

**Comment by JuliaSprenger** [comment]
I agree, this would be a good extension. I talked to a number of people at the Bernstein Conference, who would appreciate this feature. In my opinion json sounds like the better approach since it is more flexible and keeps the actual csv file clean.

**Comment by apdavison** [comment]
Yes, we seem to have a lot of data in HBP using plain text files for ephys data.

I was thinking we could support both options (external JSON file and internal comments). The advantage of JSON is that you don't need to modify the original data file, but the advantage of internal comments is that everything is in one file.
