### ISSUE TITLE
Neo 0.6.1 incompatibility with latest numpy 1.15.

### ISSUE THREAD

**Issue by alperyeg** [NeuralEnsemble/python-neo#584]
When installing `neo 0.6.1` from pip it causes problems with the latest numpy version 1.15.x. An error is thrown from the analogsignal, that a `float` object has no attribute `t_start`. You can see similar errors in my travis build [here](https://travis-ci.org/alperyeg/elephant/jobs/435683816). 
If I downgrade to numpy 1.10 then the error does not appear. 
The `neo 0.7.dev` version does not cause any problems so far.

**Comment by jpgill86** [comment]
Thanks for reporting, @alperyeg. I believe this is the same issue identified in #556, which, as you observed, is fixed in dev and presumably will be fixed in the next release.

**Comment by alperyeg** [comment]
Thank you for the notification. Good to know. The issue can be closed then.
