### ISSUE TITLE
Set channel list for reading explicitly 

### ISSUE THREAD

**Issue by sin-mike** [NeuralEnsemble/python-neo#590]
@samuelgarcia, I did an inspection of neuralynxrawio.py up to the baserawio.py, and I couldn't find a way to set a channel list for reading. Is there a way? Could I implement it in neuralynxrawio explicitly? 

e.g. it will just filter by channel id in the following structures
```
        self.ncs_filenames = OrderedDict()  # chan_id: filename
        self.nse_ntt_filenames = OrderedDict()  # chan_id: filename
        self.nev_filenames = OrderedDict()  # chan_id: filename

        self._nev_memmap = {} #
        self._spike_memmap = {}
        self.internal_unit_ids = []  # channel_index > (channel_id, unit_id)
        self.internal_event_ids = []
```

as well as in `self.header`

**Comment by samuelgarcia** [comment]
Are you at neo.io or neo.rawio level ?

For neo.io level, channel selection when reading is not yet implemented but the futur lazy/proxy object will do this.
See #461.
It should be merged in December.

For neo.rawio level you can do
```
reader = neo.NeuralynxRawIO(dirname='/ath/to/dataset')
reader.parse_header()

# read signal by channel index (0 based)
raw_sig = reader.get_analogsignal_chunk(channel_indexes=[0,5,24, 36])

# read signal by channel name
raw_sig = reader.get_analogsignal_chunk(channel_names=['ch0', 'ch5', 'ch24', 'ch36'])

# read signal by channel id.
# the notion of IO vary from IOs
raw_sig = reader.get_analogsignal_chunk(channel_ids=[...])
```


This is briefly documented here:
https://neo.readthedocs.io/en/0.6/rawio.html#basic-usage
please add any thing in the doc that would help.

**Comment by sin-mike** [comment]
@samuelgarcia Thank you! It makes sense now. However, in our lab, we have some experiments at which the chan_id is not unique. I want people to switch to python+neo from Matlab, but in this exact case, they get a mess in their data. Their use case is that, when you record in DC mode, you can assign two different channels for the same AD channel, each with different preprocessing. It becomes much handier for their purposes. A simple workaround is to split files in the working directory to ensure channel uniqueness. But my suggestion was simply to list explicitly, which channels to read, e.g. passing a subset of files to the reader. Because by default the reader just scans the whole dir at a time of init. When the chan_id is not unique, the ordered dicts are all broken, as in pic:

![image](https://user-images.githubusercontent.com/4338049/47564805-eb0cae80-d92e-11e8-896e-1bff17026492.png)

I'm inserting a screenshot with the record structure as well:

![image](https://user-images.githubusercontent.com/4338049/47564586-26f34400-d92e-11e8-8377-4a7301103108.png)

Sincerely,
Mike

**Comment by sin-mike** [comment]
> Anwser 2:
> The actual NeuralynxRawIO have a silent bug!! Thank you very much to discover it.
> 
> len(ncs_filenames) should be header['signal_channel'].size and it is not the case.
> 
> I guess that when I wrote this IO I made the assumption that the chan_id was unique.
> 
> The fault is on ncs_filenames that should not be a dict by chan_id.
> 
> I need to fix it because you will read data from randomly group 0 or group 1 across channels.

I had already implemented this workaround in my local copy.  I made a trick, that chan_id -> generic UID, which, in my case was just an enumeration of files. Just debugging it. However, I don't know how it fits the architecture. Would you need a PR?

**Comment by sin-mike** [comment]
>

**Comment by sin-mike** [comment]
>

**Comment by samuelgarcia** [comment]
The other solution is to use double key for the ncs_filenames
ncs_filenames[(chan_id, chan_name)] = ...

Would be you OK to do the ptach ?

**Comment by sin-mike** [comment]
Yep, I'm ok. I will do with double key then. And the spiking filenames too.

**Comment by samuelgarcia** [comment]
Spiking file also do not have unique ID ????

**Comment by sin-mike** [comment]
my fault. the units are unique.

btw, @samuelgarcia, how do you usually debug things in neo? do you reinstall the whole package with debug options or you put debug controls directly to the installed files?

**Comment by samuelgarcia** [comment]
I do
```bash
git clone python-neo
cd python-neo
python setup.py develop  # not setup.py install
```
This perform an installation by alias so you can coutinue to modify files until it works.
Then git comit.

And I do this in a dedicated environement.
I use virtualenvwrapper but there are many other ways (pyenv, canda, venv)

**Comment by sin-mike** [comment]
Good, I will try

**Comment by samuelgarcia** [comment]
#681

**Comment by samuelgarcia** [comment]
Done in #681
