### ISSUE TITLE
get_io() doesn't return the correct IO when we have an ascii spiketrain file

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#616]

**Comment by apdavison** [comment]
Since `get_io()` is based on file suffixes, I the only way to fix this would be to merge AsciiSignalIO and AsciiSpikeTrainIO.

**Comment by JuliaSprenger** [comment]
This issue also exists for other ios supporting generic formats like `hdf5`. With the new implementation of [list_candidate_ios]()ttps://github.com/NeuralEnsemble/python-neo/blob/3f0225c2551714295a6ad8eabdbd51032f83b2d4/neo/io/__init__.py#L413) there's at least a way to know which IOs should be considered. `get_io()` now returns the 'most likely' best IO for the given file format, which is still not always correct, but the best we can do so far.
Is this closing the issue or do you have more ideas on how to improve the `get_io` function?

**Comment by zm711** [comment]
I want to second Julia's statement. I believe the `get_io` now returns the most likely io and that if the user wants to be able to pick their io they can use `list_candidate_ios`. I'm going to change the milestone to 13.1 so we can discuss this in case we forget to close this before then.

**Comment by zm711** [comment]
@apdavison, since you're still on are we good to close this now. I switched the tag so we would discuss but since we ran out of time.

**Comment by apdavison** [comment]
we're good
