### ISSUE TITLE
duplicate_with_new_array changed to duplicate_with_new_data

### ISSUE THREAD

**Issue by aguimera** [NeuralEnsemble/python-neo#621]
The basesignal class method  "duplicate_with_new_array" has been changed by "duplicate_with_new_data" in version 0.7, it can produce back compatibility errors.

**Comment by jpgill86** [comment]
Indeed, this is affecting elephant, and a simple fix is proposed in NeuralEnsemble/elephant#189.

In my opinion, the old name should have been retained as an alias for at least one development cycle, eventually deprecated, and later removed, but, hey, hindsight is 20/20. In the words of Michael Scott, we should have had hindsight.

**Comment by apdavison** [comment]
> the old name should have been retained as an alias for at least one development cycle, eventually deprecated, and later removed

I completely agree. It was more a case of oversight than lack of foresight - the change was in a PR that was merged a short time before the release, and we didn't notice the change! 

I actually think we should reintroduce an alias in the next release.

**Comment by apdavison** [comment]
Done. Released in v 0.7.1
