### ISSUE TITLE
branching policy

### ISSUE THREAD

**Issue by massich** [NeuralEnsemble/python-neo#634]
you don't keep a maint/0.x for the current branches? 

This confused me because I had installed 0.6 (I missed 0.7.x release), and reading the doc I realized I was reading 0.8.

How do you work? you just keep master and freeze it ?

**Comment by apdavison** [comment]
We create a branch named "0.x" when needed. There is a branch called "0.6" for example.

There is not yet a branch "0.7" because there had been no significant changes to master when we needed to release 0.7.1. If we need to release 0.7.2, we will create "0.7" at that point.

**Comment by massich** [comment]
ok, great to know. Closing.
