### ISSUE TITLE
Include packaging.version in CI builds?

### ISSUE THREAD

**Issue by achilleas-k** [NeuralEnsemble/python-neo#640]
A couple of days ago I opened PR #636 to add version checking for library compatibility between the NIX IO and the NIXPy library. Instead of parsing the version string manually (split on "." and int() the parts), @JuliaSprenger rightly suggested that it would be better to use Version objects, from the packaging.version module, but the module isn't available in the CI builds (except for Python 3.4 on Travis for some reason).

Will the packaging module be added to the CI builds or should I revert to parsing manually?

**Comment by achilleas-k** [comment]
The issue with distutils.version is that, as far as I can tell, it's meant to just be there to report on the package version and any other functionality is undocumented.
https://docs.python.org/2/distutils/apiref.html#module-distutils.version
https://docs.python.org/3.7/distutils/apiref.html#module-distutils.version

**Comment by achilleas-k** [comment]
Is there a decision on this?

**Comment by JuliaSprenger** [comment]
If `distutils` is already there we can go on and use it for now and not introduce additional dependencies.

**Comment by samuelgarcia** [comment]
I am also in not intriduce dependencies.

**Comment by apdavison** [comment]
after more discussion, @samuelgarcia @JuliaSprenger and I are in favour of using distutils.version

**Comment by achilleas-k** [comment]
Updated PR.  Closing the issue.

**Comment by samuelgarcia** [comment]
New in python 3.8
```python
from importlib.metadata import version
version(XXXX)```
