### ISSUE TITLE
Annotation problem for Analogsignal in BaseFromRawIO

### ISSUE THREAD

**Issue by hkchekc** [NeuralEnsemble/python-neo#643]
If I am not mistaken, in the baserawio.py and proxyobjects.py, the annotations of the Analogsingal Object cannot be inherited from the rawio.raw_annotations (Unless the length of signal_channel is 1) :

https://github.com/NeuralEnsemble/python-neo/blob/b4c5950d85ed4cedf27caf7dd36aa41067ab01ab/neo/io/proxyobjects.py#L115

I want to know is that intentional and is there anyway for getting customized annotations through?

Thank you.

**Comment by samuelgarcia** [comment]
In #461 (proxy and lazy) recently merge, what I did is to add array_annotations in IO.
In short, channel_names and channel_ids are now in array_annotations.
By nature, all annotation that concern all channels should be in array_annotations.

At rawio level, channel annotations are a dict for each channel.
So mapping the list of dict to of one dict (annotation) is obvious only when there is one channel.

For particular annotations that concern all channel, it is easy to create an array_annotation.
I did something similar for  it for ```ChannelIndex``` here https://github.com/NeuralEnsemble/python-neo/blob/b4c5950d85ed4cedf27caf7dd36aa41067ab01ab/neo/io/basefromrawio.py#L135
It should be easy to do the same in AnalogSignalProxy.
I can do it.

**Comment by hkchekc** [comment]
will be great

> In #461 (proxy and lazy) recently merge, what I did is to add array_annotations in IO.
> In short, channel_names and channel_ids are now in array_annotations.
> By nature, all annotation that concern all channels should be in array_annotations.
> 
> At rawio level, channel annotations are a dict for each channel.
> So mapping the list of dict to of one dict (annotation) is obvious only when there is one channel.
> 
> For particular annotations that concern all channel, it is easy to create an array_annotation.
> I did something similar for it for `ChannelIndex` here
> 
> [python-neo/neo/io/basefromrawio.py](https://github.com/NeuralEnsemble/python-neo/blob/b4c5950d85ed4cedf27caf7dd36aa41067ab01ab/neo/io/basefromrawio.py#L135)
> 
> Line 135 in [b4c5950](/NeuralEnsemble/python-neo/commit/b4c5950d85ed4cedf27caf7dd36aa41067ab01ab)
>  keys = list(self.raw_annotations['signal_channels'][ind_abs[0]].keys()) 
> 
> It should be easy to do the same in AnalogSignalProxy.
> I can do it.

will be great

**Comment by apdavison** [comment]
Implemented in #709
