### ISSUE TITLE
simple_plot_with_matplotlib.py <- wrong distant url

### ISSUE THREAD

**Issue by cskoven** [NeuralEnsemble/python-neo#644]
The distant url refers to an overview of sample files (html page) and the simple plot file therefore does not work.

I found the right url and changed the line:
distantfile = 'https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/raw/master/plexon/File_plexon_3.plx'

That seems to be working...

Br,
Christian Skoven

**Comment by samuelgarcia** [comment]
Thank, is it in  doc or an example script ?

**Comment by apdavison** [comment]
Fixed in 710b425
