### ISSUE TITLE
Add new OpenEphys format

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#654]
OpenEphys have several formats.

The ex default format is already implemented in neo.rawio and is described [here](https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/65667095/Flat+binary+format+old+version)

The new default format is **not** implemented in neo. It is descirbed [here ](https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/166789121/Flat+binary+format)

I guess that today all new data are recorded with the new format, we should implemented it.
Note that the new format should be easier to implemented because the structure is less ambiguous and most of the file are **npy** based.
The new format support subfolder  "experiment" and subsubfolder "recording" that could be map "Block" and "Segment" directly.

**Comment by JuliaSprenger** [comment]
see #945
