### ISSUE TITLE
problems with reading blackrock nsx files

### ISSUE THREAD

**Issue by jsv13** [NeuralEnsemble/python-neo#660]
Hi all,
I'm trying to read BlackRock nsx data and I do run into several problems.

1. When reading a ns2 file which is only 100MB long, then it takes unreasonably long time to parse the header. The code I use is following:
``` 
from neo.io.blackrockio import BlackrockIO
reader = BlackrockIO(filename=file_name, verbose=True)
```
2. If I use 
```
from neo.rawio import BlackrockRawIO
reader = BlackrockRawIO(filename=file_name)
reader.get_analogsignal_chunk(i_stop=300)
```
the I get an error 

> AttributeError: 'BlackrockRawIO' object has no attribute '_several_channel_groups'

3. There is also this option
`from neo.io import OldBlackrockIO as BlackrockIO`
but the differences to (1) are not clear. Should this option still be used?

In general I have the impression that reading BlackRock files is not that well documented. Do you have any nice examples which work also for larger files?

Thanks for your help.

**Comment by JuliaSprenger** [comment]
Hi @jsv13!
Parsing the header indeed shouldn't take very long for such a small file. Can you give more details on
- the Blackrock file format version
- the neo version

or even provide the ns2 file for testing purposes?

If you plan to use the neo structure for handling your data, then using the approach 1) is the correct one. Approach 2) gives you fast access to the raw data, but does not provide any utilities (eg. quantity handling...) around that.  Regarding your approach 3) There is still an old (non-raw) implementation of the `BlackrockIO` present for compatibility reasons until the current implementation covers all functionality of the old implementation. You can also try out the `OldBlackrockIO`, but be aware this has very different parameters and is slower than the `BlackrockIO`.

**Comment by samuelgarcia** [comment]
Hi.
BlackrockIO do not only oarse header but also load all data in memory and by default scale everything to units so it is quite heavy.

In actual master there is a lazy load option, 
reader = BlackrockIO(filename=file_name, lazy=True)

Samuel

**Comment by jsv13** [comment]
neo version:  0.7 and now I pulled also 0.8.0.dev (same problem)
blackrock file format version: 2.3

1. I see that most of the time is spent in  `__read_nsx_dataheader_variant_b`
2. reader = BlackrockIO(filename=file_name, lazy=True) gives an error with 0.8.0.dev:

> TypeError: __init__() got an unexpected keyword argument 'lazy'
3. Unfortunately I cannot share ns2 file, it's human data, would be difficult from regulatory and data protection point of view

**Comment by samuelgarcia** [comment]
Oups my bad.
```python
reader = BlackrockIO(filename=file_name)
reader.read_block(lazy=True)
```

And you are right, ```reader = BlackrockIO(filename=file_name)``` should do only the parse_header and should be fast.
I am sorry I awsered to quickly.

Maybe it is due to the event and spike file that are really big.
Because to get all possible units the file must entierily read at parse_header stage.

What append if you move the nev file somewhere else ?

**Comment by jsv13** [comment]
still the same if I move the nev file away. To me it seems the problem to be the following:

In the  `__read_nsx_dataheader_variant_b` method  the offset is increased  only by 9 bytes at a time, because data_size is zero  ( see `offset = data_header[index]['offset_to_data_block'] + data_size` ).
So, it goes through a 100MB file 9 bytes at a time, this doesn't look correct, does it?

**Comment by JuliaSprenger** [comment]
Maybe the number of channels was not recognized correctly? Can you also check `self.__nsx_basic_header[nsx_nb]['channel_count']` and `dh['nb_data_points']` in the same method?

**Comment by jsv13** [comment]
- self.__nsx_basic_header[nsx_nb]['channel_count'] = 128  (correct)
- dh['nb_data_points'] = 0  . I don't know what this should be, but I guess this causes the problem

**Comment by JuliaSprenger** [comment]
Yes, it looks like the number of datapoints is either not recognized correctly, or all your data pakets are empty. Do you get `dh['nb_data_points`]==0` for all data pakets, i.e. all iterations of the `while` loop?

**Comment by jsv13** [comment]
yes, for all iterations

**Comment by JuliaSprenger** [comment]
That's puzzling. Are you sure the data was recorded correctly? Eg. can you replay it using the Blackrock system used for recording or visualized it using the NeuroExplorer tool? @samuelgarcia: Do you have any more ideas regarding this?

**Comment by jsv13** [comment]
well, I can open the file with NPMK without a problem. I will check neo with other files as well and report back.

**Comment by samuelgarcia** [comment]
This is very strange.

@jsv13 : would you have any possibility to record a new on the same system with same configuration but wihtout patient, so we could have the same buggy file ?
We could so include it in our test file.
Without the file, I guess that you are the only one able to debug this...

@JuliaSprenger I went to the code of ```__read_nsx_dataheader_variant_b```. I guess we could avoid the loop with a memmap no ?

**Comment by JuliaSprenger** [comment]
@samuelgarcia: Yes the loop can be avoided by incorporating the `__read_nsx_dataheader` directly into the `__read_nsx_dataheader_variant_b` if you assume the numer of data points per paket is constant. But I think this would make the code less modular and readable. If you have a suggestion for a readable version without the loop, I am happy to review your PR :)

**Comment by jsv13** [comment]
@samuelgarcia : This may not happen any time soon, but yes I could try. So far, I've had this problem only with one file.

**Comment by apdavison** [comment]
@jsv13 unfortunately I think we have to close this issue as unfixable for now. If you can provide us with a test file that exhibits the problem, we can reopen the ticket.
