### ISSUE TITLE
Blackrock events not identified correctly

### ISSUE THREAD

**Issue by histed** [NeuralEnsemble/python-neo#671]
Several months ago I noticed that neo's blackrock reading code wasn't parsing digital events correctly.  
I fixed this in an old version of neo:
https://github.com/histedlab/python-neo/commit/591e15624a592caa9f8f0d0cb3f4469ef619ea3f

> Blackrock specs say packet_insertion_reason is
1 for PARALLEL and 129 for SERIAL.  (also 64 for PERIODIC, not implemented)
i.e. bit 1 is set for parallel and bits 1 and 7 are set for serial.
Because the bitfield is just a unique ID, I removed the bit testing and use equality instead.

It looks like I forgot to send a pull request then, and this may now be bitrotted.  If someone wants to fix up and commit, that would be fine.  Otherwise at some point I will look into rebasing on top of current neo master.

**Comment by histed** [comment]
until then perhaps info above helps others seeing this issue

**Comment by samuelgarcia** [comment]
Hi @histed, thank you for reporting this.
Could you make a pull request for this on the current master ?

We are working on 0.8 release. It could be good to have it.

**Comment by samuelgarcia** [comment]
I have done a PR for this but I did not keep the if .. raise

**Comment by histed** [comment]
Hi Samuel,
Thanks for doing this.  Looks to me like it should fix the issue.
Mark
