### ISSUE TITLE
Extracting keyboard markers from Spike2 

### ISSUE THREAD

**Issue by MatthiasKohler** [NeuralEnsemble/python-neo#679]
Dear all,

I have some older Spike2 smr files. During the recording markers were set by a keyboard press. I would like to extract the time of the marker and which key was pressed. 

reader = neo.io.Spike2IO(filename='Spike2File.smr')
data = reader.read(lazy=False)[0]
e = data.segments[0].events

e then seems to contain the times. Is it possible to also get the pressed key?

Thank You

**Comment by samuelgarcia** [comment]
Could it be in e.labels ?

**Comment by MatthiasKohler** [comment]
Yes that could be the case. Tanks a lot.
