### ISSUE TITLE
Neuralynx annotations from 0.7.1 to 0.8 dev

### ISSUE THREAD

**Issue by sin-mike** [NeuralEnsemble/python-neo#680]
Guys, please, I can't figure it out myself, the annotations are different

In version 0.7.1 with any number of channels, everything is correct:
![image](https://user-images.githubusercontent.com/4338049/60382554-43232400-9a6d-11e9-994d-632f6736c8dc.png)

In version 0.8 dev (Master HEAD by now) with _two_ channels:
![image](https://user-images.githubusercontent.com/4338049/60382501-8e890280-9a6c-11e9-917d-a7dd73a236f9.png)

In version 0.8 dev (Master HEAD by now) with _one_ channels:
![image](https://user-images.githubusercontent.com/4338049/60382540-048d6980-9a6d-11e9-8fd5-216a5edd31cf.png)

???

**Comment by sin-mike** [comment]
OK, false alarm, the required field has now been moved from "annotations" to "array_annotations"

**Comment by samuelgarcia** [comment]
Excatly all annoations that array like with the one dimenssion matching the datat itself are moved to array_annotation. With this when slicing array_annotation are also sliced.
