### ISSUE TITLE
Release 0.7.2

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/python-neo#687]
Now that the 0.7.x maintenance branch has been created with passing tests (#683) and AxographRawIO has been backported into it (#682), release 0.7.2 could be created.

Afterwards, the release notes can be merged into master, I think.

**Comment by apdavison** [comment]
Release 0.7.2 is now on PyPI.

We still need release notes to be written for both 0.7.1 and 0.7.2

**Comment by jpgill86** [comment]
Thank you @apdavison!
