### ISSUE TITLE
Tasks for 0.7.x maintenance branch

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/python-neo#691]
- [x] Push commit(s) with version string changed from "0.7.1". @apdavison, I think you may have released 0.7.2 from a local change on your machine without actually pushing a commit with the version string changed to "0.7.2" to the maintenance branch.
- [x] Backport release notes (#692).

**Comment by apdavison** [comment]
@jpgill86 indeed, mea culpa

**Comment by jpgill86** [comment]
Tasks complete!
