### ISSUE TITLE
TdtIO fails, cannot parse hearer

### ISSUE THREAD

**Issue by matthewperkins** [NeuralEnsemble/python-neo#696]
`<ipython-input-9-f9bc361d5909> in <module>
----> 1 reader = TdtIO(dirname = 'TDTdata/')

~/.virtualenvs/tdc/lib/python3.6/site-packages/neo/io/tdtio.py in __init__(self, dirname)
     18     def __init__(self, dirname):
     19         TdtRawIO.__init__(self, dirname=dirname)
---> 20         BaseFromRaw.__init__(self, dirname)

~/.virtualenvs/tdc/lib/python3.6/site-packages/neo/io/basefromrawio.py in __init__(self, *args, **kargs)
     71     def __init__(self, *args, **kargs):
     72         BaseIO.__init__(self, *args, **kargs)
---> 73         self.parse_header()
     74 
     75     def read_block(self, block_index=0, lazy=False, signal_group_mode=None,

~/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/baserawio.py in parse_header(self)
    149 
    150         """
--> 151         self._parse_header()
    152         self._group_signal_channel_characteristics()
    153 

~/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/tdtrawio.py in _parse_header(self)
    140             self._seg_t_stops = [self._seg_t_stops[x] for x in sort_inds]
    141             self._tsq = [self._tsq[x] for x in sort_inds]
--> 142         self._global_t_start = self._seg_t_starts[0]
    143 
    144         # signal channels EVTYPE_STREAM
`

**Comment by matthewperkins** [comment]
I was just messing up the directory structure... closing.

**Comment by balajisriram** [comment]
@matthewperkins could you specify what the error in the directory structure was - I couldnt read a TDT tank either and got a similar error
