### ISSUE TITLE
mv neo/io/proxyobject to neo.core/proxyobject ?

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#708]
@apdavison @JuliaSprenger 
We have decided to move proxyobject to core.

The main issue I see in that test_proxyobject depend on neo.rawio because we need at least on rawio to test it.

```from neo.rawio.examplerawio import ExampleRawIO```

proxyobject do not have direct dependency on neo.rawio but the relative tests do have this dependency. And of course there is an implicit dependency on rawio because proxyobject is also layer between neo.io and neo.rawio. basefromrawio really depend on proxyobject.

I think it was the main reason why I put proxy into neo.io even it is not natural.

I am not sure to be so happy to have this kind of circular dependency even it is at test level.

What do you think ?
Do I move proxy to core or not ?

**Comment by apdavison** [comment]
I tried this in a branch a few weeks ago, and I couldn't get it to work, there were always circular imports.

I'm sure it's possible, but I think it will need a careful mapping of dependencies.

**Comment by samuelgarcia** [comment]
Do you still think we need to move proxy in core so ?
The main issue is that conceptually proxy depend on rawio even if there is no directy import.

In short the logical dep cycle is **core<rawio<proxyobject<io** trying to move proxy to core will lead to problem soon or later.
No ?

**Comment by apdavison** [comment]
I think the motivation is that we wish to treat real objects and proxy objects the same wherever possible, as in #652.

It might be sufficient to just move `BaseProxy` to core.

**Comment by samuelgarcia** [comment]
OK I propose:
  * in neo.core: BaseProxy + a function si_proxy(...) that would be done with isinstance(..., BaseProxy).
    This would avoid ```hasattr(self.spiketrains[st_id], '_rawio')``` like wa can have in seg.time_slice
  * in neo.io: AnalogSignalProxy/EventProxy/SpikeTrainProxy/EpoxhProxy

So we limit the risk and the work on this.

A clever solution would be to seperate AnalogSignalProxy in two parts:
  * one declarative that would be neo.core
  * one that do the implement the loading based on rawio and would be in neo.io
Maybe for next version ?

**Comment by zm711** [comment]
@samuelgarcia,

this issue has also been open for 5 years and we have moved across 4 versions. Is this something we just move to future or close?
