### ISSUE TITLE
grouping mode default should now be 'group-by-same-units'

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#710]
For smooth trnasition with very behavrio of neo (one channel = one AnalogSignal)
when have the option ```signal_group_mode = 'split-all'/'group-by-same-units'```

For each io the default mode can be diffrent because of this ```_prefered_signal_group_mode```
 
I think we should change this
```_prefered_signal_group_mode = 'split-all'```

to  this

```_prefered_signal_group_mode = 'group-by-same-units'```

for all IOs.

**Comment by samuelgarcia** [comment]
Lets put a warning in 0.8 and change in 0.9

**Comment by apdavison** [comment]
This changes the default behaviour of IO classes, so I think we should add a DeprecationWarning for now, and change the behaviour in 0.9

**Comment by samuelgarcia** [comment]
Duplicate of #832
