### ISSUE TITLE
Problem with label reading .TRC

### ISSUE THREAD

**Issue by koopa31** [NeuralEnsemble/python-neo#732]
Good afternoon,
I noticed reading .TRC files there was a problem when special characters like 'é' were present in the labels. As a consequence, I had to overload methods like _get_event_timestamps. In fact he problem is mainly when doing: labels = raw_event['label'].astype('U').
Indeed, as the elements of raw_event['label'] contain specail characters they are 'iso-8859-1' and cannot be converted. In the end, I had to do:
        decoder = np.vectorize(lambda x: x.decode('iso-8859-1'))
        if len(raw_event) != 0:
            labels = decoder(raw_event['label']).astype('U')
        else:
            labels = raw_event['label'].astype('U')
Best regards.

**Comment by samuelgarcia** [comment]
Hi @koopa31. Thank you for this report.
Sorry for the super long delay.
I can add it in MicromedrawIO but are you sure that all micromed file are 'iso-8859-1' ?

**Comment by koopa31** [comment]
Hi,
I’m not working in the lab anymore, but I transferred the message to my colleague Quentin Delannoy. He’ll answer you as soon as he goes back from holidays. Thank you for your answer. 
Best regards. 
Clément Cazorla
