### ISSUE TITLE
Problem with reading BCI2000 data

### ISSUE THREAD

**Issue by flecaignard** [NeuralEnsemble/python-neo#734]
Hi!
I'm trying to import BCI2000 data (ECoG data) but io.BCI2000IO fails, and I get this error message :
![Capture d’écran 2019-09-16 à 16 53 10](https://user-images.githubusercontent.com/48314202/65251582-de211c80-daf7-11e9-86df-adaba4061762.png)
I could send one of my data file if needed ?

Thanks fo your help!
Françoise

**Comment by JuliaSprenger** [comment]
Hi @flecaignard!
If you have a small test file you could provide, I can have a look.

**Comment by flecaignard** [comment]
Thanks @JuliaSprenger !
Here is a file, which make the import failing
(basically there is not much in there, I should send a datafile but it is 300 Mo big) 
[debug.py.txt](https://github.com/NeuralEnsemble/python-neo/files/3631959/debug.py.txt)

hope this helps!
thanks

**Comment by JuliaSprenger** [comment]
The script does not help much, since there is no information about the content of the file you are loading.
If your data is not confidential and you can upload the file to some server and provide the link to it or send the link via email if you don't want it to be public.

**Comment by flecaignard** [comment]
ok, I prefer email  (clinical data)
could you give me an email  to send the link?

**Comment by flecaignard** [comment]
meanwhile I've send the link to @samuelgarcia ,
thanks for giving me your address ;-)

**Comment by JuliaSprenger** [comment]
So @samuelgarcia is looking into this? Otherwise you can use j.sprenger@fz-juelich.de.

**Comment by flecaignard** [comment]
Hi Julia, I've sent the link to yout adress, thanks+++

**Comment by samuelgarcia** [comment]
Hi Julia, I am not the original author of this format. I only made the port to rawio 2 years ago.
I can have look next week.
Cheers

**Comment by JuliaSprenger** [comment]
Hi @flecaignard,
I introduced a small fix such that you can load the files. You can find the fix here https://github.com/JuliaSprenger/python-neo/tree/fix/bci2000. Could you please test this version and see if everything else works for you? E.g. if the information contained in the file header is available and signal are decoded correctly? You can install the Neo version including the fix, e.g. via pip `pip install git+https://github.com/juliasprenger/python-neo.git@fix/bci2000`. If everything works for you I will make a PR to include the fix in the main Neo repo.

**Comment by flecaignard** [comment]
Hi @JuliaSprenger ! Thanks for your help, I'll look into this and let you know asap
thanks!

**Comment by flecaignard** [comment]
Hi @JuliaSprenger ,
I could import data, and amplitudes look fine, as well as header info. 
thanks again!
