### ISSUE TITLE
Load() method lacking for lazy reader?

### ISSUE THREAD

**Issue by luiztauffer** [NeuralEnsemble/python-neo#735]
Hi, following instructions from [docs](https://neo.readthedocs.io/en/latest/io.html) I’m trying to lazy read a directory with Neuralynx files, but can’t find a way to load the data to memory. E.g.:
```python
from neo.io.neuralynxio import NeuralynxIO
import os

dirname = os.path.join(os.getcwd(), 'data')
nio = NeuralynxIO(dirname=dirname, use_cache=False)

seg = nio.read_segment(lazy=True)
anasig = seg.analogsignals[0]
anasig.load()
```

which raises:
```
AttributeError: 'AnalogSignal' object has no attribute 'load'
```

I can read slices of data with:
```python
nio.get_analogsignal_chunk(channel_indexes=[0], i_start=0, i_stop=100)
```

I’m not sure if this is a bug, or am I doing something wrong?

**Comment by apdavison** [comment]
https://neo.readthedocs.io/en/latest/ shows the docs for the development version.

If you installed Neo with `pip install neo` you will have the latest release (0.7.2), which does not contain the lazy loading as shown in your example. The docs for the latest released version are at https://neo.readthedocs.io/en/0.7.2 or https://neo.readthedocs.io/en/stable

We will probably release Neo 0.8.0 within the next week, at that point `pip install -U neo` will upgrade to the new version, and your code example should then work.

**Comment by luiztauffer** [comment]
@apdavison thanks!
