### ISSUE TITLE
Unable to write neo annotations with NixIO

### ISSUE THREAD

**Issue by seankmartin** [NeuralEnsemble/python-neo#743]
Hello, 
I am unable to write neo block annotations to file using NixIO. I also tried matlab io but this didn't work either. Below are a minimal example and a screenshot of the resulting hdf5 file. Thanks! 
Sean

````
from neo.core import Block, Segment, Event
from neo.io import NixIO
import os

filename = "annot_only.nix"
anots = {"Hi": 10, "nix_name": "1"}
blk = Block(annotations=anots)
nio = NixIO(filename=filename)
nio.write(blk)
nio.close()
````

![h5View](https://user-images.githubusercontent.com/21295664/66146488-cb810a00-e604-11e9-906a-d2ef56e380c6.PNG)

**Comment by achilleas-k** [comment]
Annotations aren't set with the keyword argument `annotations` but instead, any extra keyword argument that isn't specified in the constructor.  So in this case, the code should be:
```python
from neo.core import Block
from neo.io import NixIO

filename = "annot_only.nix"
anots = {"Hi": 10, "nix_name": "1"}
blk = Block(**anots)
nio = NixIO(filename=filename)
nio.write(blk)
nio.close()
```

which produces
```
❯ h5ls -d -r annot_only.nix/metadata/1/
/properties              Group
/properties/Hi           Dataset {1/Inf}
Data:
(0) 10
/properties/neo_name     Dataset {1/Inf}
Data:
(0) ""
/properties/nix_name     Dataset {1/Inf}
Data:
(0) "1"
```

The result in your original code was the creation of an annotation called `annotations` which was a dictionary and the NIXIO just used the keys as values for that annotation.

**Comment by seankmartin** [comment]
Thank you very much! My apologies, I misunderstood how annotations were meant to be passed. I appreciate the clarification! All the best,
Sean
