### ISSUE TITLE
Trouble reading some BCI2000 files

### ISSUE THREAD

**Issue by flecaignard** [NeuralEnsemble/python-neo#744]
Hi everyone

Thanks to an update in reading BCI2000 data (#736, #734) I can now import my *.dat files into neo. However, I've just figured out that an issue remains for some of my files, and it looks to be due to how the gain is specified in the header.

could you help me on this ?

attached: 
- snapchot of the error I get using neo reader
- 
<img width="614" alt="Capture d’écran 2019-10-04 à 14 09 14" src="https://user-images.githubusercontent.com/48314202/66206558-ba8dd280-e6b0-11e9-9eb2-df650710db69.png">
![Capture d’écran 2019-10-03 à 17 29 36](https://user-images.githubusercontent.com/48314202/66206572-c37ea400-e6b0-11e9-9ee0-5951af6991b1.png)
![Capture d’écran 2019-10-03 à 17 29 47](https://user-images.githubusercontent.com/48314202/66206574-c4173a80-e6b0-11e9-8881-ef1fb0dd8220.png)

and two snapshots of the SourceChGain value (observed using Matlab load_bcidat.m) in one working  file (index 78), and in a failing one (85)

Thank you for your help on this!
Françoise

**Comment by flecaignard** [comment]
![Capture d’écran 2019-10-03 à 17 29 47](https://user-images.githubusercontent.com/48314202/66206634-ec9f3480-e6b0-11e9-8bff-bbd2b67fecde.png)

**Comment by flecaignard** [comment]
![Capture d’écran 2019-10-03 à 17 29 36](https://user-images.githubusercontent.com/48314202/66206645-f6289c80-e6b0-11e9-9f22-7c0825002f1e.png)

**Comment by flecaignard** [comment]
I can send a link to the data via email (clinical data)
thanks+++

**Comment by samuelgarcia** [comment]
I take it.
