### ISSUE TITLE
block.list_children_by_class empty array_annotations

### ISSUE THREAD

**Issue by dizcza** [NeuralEnsemble/python-neo#749]
In https://github.com/INM-6/elephant/blob/neo-v0.8.0/elephant/test/test_neo_tools.py#L621 

```python
obj = self.block.list_children_by_class('Event')[0]
targ = get_fake_values('Event', seed=obj.annotations['seed'])
```

`obj.array_annotations` is an empty ArrayDict of size 13, but it should return the same dict as in `targ['array_annotations']`.

The other thing is that their lengths mismatch. To fix both issues, we make

```python
        num_times = len(targ['times'])
        obj = obj[:num_times]
        del targ['array_annotations']
```

Please confirm that this is an issue and not incorrect usage of neo in Elephant.

Update.
This might relate to https://github.com/NeuralEnsemble/python-neo/pull/656

**Comment by apdavison** [comment]
I think this is an issue with the Neo tests, and the way `get_fake_values()` works, rather than with the `list_children_by_class()` method.

Example:
```
import neo
ev = neo.Event([1, 2, 3, 4, 5], units="ms", labels=["a", "b", "c", "d", "e"])
seg = neo.Segment()
seg.events.append(ev)
ev.segment = seg
b = Block()
b = neo.Block()
b.segments.append(seg)
seg.block = b
ev.array_annotate(category=[1, 2, 2, 1, 1])
ev2 = b.list_children_by_class('Event')[0]
```

`ev2.array_annotations` --> `{'category': array([1, 2, 2, 1, 1])}`

I'll leave this open to check when we refactor the Neo testing framework.

**Comment by samuelgarcia** [comment]
get_fake_values was removed.
