### ISSUE TITLE
BlackrockIO: Selection of files to load

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#759]
The RawIO implementation of the BlackrockIO takes only a single argument specifing the set of files to be loaded, defined by the common naming scheme. However, sometimes it is necessary to use an accompanying file which does not match the strict naming scheme, e.g. loading session `<session_name>.ns2` together with `<session_name>-01.nev`. How can this be achieved using the RawIO mechanism? Is there a way to extend the interface to cover this case or should two separate IOs be instantiated in this case?

**Comment by samuelgarcia** [comment]
Does ths **nsx_override** or **nev_override** can do the job ?

**Comment by JuliaSprenger** [comment]
I didn't know this was present at the RawIO level. From the BlackRockIO itself these arguments are not visible, so I missed it. Thanks, this should solve the issue!

**Comment by samuelgarcia** [comment]
I hope it works because I nerver tested it.
But I remember to try porting all thing you needed like this one.

At neo.ioBlackrockIO lebel **kargs should pass all argument to BlacrockrawIO.
