### ISSUE TITLE
Problem importing TDT tank

### ISSUE THREAD

**Issue by Gittinator** [NeuralEnsemble/python-neo#765]
I am trying to import a TDT TTank into Neo, and I'm running into an ambiguous error. It's attached. I tried to debug, and it looks like what is happening in the tdtrawio file is that "data_index" is empty, because the mask on tsq used to create it is all False. I'm having trouble figuring out what could be causing that though.

The relevant code is just: r = io.TdtIO(tank_path)

<img width="722" alt="Screen Shot 2019-11-13 at 5 03 44 PM" src="https://user-images.githubusercontent.com/2263921/68808504-e00ae600-0637-11ea-8698-c77c085d80f1.png">

**Comment by samuelgarcia** [comment]
Hi thank you for the report.
Could you send the file please, so I could help you help to debug this.
Yes the data_index seams empty, does it make sense ?
What do you with tdt software about data size ?

**Comment by apdavison** [comment]
@Gittinator do you have an example you can send us, to help debug this problem?

**Comment by zm711** [comment]
Let's close this. @Gittinator, feel free to reopen if you try to use this again in the future and run into the same issue.
