### ISSUE TITLE
Error loading NeoMatlab file

### ISSUE THREAD

**Issue by xabiben** [NeuralEnsemble/python-neo#768]
Dear colleagues,
I am trying to create a backup file with my electrophysiological recordings using neo. I decided to use NeoMatlabIO to create .mat files (not sure if there is a better option).
Files are big, so it is difficult to share an example. However, files are successfully created, as I can read them in Matlab.

The problem comes when I try to read the files in Python again. It rises the following message: 

 File "<ipython-input-12-c8298ac30bcc>", line 1, in <module>
    seg2 = r2.read_block().segments[0]
  File "E:\Users\Xabi\Anaconda3\envs\ephys\lib\site-packages\neo\io\neomatlabio.py", line 235, in read_block
    bl_struct, 'Block')
  File "E:\Users\Xabi\Anaconda3\envs\ephys\lib\site-packages\neo\io\neomatlabio.py", line 362, in create_ob_from_struct
    classname_lower_to_upper[attrname[:-1]])
  File "E:\Users\Xabi\Anaconda3\envs\ephys\lib\site-packages\neo\io\neomatlabio.py", line 362, in create_ob_from_struct
    classname_lower_to_upper[attrname[:-1]])
  File "E:\Users\Xabi\Anaconda3\envs\ephys\lib\site-packages\neo\io\neomatlabio.py", line 394, in create_ob_from_struct
    item = item.astype(dt)
AttributeError: 'str' object has no attribute 'astype'

I don't get whats going wrong. Can somebody guide me about this error? Apparently, in the structure of the file there is something that neo is not able to deal appropriately with. I guess it could be some class problem inside the annotations, names or something like that (that is, the parts of the object that are actually strings).

Sorry for not being more clear in my explanation. I have tried to code an artificial example of my file, but it runs perfectly, not reproducing the problem.

UPDATE:
Ok, apparently the problem comes when dealing with the events stored in the segment. As soon as I remove them, I can read the file. This is how the events look like:

[Event name: 'TTL_049_flag1' annotations: {'id': '16'},
 Event name: 'TTL_050_flag1' annotations: {'id': '17'},
 Event name: 'TTL_051_flag1' annotations: {'id': '18'},
 Event name: 'Board1_Port203' annotations: {'id': '71'},
 Event name: 'TTL_049' annotations: {'id': '72'},
 Event name: 'TTL_050' annotations: {'id': '73'},
 Event name: 'TTL_051' annotations: {'id': '74'}]

**Comment by samuelgarcia** [comment]
dear Xabi,
thank you to report this.

NeoMatlabIO is not the best option to save a neo tree in a file. It support only some features.
In particular ChannelIndex, annotation, array_annotation are not saved.

It still be usefull to retrieve signals, spikes and events in matlab ecosystem and use neo as a "converter".

To save a full neo tree, NixIO is you best friend but you need to install the very last beta release of nix  iopython package for this.

About the bug, of event in matlabio, I could try to fix it, could you send me a piece of code that trigger this bug ?

Best,

Samuel

**Comment by xabiben** [comment]
Thank you for the suggestion, @samuelgarcia. I will use the NixIO format instead.

It took me a while but I have written a little script that reproduces the error. I had to play around the Event I was creating to have the exact attributes as my original files. There is a fancy line of code there for that purpose. 

```
import neo
from neo.io import NixIO, NeoMatlabIO
import quantities as pq
from scipy import rand, array

bl = neo.Block(name='my block with neo')
seg = neo.Segment()

for a in range(5):
    anasig = neo.AnalogSignal(rand(100)*pq.mV, t_start=0*pq.s,
                              sampling_rate=100*pq.Hz)
    seg.analogsignals.append(anasig)
for t in range(7):
    sptr = neo.SpikeTrain(rand(40)*pq.ms, t_start=0*pq.ms, t_stop=10*pq.ms)
    seg.spiketrains.append(sptr)

ev = neo.Event([10]*pq.s, name = 'event1', labels=array([b''], dtype = '|S1'))
ev.annotations = {'id': '15'} # this line is to reproduce the format in which the
#annotations of the event are imported from my NeuroExplorer file. If you
#embed the annotations in the previous function it does not store the same 
#thing. I guess that either the NueuroExplorerIO importer or the NeoMatlabIO
#exporter might have the mistake.

seg.events.append(ev)
bl.segments.append(seg)   

w = NeoMatlabIO(filename='myblock.mat')
w.write_block(bl)

#the error is raised now, when you try to reload the data
r = NeoMatlabIO(filename = "myblock.mat")
bl2 = r.read_block()
```

Interestingly, when you use NixIO format it does not give the error when realoading. 

Thank you for all for your excellent work.

Xabier

**Comment by samuelgarcia** [comment]
Thank you for the code.
I will have a look.
Achilleas wroked a lot on NixoIO to make it robust.
MatlabIO is old code done by me and not so mush maintened over time.
I will try to improve it.

**Comment by samuelgarcia** [comment]
Hi @xabiben 
Sorry for the ultra long delay.

Now for event "labels" are supposed to be unicode so with dtype 'U'

So if you change to this:
```python
ev = neo.Event([10]*pq.s, name = 'event1', labels=np.array([''], dtype = 'U'))
```

your script is working. COuld you check so I could close this ?

**Comment by apdavison** [comment]
Hi @xabiben - a quick reminder - please could you check whether @samuelgarcia's fix works for you? Many thanks.

**Comment by JuliaSprenger** [comment]
I close this now. If you still experience issues, please reopen.
