### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/python-neo#769]
I just noticed that with Neo 0.8.0 the dependencies list in [``requirements.txt``](https://github.com/NeuralEnsemble/python-neo/blob/82b9600973f0ed092bbb13f2b5880a0c5e55ec04/requirements.txt#L2-L3) was update to newer versions of numpy and quantities, but [``setup.py``](https://github.com/NeuralEnsemble/python-neo/blob/82b9600973f0ed092bbb13f2b5880a0c5e55ec04/setup.py#L8-L9) was not. The [docs](https://neo.readthedocs.io/en/0.8.0/install.html) were updated to match ``requirements.txt``, but ``setup.py`` is the one that pip really cares about.

Should ``setup.py`` be updated too?

**Comment by apdavison** [comment]
yes, we missed that.
