### ISSUE TITLE
[NixIO] Error for datetime annotations

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#783]
Saving a neo block structure that contains an annotation of type datetime (date/time) results in a `ValueError`. E.g.
```python
from neo import NixIO, Block
import datetime

b = Block(custon_date=datetime.date.today())
with NixIO('test.nix','ow') as io:
    io.write_block(b)
```
causes `ValueError: Unknown type for value 2019-12-10`.
However, datetime objects are a supported annotation object type within neo, see 
https://github.com/NeuralEnsemble/python-neo/blob/a9ac68db3a2bfdc6b8f0d96237e091e7772610ed/neo/core/baseneo.py#L20
and are frequently generated when loading datasets with other IOs.

**Comment by achilleas-k** [comment]
https://github.com/NeuralEnsemble/python-neo/blob/a9ac68db3a2bfdc6b8f0d96237e091e7772610ed/neo/io/nixio.py#L1164-L1165

This should be taking care of converting datetime objects to a timestamp integer for storage in NIX.  Unfortunately, it doesn't cover date or time objects (only the combo), so I'll need to fix that.

One more issue though is that date, time, and datetime values aren't converted back on read.  It doesn't add any information about the original type.  I should probably add some information to the property that the NIXIO reader uses on load to initialise the correct types, like it does for quantities and arrayannotations.

**Comment by achilleas-k** [comment]
Looks like I had already worked on something like this a few months ago and the branch got forgotten.  Opened PR now.  Can you test please?
