### ISSUE TITLE
Change dtype of neo.core.AnalogSignal

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/python-neo#794]
Hello there!

I wanted to change the dtype of my analogsignals from `float64` to `float32` and could not figure out a way to do it without creating a new object.

Given an analogsignal object `anasig`, I currently do:
```
    new_anasig = neo.core.AnalogSignal(anasig.magnitude.astype('float32'),
                                       units=anasig.units,
                                       sampling_rate=anasig.sampling_rate)
    new_anasig.array_annotations = anasig.array_annotations
```

Is there a better, more memory efficient way? In place would be ideal. The magnitude could maybe inherit the method from numpy.ndarray somehow. 

Let me know your thoughts.

Thanks,
Aitor

**Comment by rgutzen** [comment]
Apparently, this works
`anasig.dtype = np.float32`

**Comment by morales-gregorio** [comment]
Oh wow, I feel quite stupid now hehehe. 

Awesome!
