### ISSUE TITLE
Updates to Blackrock File Format (3.0)

### ISSUE THREAD

**Issue by NickHalper** [NeuralEnsemble/python-neo#795]
Blackrock is expecting a change to our file format in an upcoming release (I think at least a couple of months away), so I wanted to reach out to you to make sure it is on your radar for incorporation into neo. As always, we will allow people access to our previous file formats, and the adoption will be slow, so this would be supported in addition to the current ones that you load. 

The primary change is a move to 64 bit timestamps. The other change is the inclusion of an additional event type in our Neural Events File: an indicator for the recording pausing, resuming, and stopping. 

We can provide the file spec as soon as it is all signed off on our side, which should be in just a couple of weeks, but I just wanted to throw this in here so that it could be planned on. 

Let me know if there is anything else you'll need from me besides example files.

**Comment by JuliaSprenger** [comment]
Hi @NHalper!
Thanks for the heads-up. That's very good to know. Keep us updated as soon as the specifications are set and example files are available. Thanks!

**Comment by NHalper** [comment]
Definitely. I will update this thread with them as soon as they are ready.

**Comment by JuliaSprenger** [comment]
Hi @NickHalper! Any updates about this in the meantime?

**Comment by NickHalper** [comment]
Julia, I actually no longer work at Blackrock Microsystems, so I am not
sure of their current release schedule. Sorry about that!

**Comment by JuliaSprenger** [comment]
@NickHalper Can you then maybe link someone else from the Blackrock team here?
