### ISSUE TITLE
missing t_start attribute of ImageSequence objects

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/python-neo#799]
Contrary to the other objects, ImageSequence has only relative timing, i.e. a sampling rate between image frame, but no starting or stopping time to align it also to other objects.
Is there a particular reason for this?
Otherwise, I would think ImageSequence should have an optional `t_start` attribute which defaults to `0*pq.ms`, similar to AnalogSignal (which would also facilitate their potential mapping, see #745).

**Comment by samuelgarcia** [comment]
I agree.
ImageSequence inherits BaseSignal, I would except that t_start would be handle there but it is not the case.
@apdavison  ?

**Comment by apdavison** [comment]
yes, I think it should be there, that was an oversight on my part

**Comment by samuelgarcia** [comment]
It is out maybe because irregularysampledsignal.
I don't remember.
