### ISSUE TITLE
Write neo (analogsignals) and read with lazy mode

### ISSUE THREAD

**Issue by TRuikes** [NeuralEnsemble/python-neo#812]
I've got 128 downsampled analogsignals, which I'd like to write on a drive, and in the future interact with trough lazy reading. Through which IO is this possible?

The combined size of the channels is still too large to load at once into memory. Ideally it would be something where I write all the signals into one file, and then can read parts of it just as you already have implemented it the current read/lazy methods, but I can't figure out which IO I need to save the data.

**Comment by jpgill86** [comment]
Hi @TRuikes,

I think your only option is [RawBinarySignalIO](https://neo.readthedocs.io/en/stable/io.html#neo.io.RawBinarySignalIO).

```python
>>> import neo
>>> from neo.rawio.baserawio import BaseRawIO
>>> for io in neo.iolist:
>>>     if io.is_writable and io.support_lazy:
>>>         print(io)
<class 'neo.io.rawbinarysignalio.RawBinarySignalIO'>
```

**Comment by TRuikes** [comment]
Allright! I think this one is WIP aswell. I'll use [h5 for now](https://github.com/TRuikes/python-neo/blob/hacks_thijs/neo/io/lazyanalogsigio.py).

**Comment by TRuikes** [comment]
I found my answer (Nixio in combination with NixioFr can do it) in #786, in case anyone ends up here!
