### ISSUE TITLE
SpikeIO does not load .smr

### ISSUE THREAD

**Issue by weltgeischt** [NeuralEnsemble/python-neo#818]
Dear Neo developers,
I can not load some of my .smr files with Spike2IO. I work with **python 3.5.2** and tried Neo versions **0.8.0** and **0.9.0.dev**. The error message is: “_IndexError: index 0 is out of bounds for axis 0 with size 0_”.
Note that I got the same error for some other  .smr files and could resolve this by using try_signal_grouping=False, however, the issue persists for some other .smr files. 
You can download an example file here: https://www.dropbox.com/s/hqgs4biuf5bm237/EP147-148-150-154_44d000.smr?dl=0
This file contains several channels (e.g. 'HCi1') of LFP recordings.

The code to reproduce the error:

from neo.io import Spike2IO
r = Spike2IO(filename='myfilename.smr',try_signal_grouping=False)

Thank you very much for your support.

**Comment by samuelgarcia** [comment]
Thank for the report, I will have a look.

**Comment by weltgeischt** [comment]
Hi Samuel,
sorry to bother you again. Did you already find out why the .smr loading
does not work? We rather urgently need to analyze this data because a
resubmission deadline is looming.
Greetings,
Katharina

Am Mi., 20. Mai 2020 um 19:12 Uhr schrieb Garcia Samuel <
notifications@github.com>:

**Comment by samuelgarcia** [comment]
Hi Katharina,
sorry for the delay.
I had a look to the file and it seems strange. The data block index are totally illogical for the file.
Is it the only file like this ?
Is a smrx (next spike2 version) in fact ?

Samuel

**Comment by weltgeischt** [comment]
Hi Samuel,
thank you for your response. I just asked my colleague who records the data
and thats what she said:
1) She encountered this error for about half of her files (so about 50, I
guess)
2) She *did not use a different version of spike2* than for the files she/I
could open
3) BUT She *configured spike2 to "big file"* so she does not have to start
a new recording after 2GB are full.
So I guess it might have something to do with the "big file" configuration.
-- Can Neo deal with this?
Thank you for your help and have a nice weekend,
Katharina


Am Fr., 5. Juni 2020 um 21:22 Uhr schrieb Garcia Samuel <
notifications@github.com>:

**Comment by weltgeischt** [comment]
to be clear for 3) She configured to big-file after she had already
recorded some other recordings. So the issue might be really with big file.

Am Sa., 6. Juni 2020 um 16:04 Uhr schrieb Katharina Heining <
katharina.heining@bcf.uni-freiburg.de>:

**Comment by samuelgarcia** [comment]
Yes. I think this is the case.
Unfortunatly, this big file is not handle in neo now.
I would be happy to code it but I would need a format specification from the manufacturer.
Could you contact then ?
I would also need a small file of this type to implement test.

**Comment by brandonStell** [comment]
I'm new to neo (and spike2) and am also having trouble loading a .sml: https://filesender.renater.fr/?s=download&token=56c8574e-d9c3-4719-84d5-c981bdfa7563

```python
import neo
reader = neo.io.Spike2IO(filename='/home/bs/Documents/DATA/decerebrate/raw_recordings/20200527_Cell408_000.smr')
```

 ```python
Traceback (most recent call last):
  File "/home/bs/anaconda3/envs/data/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d7be200c8001>", line 1, in <module>
    runfile('/home/bs/repositories/decere/Spike2Analysis.py', wdir='/home/bs/repositories/decere')
  File "/snap/pycharm-professional/201/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/201/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/bs/repositories/decere/Spike2Analysis.py", line 3, in <module>
    reader = neo.io.Spike2IO(filename='/home/bs/Documents/DATA/decerebrate/raw_recordings/20200527_Cell408_000.smr')
  File "/home/bs/anaconda3/envs/data/lib/python3.8/site-packages/neo/io/spike2io.py", line 10, in __init__
    BaseFromRaw.__init__(self, filename)
  File "/home/bs/anaconda3/envs/data/lib/python3.8/site-packages/neo/io/basefromrawio.py", line 74, in __init__
    self.parse_header()
  File "/home/bs/anaconda3/envs/data/lib/python3.8/site-packages/neo/rawio/baserawio.py", line 149, in parse_header
    self._parse_header()
  File "/home/bs/anaconda3/envs/data/lib/python3.8/site-packages/neo/rawio/spike2rawio.py", line 102, in _parse_header
    block_info = self._memmap[ind:ind + 20].view(blockHeaderDesciption)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Any suggestions would be greatly appreciated.

**Comment by MarinManuel** [comment]
Hi @samuelgarcia 
I've looked in the documentation for the CED SON library (http://ced.co.uk/upgrades/spike2tools). It seems the offsets have changed for v9 Spike2 files.

> **TDOF** This type is defined for use as Type Disk OFfset. It holds all references to positions in the data file. It is defined as typdef long TDOF; though for testing purposes in a C++ environment it can be advantageous to define it as an opaque type to detect all attempts to do maths with it. In version 9 and above files, if pos is of type TDOF, the disk offset is pos*DISKBLOCK. In version 8 and previous files, the disk offset is pos. We also define TDOF64 internally for use as a 64-bit disk offset.

I've added a check for v9 files, and adjusted the offsets accordingly. As far as I can tell, that is enough to allow reading @weltgeischt 's file above. However, there is another problem with @brandonStell 's file that's unrelated and that seem to be caused by some non-ascii characters in the channel names, but I did not have time to dig deeper

**Comment by MarinManuel** [comment]
I may have fixed the issue with the non-ascii char. I've included it in the PR. I'd be happy to provide some v6 and v9 files for a test case. Unfortunately, I don't know really know how to write unit tests

**Comment by weltgeischt** [comment]
Hi Samuel,
1) my colleague has asked the Spike2 people about the format specification
and is still awaiting an answer.
2) here you can find a very small file saved with the bigfile configuration
for testing:
https://www.dropbox.com/s/b2qp5lpq856g0ro/Enya%20Paschen%20%20-%20Two-mice-bigfile-test000.smr?dl=0
Thank you very much for your efforts and have a nice weekend,
Katharina

Am Mo., 8. Juni 2020 um 09:32 Uhr schrieb Garcia Samuel <
notifications@github.com>:

**Comment by MarinManuel** [comment]
@weltgeischt I think the PR i pushed yesterday works to open your file.
![Figure_1](https://user-images.githubusercontent.com/65401298/84588137-12c2ca00-ae25-11ea-9f9c-8a5021ef87dc.png)

**Comment by brandonStell** [comment]
Thanks a lot @MarinManuel !  This is working fine for me.  
@samuelgarcia any chance of merging this to master or should I keep working with the PR for now?

**Comment by weltgeischt** [comment]
The new PR did the trick for me too, thank you!

**Comment by samuelgarcia** [comment]
I f it works for all.
I can merge quite soon.
Let me first add the file test in gin.gnode and add this file in tests first.
