### ISSUE TITLE
Error in loading Micromed data: UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12

### ISSUE THREAD

**Issue by ShirinNajdi** [NeuralEnsemble/python-neo#821]
Hi,

I encountered an error trying to load .trc data recorded with Micormed system using neo. Here is the error:

`seg = reader.read_segment(lazy=False)`
`e = e.load(time_slice=time_slice, strict_slicing=strict_slicing)`
`t_start=_t_start, t_stop=_t_stop)`
`block_index, seg_index, event_channel_index, t_start, t_stop)`
`labels = raw_event['label'].astype('U')`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)`

Would you please let me know how can I solve it? 
Interesting point is that this error only happens with some of the .trc files from the database.

**Comment by ShirinNajdi** [comment]
Can anybody suggest a solution for this problem?

**Comment by JuliaSprenger** [comment]
Hi @ShirinNajdi,
could you give the full traceback of the error and provide minimal code on how you load the data? There are some inconsistencies in your code that make it more complicated to understand what parts of the code you are actually running.
Also if you are able to provide a tiny .trc file which already causes the error, this could help debugging here.

**Comment by samuelgarcia** [comment]
Hi @ShirinNajdi,
if you don't have restriction about data pricacy would it be possible to send us the this file ?

**Comment by ShirinNajdi** [comment]
Hi.

This is the part of code that I am using for reading the data:

`from neo.io import MicromedIO`
`reader = MicromedIO(filename=database_path)`
`seg = reader.read_segment(lazy=False)`

The following is the error that I get:

`Traceback (most recent call last):`
 `File " windowing.py", line 32, in _read_trc`
 `seg = reader.read_segment(lazy=False)`
 `File "~/Library/Python/3.6/lib/python/site-packages/neo/io/basefromrawio.py ", line 293, in read_segment`
 `e = e.load(time_slice=time_slice, strict_slicing=strict_slicing)`
` File "~/Library/Python/3.6/lib/python/site-packages/neo/io/proxyobjects.py", line 425, in load
    t_start=_t_start, t_stop=_t_stop)`
`File "~/Library/Python/3.6/lib/python/site-packages/neo/rawio/baserawio.py", line 571, in get_event_timestamps
    block_index, seg_index, event_channel_index, t_start, t_stop)`
` File "~/Library/Python/3.6/lib/python/site-packages/neo/rawio/micromedrawio.py", line 221, in _get_event_timestamps
    labels = raw_event['label'].astype('U')`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)`



I cannot share the data because of the privacy restrictions but I can explain exactly what is happening in micromedrawio.py in line 221 that causes an error:

Normally the `raw_event['label']` that arrives to line 221 is like this: 
`array([b'* * * Part 1 * * *', b'START deel 1 waak', b'diffuus veel Beta',
       b'Ogen open', b'Ogen dicht', b'7-8/sec re>li', b'Start HV',
       b'aansporing', b'HV 30 sec', b'HV 60 sec', b'HV 90 sec',`

But the problamatic files have `raw_event['label']` like the following:
`array([b'start waak\x00tton', b'Ogen dicht\x00tton', b'beta amp re>li',
       b'mu\x00a amp re>li', b'Ogen open\x00e>li',
       b'Start HV\x00\x00e>li', b'mu C4\x00HV\x00\x00e>li',`


Hope this can explain what is the problem!

**Comment by samuelgarcia** [comment]
Thank you. This help.

In micromed there is 4 events channel with diffrents internal dtypes: 
```
('TRIGGER', [('start', 'u4'), ('label', 'u2')]),
('NOTE', [('start', 'u4'), ('label', 'S40')]),
('EVENT A', [('label', 'u4'), ('start', 'u4'), ('stop', 'u4')]),
('EVENT B, [('label', 'u4'), ('start', 'u4'), ('stop', 'u4')]),
```
I think that it is  "NOTE" channel with S40 dtype for label.
**\x00** should be the terminating char but in that file there are extra char after it.
What do you see in the micromed software when you open this file ?

**Comment by ShirinNajdi** [comment]
@samuelgarcia I don't have access to Micromed system, I am working with data exported from this system. However I asked this question from data providers and I'm waiting for their reply.

**Comment by samuelgarcia** [comment]
Maybe #873 is fixing this.
Could you try it please ?

**Comment by JuliaSprenger** [comment]
I am closing this issue now. @ShirinNajdi Please comment again, if you are still interested.
