### ISSUE TITLE
Add validator to ensure neo structure is rawio compatible

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#828]
This idea was developed in #626.

The validator can be used to ensure a saved neo structure can be loaded with a rawio.
It should be part of `neo.utils`. Besides providing a boolean feedback, it might also indicate to the user the structural parts that are not consistent with the rawio requirements.

**Comment by JuliaSprenger** [comment]
Aspects that should be covered are
- consistent channels across segments
- array annotations can only be basic (default) annotations like channel_id, that are recognized on rawio level as array annotation type
- consistent linking between objects (bidirectional where possible)
- any more ideas?

**Comment by apdavison** [comment]
Implemented in #839
