### ISSUE TITLE
[Bug] neo.SpikeTrain.time_slice() should not work outside the original t_start and t_stop

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/python-neo#831]
Hey,

Was slicing some data and realized that the `neo.SpikeTrain.time_slice()` can take **any** times in and will return a `neo.SpikeTrain`, so even if one is outside of the range it will give you an empty spiketrain.

In my use case however, not all spiketrains "exist" at all times, meaning that because of some acute probe moved a unit was lost. So in principle the neuron is not just silent for the rest of the time, we just do not know what is doing. And the slicing function as it is now assumes silence.

I would suggest to either:
* throw an error,
* return an `np.nan` with a warning
* or return a `None` with a warning.

It can also be especially useful for slicing whole segments as well!

Let me know if you think this is meaningful and I create a PR if needed :)

Cheers,
Aitor

**Comment by morales-gregorio** [comment]
I was just going through the code again and noticed it is even worse 😅. Actually you can get a spiketrain back that has `st.t_start` > `st.t_stop`, which I believe should never happen.

I will look into it already and relabel the issue as a bug 🐞

**Comment by apdavison** [comment]
Hi @morales-gregorio I didn't read carefully enough, and didn't see your offer to create a PR until after I'd created one myself!

Please could you take a look at #867?

**Comment by morales-gregorio** [comment]
No probs! I can have a look at the PR :)
