### ISSUE TITLE
Support graphical representation of object structure

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#835]
Getting an overview of the objects within a Neo structure is often a hurdle for people starting to use Neo. Here, a graphical representation might provide intuitive help.
A representation of a specific Neo structure could provided on a descriptive level, e.g. using the `DOT` graph description language. This can then be rendered using `Graphviz`.

This would, similar to #756, require a standardised text representation of each Neo object as a graph node.

**Comment by zm711** [comment]
I think this is done, but if you meant something other than what we currently have just reopen.
