### ISSUE TITLE
Default type of AnalogSignal units is wrong

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#843]
Describe the bug
AnalogSignal init has units=None
However Quantity has units=''

To Reproduce
import neo
import numpy
import quantities
signal = numpy.asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
a = neo.AnalogSignal(signal, sampling_period =1 * quantities.ms)

**Comment by JuliaSprenger** [comment]
Hi @Christian-B,
could you be a bit more specific about the error? I think that with the minimal example above you should receive an `ValueError: Units must be specified` as the signal requires either units to be specified or needs to be a quantity itself.

**Comment by Christian-B** [comment]
The error is that AnalogSignal init has a default value for the units parameter so your claim "Units must be specified" is INCORRECT!

The problem is that this default is None while the underlying quantity uses the empty string to specify no unit.

**Comment by JuliaSprenger** [comment]
Hello again,
which version of neo are you using? I have been testing your example with version `0.8.0` and still can't reproduce your error. If I see this correctly, this [check](https://github.com/NeuralEnsemble/python-neo/blob/c9e5829f3209f65bdd0a3100dbb7666f1ce41ec8/neo/core/basesignal.py#L94) was introduced 3 years ago and should be present in all versions released since then.

**Comment by Christian-B** [comment]
I am using neo 0.6.0 but having checked the error is in current master!
Look at
https://github.com/NeuralEnsemble/python-neo/blob/c9e5829f3209f65bdd0a3100dbb7666f1ce41ec8/neo/core/analogsignal.py#L199
and
https://github.com/python-quantities/python-quantities/blob/a15e9fc71d54ace1827759f18a3b1901088983fd/quantities/quantity.py#L122

1. The first allows the user not to specify units so do not claim "Units must be specified" as that claim does not match the code!
2. As you say if you pass that default None into the qunatities it will give you a ValueError

The bug is that the value your code puts in if the user chooses (as he is allowed to ) not to specify units is INCORRECT!

**Comment by Christian-B** [comment]
The check which blows up if the default code your code puts in is just BAD PROGRAMMING!

**Comment by Christian-B** [comment]
Once again the correct default value for AnalogSignal units is the EMPTY STRING!

**Comment by apdavison** [comment]
Dear Christian,

Your use of words in all uppercase, and ending every post with an exclamation mark, comes across as very aggressive. I hope that was not your intention. 

When I enter your example:
```
import neo
import numpy
import quantities
signal = numpy.asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
a = neo.AnalogSignal(signal, sampling_period =1 * quantities.ms)
```

I get
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f125b975a203> in <module>
      3 import quantities
      4 signal = numpy.asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
----> 5 a = neo.AnalogSignal(signal, sampling_period =1 * quantities.ms)

~/dev/analysis/neo/neo/core/analogsignal.py in __new__(cls, signal, units, dtype, copy, t_start, sampling_rate, sampling_period, name, file_origin, description, array_annotations, **annotations)
    181         __array_finalize__ is called on the new object.
    182         '''
--> 183         signal = cls._rescale(signal, units=units)
    184         obj = pq.Quantity(signal, units=units, dtype=dtype, copy=copy).view(cls)
    185

~/dev/analysis/neo/neo/core/basesignal.py in _rescale(self, signal, units)
     93         if units is None:
     94             if not hasattr(signal, "units"):
---> 95                 raise ValueError("Units must be specified")
     96         elif isinstance(signal, pq.Quantity):
     97             # This test always returns True, i.e. rescaling is always executed if one of the units

ValueError: Units must be specified
```

This is with the current master branch. As a check, I also created a new virtualenv with Neo 0.6.0 and Python 2.7, and the same ValueError is raised.

The `units` argument is a rather complex one, as it may or may not be required, depending on the value of the other arguments (if the signal is a Quantity array, it is not required, if the signal is a plain NumPy array, it is required). This is explained in the docstring.

Have I understood correctly that you are saying the constructor signature of a subclass should not have different default values from those of the parent class?

**Comment by Christian-B** [comment]
Yes I am saying the constructor signature of a subclass should not have different default values from those of the parent class?

The example code works if I add a parameter units = empty string.
This will result in the units being "dimensionless"

**Comment by apdavison** [comment]
> Yes I am saying the constructor signature of a subclass should not have different default values from those of the parent class?

In general, I would agree with you, as it makes the behaviour more predictable. However, in this case we do not wish to use the same default value as `quantities` (i.e. dimensionless), we want to force the user to explicitly choose units. This is a central design decision of Neo, aimed at reducing errors in user code.

> The example code works if I add a parameter units = empty string.

Yes, or alternatively `a = neo.AnalogSignal(signal * quantities.dimensionless, sampling_period =1 * quantities.ms)`

As I noted above, the default value of `units` is _"the same as the units of the signal, if the signal is a Quantity array"_. This cannot be expressed in a Python method signature, therefore we use `units=None` and do further checking in the body of the method.
