### ISSUE TITLE
nixio.py requiring version not in the PyPi repository

### ISSUE THREAD

**Issue by PeterNSteinmetz** [NeuralEnsemble/python-neo#844]
nixio.py now requires nixio package at version 1.5.0 or higher. But the latest version in the PyPi repository is 1.4.9. 

So using standard downloads, the tests for nixio fail.

**Comment by JuliaSprenger** [comment]
Hi @PeterNSteinmetz!
Thanks for the report. Which version of Neo are you working with? For version 0.8.0 and master nixio should only be installed upon request `pip install neo[nixio]` only. This way also beta versions of the nixio should be taken into consideration like the current nixio [1.5.0b6](https://pypi.org/project/nixio/1.5.0b6/).
To achieve the same when manually installing the nixio you would need to permit pip to consider beta versions via `pip install --pre nixio`.

**Comment by PeterNSteinmetz** [comment]
I am building neo from source using 'python setup.py build', with the latest tip of the master branch. I tried 'pip install --pre nixio' and it did not bring in the 1.5.0b6.

**Comment by achilleas-k** [comment]
If nixio is already installed, you need to also specify `--upgrade`:
`pip install --upgrade --pre nixio`

Alternatively, you can specify the version with `pip install nixio==1.5.0b6`.

**Comment by PeterNSteinmetz** [comment]
Thanks. The --upgrade did the trick.
