### ISSUE TITLE
Loss of some metadata when converting from .abf to binary raw binary data using io.RawBinarySignalIO()

### ISSUE THREAD

**Issue by shw3ta** [NeuralEnsemble/python-neo#845]
While converting .abf to .raw using the RawBinarySignalIO() class, the header of the file that has been written to retains almost all the information, except for some info I need to be retained such as the signal channel units. Is there any way to fix this? I tried adding this missing info in the correct location in the header dict, but it doesn't work.

For comparison, here is the result of printing `reader.header['signal_channels']['units']` and `reader.header` for the .abf file:

`['mV' 'V'] `
`{`
 `'nb_block': 1,`
` 'nb_segment': [1],`
` 'signal_channels': array([('Vm2', 0, 10000., 'int16', 'mV', 0.00030518, 0., 0), ('IN6', 1, 10000., 'int16', 'V', 0.00030518, 0., 0)],  dtype=[('name', '<U64'), ('id', '<i8'), ('sampling_rate', '<f8'), ('dtype', '<U16'), ('units', '<U64'), ('gain', '<f8'), ('offset', '<f8'), ('group_id', '<i8')]), `
`'unit_channels': array([], dtype=[('name', '<U64'), ('id', '<U64'), ('wf_units', '<U64'), ('wf_gain', '<f8'), ('wf_offset', '<f8'), ('wf_left_sweep', '<i8'), ('wf_sampling_rate', '<f8')]),`
` 'event_channels': array([('Tag', '', b'event')], dtype=[('name', '<U64'), ('id', '<U64'), ('type', 'S5')])`
`}
`

And here is the result of printing `reader.header['signal_channels']['units']` and `reader.header` for the .raw file obtained after conversion:

`['' '']`
`{`
` 'nb_block': 1,`
`'nb_segment': [1], `
` 'signal_channels': array([('ch0', 0, 10000., 'float32', '', 1., 0., 0), ('ch1', 1, 10000., 'float32', '', 1., 0., 0)], dtype=[('name', '<U64'), ('id', '<i8'), ('sampling_rate', '<f8'), ('dtype', '<U16'), ('units', '<U64'), ('gain', '<f8'), ('offset', '<f8'), ('group_id', '<i8')]),` 
`'unit_channels': array([], dtype=[('name', '<U64'), ('id', '<U64'), ('wf_units', '<U64'), ('wf_gain', '<f8'), ('wf_offset', '<f8'), ('wf_left_sweep', '<i8'), ('wf_sampling_rate', '<f8')]), `
`'event_channels': array([], dtype=[('name', '<U64'), ('id', '<U64'), ('type', 'S5')])`
`}
`

Your help will be very appreciated!
Shweta

**Comment by samuelgarcia** [comment]
Unfortunatly the RawBinarySignalIO that handle binary neutral format don't have any way of dealing with metadata offcially.
In short the format itself do not handle anything.
sampling rate, channel count, units, gains, dtype have to be handle externally and explicitly.
So we can't do anything in neo.

**Comment by JuliaSprenger** [comment]
@shw3ta if you are looking for a format to write to that preserves metadata you might want to look at the NixIO.

**Comment by shw3ta** [comment]
Thank you, I did end up using NixIO.
