### ISSUE TITLE
Grouping objects for hierarchy in simulated results

### ISSUE THREAD

**Issue by Helveg** [NeuralEnsemble/python-neo#860]
Hi! I'm looking into the neo package to use in a project similar to PyNN and the bmtk; we generate various simulated signals that fit well into the available data objects. The Grouping objects however seem very focussed on the experimental side of things. There for example seem to be no grouping objects to clump together sets of AnalogSignals of neurons of let's say the same population. 

I could for sure use the `annotations` to label them and then iterate over the labels to fish them out, but it would look a lot cleaner if I could transfer the hierarchy in my simulation output into Neo using some generic grouping object that makes it easier to take out objects together.

Does something like this already exist, or how would you recommend dealing with this?

**Comment by apdavison** [comment]
If you're only recording from a single location per neuron (e.g. the soma) I would use a single, multi-channel AnalogSignal to store the signals from the entire population (1 neuron = 1 channel). If you're recording from many locations for each neuron (soma, dendrites, etc.) then you'd probably want one AnalogSignal per neuron (1 channel per recording location).

In this second scenario, what you probably need is the new generic Group object that will be available in Neo 0.9. There is a pull request for it [here](https://github.com/NeuralEnsemble/python-neo/pull/817), but it hasn't been merged yet. The 0.9 release should happen within the next six weeks, or you can start using [this branch](https://github.com/apdavison/python-neo/tree/view-group) now.

**Comment by Helveg** [comment]
What a happy coincidence, that generic grouping object sounds like exactly what I was looking for :)
