### ISSUE TITLE
Unconventional installation recommendations in the docs

### ISSUE THREAD

**Issue by Helveg** [NeuralEnsemble/python-neo#861]
The installation docs start out with 

> For Debian/Ubuntu, you can install these using:
> $ apt-get install python-numpy python-pip
> $ pip install quantities
> **You may need to run these as root**. For other operating systems, you can download installers from the links above, or use a scientific Python distribution such as Anaconda.

These are quite unconventional recommendations:
* You're installing python packages using the distro, which installs the package for the system Python installs. It is absolutely not recommended to use these system Pythons (python2.x and python3.x) yourself. Most users (should) have their own setup such as pyenv or virtual envs which these instructions will ignore (iirc).
* The part in bold condones installing Python packages with root; it's probably aimed at the `apt-get install` but can easily be interpreted that if something goes wrong with the `pip install` they should just sudo it. During `pip install` python packages can execute arbitrary code! Doing `sudo pip install` is a huge security risk, you're giving untrusted arbitrary code sudo rights.

May I propose updating this to:

```
python -m ensurepip
pip install --upgrade pip
pip install numpy quantities
```

This uses the pip bootstrapping module `ensurepip`, the recommended way of installing pip, upgrades it and then installs the python dependencies. All taking virtual environments and other shindigs into account.

I'd even leave off the first 2 lines, as most people with python have pip. 

Ideally, make sure that your own python package lists its dependencies in `setup.py` under the `install_requires` kwarg and then a simple `pip install neo` would install Neo and these instructions can be left off entirely.

**Comment by Helveg** [comment]
Later on in the docs:

> Then:
>
> $ unzip neo-0.8.0.zip
> $ cd neo-0.8.0
> $ python setup.py install
> or:
>
> $ python3 setup.py install
> depending on which version of Python you are using.

Python 2 has been given [the boot](https://www.python.org/doc/sunset-python-2/) and these instructions again condone bad practices. If you're going into so much detail for installations the instructions should be pristine and convey the latest standards. Which on Linux means staying away from the system installs and using your own Python 3 install. I'd leave off:

> or:
>
> $ python3 setup.py install
> depending on which version of Python you are using.

**Comment by samuelgarcia** [comment]
Dear Robin,
thank you for this feedback.
We are aware that the documentation is totally prehistoric at some corner.
Instllation is one of theses.
We have plan a total refactoring of the doc quite soon (before v1.0).

If you want to make short PR for this. Feel free we will merge then quickly.
Don't spent to much time in re writting because of the main doc refactoring.
In my mind I would like to use sphinx gallery that generate notebooks based on simple scripts.
