### ISSUE TITLE
Installation docs claim you can't install alpha or beta versions

### ISSUE THREAD

**Issue by Helveg** [NeuralEnsemble/python-neo#862]
> Warning
>
> alpha and beta releases cannot be installed from PyPI.

Sure they can :smiley: ! Just specify the alpha/beta semver:

    pip install neo==0.8.0a5
    pip install neo==0.8.0b0

I see that your project hasn't uploaded any, maybe that's why? https://pypi.org/project/neo/#history

Maybe to avoid making people think PyPI doesn't allow it:

> Note
>
> Our alpha and beta releases are not available on PyPI

**Comment by apdavison** [comment]
Last time I looked into this (more than 5 years ago) it was considered bad practice to upload non-final releases to PyPI, so we don't do so. We rarely make alpha/beta releases, in any case.

I think in this context, the implication "alpha and beta releases (of Neo) cannot be installed from PyPI" is clear enough.
