### ISSUE TITLE
ChannelIndex parent of ImageSequence

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#878]
The current ImageSequence implementation is not listing channel_Index as a parent object or attribute https://github.com/NeuralEnsemble/python-neo/blob/593aff36e05fa3da44a3305073a67731145f7246/neo/core/imagesequence.py#L89
https://github.com/NeuralEnsemble/python-neo/blob/593aff36e05fa3da44a3305073a67731145f7246/neo/core/imagesequence.py#L90
However, indirectly this attribute is generated by inherited BaseSignal methods, e.g. https://github.com/NeuralEnsemble/python-neo/blob/593aff36e05fa3da44a3305073a67731145f7246/neo/core/basesignal.py#L83 leading to the `channel_index` set.
@apdavison Is there a reason for not explicitely listing ChannelIndex as a parent of ImageSequence?

**Comment by apdavison** [comment]
Is it causing problems? Since ChannelIndex will disappear in v0.10.0, does this need to be addressed?

**Comment by JuliaSprenger** [comment]
No, it is just an inconsistency I came across when writing a ChannelIndex & Unit -> View & Group conversion (https://github.com/apdavison/python-neo/pull/3). We could either fix it for this release, but I think it might be coming with a number of follow-up changes required across the project.
