### ISSUE TITLE
Is it possible to process spike2 data online?

### ISSUE THREAD

**Issue by kurobaneHITOMI** [NeuralEnsemble/python-neo#880]
Now we would like to read spike2 data online and test our model. We want to read the data (for example the earliest 1024 points of a channel) into python array directly.  We found that CED has provided a python interface to spike2 filing system, but we still dont konw how to make it happen. Is it possible to use neo library to achieve this?

**Comment by JuliaSprenger** [comment]
Hi @kurobaneHITOMI,
if your question is whether Neo can be used to handle data streams during a recording, then the answer is unfortunately no, as Neo relies on having the complete dataset available.
Does this answer your question? Otherwise please clarify what you are trying to achieve exactly.

**Comment by kurobaneHITOMI** [comment]
I see XD. Thanks for your answer!

**Comment by samuelgarcia** [comment]
@kurobaneHITOMI : for online experiment with python, you should have a look to https://github.com/pyacq/pyacq
doc here https://pyacq.readthedocs.io/en/latest/

CED device is not implemented, but you could add it.

**Comment by kurobaneHITOMI** [comment]
@samuelgarcia thanks for the recommendation!
