### ISSUE TITLE
Improvement of rawio API and lazy object

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#895]
Here a list of rawio API that should enhanced:
  * for sig channel 'id' is now 'int64' but should be 'U' like other object
  * _get_analogsignal_chunk should deal with both global channel indices and local channel_indices
  * if a list (or array) of channel index is given and this list is continuous and ordered like [2,3,4]
    then create the equivalent slice for instance slice(2,5) to avoid copy when memmap
  * deal with array annotation at rawio level
  * create generic lazy object. 
    Actual lazy object than depend on rawio.
    In futur implementation theses lay object would be just a specific case with a sub class.
    This would make possible to implement other lazy objects like:
       * lazy load for nix without the rawio API but with specific lazy object (that link the path into h5)
       * lazy computation `filtered_sig = lazy_passband_filter(lazy_sig, f1=300, f2=5000)`
  * _get_signal_size and _get_signal_t_start based on group_id
  * in signal channels : **group_id** rename to **stream_id** to make it more clear
  * add "local_index" in _signal_channel_dtype
  * rename internally **"unit_channels"** to **"spike_channels"** because Unit object do not exists anymore.

**Comment by PeterNSteinmetz** [comment]
Continuing the discussion here. Is there anything in the new definition of Group in Neo which requires they have the same sampling_rate/length_per_segment/t_start in each segment? I don't see that in the docs at https://neo.readthedocs.io/en/stable/api_reference.html#neo.core.Group . 

Perhaps what is needed here is a new Object, could be a subclass of Group, particularized for this purpose? An AnalogSignalGroup ?

**Comment by samuelgarcia** [comment]
The group_id is only at rawio level (which is an internal API).
This group_id is not for a new object.
The main idea is that AnalogSignal is a **multi channel** object. So a 2D matrix (nsample, nchannel) that have one sampling rate and one t_start.
The group_id at neo.rawio level make an automatic machanism to create diferents multi channel AnalogSignal at layer neo.io (see neo.io.basefromraw module).

i don't known if I am clear.

**Comment by apdavison** [comment]
to clarify a bit further: `group_id` in rawio is not related in any way to the `Group` class. Is that correct @samuelgarcia ?

The `Group` class is a generic way to group any Neo objects except `Block`, with no other constraints about what can be in a` Group`

**Comment by PeterNSteinmetz** [comment]
So maybe it should either be called something else, since group and groupid appear to be related. Or built as a separate class.

**Comment by samuelgarcia** [comment]
Since it is internal to rawio we can call it sig_group_id or sig_group.

**Comment by PeterNSteinmetz** [comment]
So I am now at the point where I need to understand the intended return signature from _get_signal_size and _get_signal_t_start. Particularly when channel_indexes is some arbitrary slice or list of indices. 

In most of the example RawIOs I have seen, the size and t_start is the same for all channels and they return a single number. But this is not really required by the definition of a core Segment. 

In particular, I have a Segment with a number of AnalogSignals, but they don't all have the size and t_start in common. There are sets of AnalogSignal which are different. 

This is an issue in ephyviewer.datasource.AnalogSignalFromNeoRawIOSource.t_start, which simply returns whatever get_signal_t_start returns. 

It seems like when there are multiple channels selected, these should return an np.array of appropriate length with the appropriate value for each channel. And even in the case of a single channel selected, perhaps it should be an np.array of length 1. 

Does that seem correct? What does ephyviewer expect?
