### ISSUE TITLE
nsdfio : remove write capability and and remove ChannelIndex

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#897]
The nsdf file format project seems to be not very active (weakly tested on py3).
It is a hdf5 based format.

The neo.io.NsdfIO:
  * support read and write.
  * support ChannelIndex

I propose to remove the ChannelIndex from this IO.
Only Block>Segment>AnalogSignal would be possible.

I also propose to remove the write_block and write_segment.
My guess is that very few user really need it.
Maintaing write with old format is lot of works when we have chand in API.
We need to do it only for hightly used format .. No ?

@apdavison @JuliaSprenger @mdenker ?

**Comment by apdavison** [comment]
I don't think we should remove write capabilities before discussing this with the authors. I have some contacts with the lab which developed NSDF, so I will contact them to ask what they wish to do.

Since ChannelIndex is only deprecated in 0.9, I think it's ok to include the current implementation in the Neo 0.9 release, then update nsdfio after the release.

**Comment by samuelgarcia** [comment]
For sure we need to discsuss for the nsdf team.
I already started a discussion in there repo here https://github.com/nsdf/nsdf/issues/48
Maintaining read/write is a lot of work when we have API change. We spent many many time on it.
If a neo.io implementation have very few users (and maintainers) it is hard to maintain for always read/write cycle across version.

I think I would prefer that CHannelIndex is out from neo.io in 0.9 for all IOs.
So we won't have to go back this in next release.
nsdfio is more or less tha last one no ?

**Comment by apdavison** [comment]
ok, so how about raising an exception when calling `write_block()`, etc., saying that these methods aren't available in Neo 0.9, and Neo 0.8 should be used if you need to write files with nsdfio.

This will make it easier to update write support later, rather than deleting the code entirely

**Comment by apdavison** [comment]
see fa6b5582
