### ISSUE TITLE
[NeuralynxIO] Tests of keep_original_spike_times failing

### ISSUE THREAD

**Issue by PeterNSteinmetz** [NeuralEnsemble/python-neo#907]
The tests in test_neuralyxio.test_keep_original_spike_times are failing for the test data in Cheetah_v5.5.1 on the .nse files. 

It is not clear to me why these have been hidden previously, though that might have to do with the code which only ran the first two blocks of tests.

**Comment by samuelgarcia** [comment]
Hi Peter.
This test (test_keep_original_spike_times) was originaly done by @JuliaSprenger I think.
I think the idea was to compare the new implementation with an older implemenation.

For new files it do not make sens anymore.
We need to shortent the list for this specific test.

**Comment by JuliaSprenger** [comment]
It's not comparing to an older implementation, but ensures that the flag 'keep_original_spike_times'  yields the identical spike times as present in the data files by comparing to a text file that contains the plain spike times. I would still keep the test as it is not outdated, but we should rather investigate the reason why the test is failing.
Surprisingly in #905 it is not failing any more and I don't think @PeterNSteinmetz removed the troublesome files from the list of tested files. So maybe there's another fix already?

**Comment by PeterNSteinmetz** [comment]
I noticed that also in #905 and don’t understand exactly why it doesn’t fail.

For current work I have simply added an ignoretest. But this will need to be addressed.

**Comment by samuelgarcia** [comment]
oups sorry for bad info so.
