### ISSUE TITLE
RawIO improvements of annotations

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#910]
From #896 @samuelgarcia  (https://github.com/NeuralEnsemble/python-neo/pull/896/files#r530612518)

> rawio have a bad choice about annotation for AnalogSignal because it is done only at channel level (which is good for array_annotation) I need to add another dict for this. And also I want to make more explicit channel_indexes.
They are now global indexes and I would to introduce local (to stream) indexes in the APi to make dev more simple.

**Comment by samuelgarcia** [comment]
This strongly link to #895
