### ISSUE TITLE
`DataObject.rescale` creates unidirectional uplinks

### ISSUE THREAD

**Issue by Kleinjohann** [NeuralEnsemble/python-neo#939]
The segment uplink of the copied object is explicitly copied here:
https://github.com/NeuralEnsemble/python-neo/blob/da0565508dbc8b0722cb27ffe1efc33ecba58549/neo/core/dataobject.py#L286

I encountered this when running the in-place deletion of `elephant.spike_train_synchrony.Synchrotool` (in the current master branch of elephant but not yet in any release version). It relies on links being bidirectional, here's a minimal example:

```
import neo
import numpy as np
import quantities as pq
from elephant.spike_train_synchrony import Synchrotool

segment = neo.Segment(name='Original Segment')
st = neo.SpikeTrain(times=np.arange(5)*pq.s, t_stop=5*pq.s)
segment.spiketrains.append(st)
segment.create_relationship()
print(st.segment.name)

st2 = st.rescale(pq.ms)
print(st2.segment.name)

sync_obj = Synchrotool([st2], spread=2, sampling_rate=1*pq.Hz)
sync_obj.delete_synchrofacts(threshold=2, in_place=True)
```

This returns
```
Original Segment
Original Segment
```

and then raises
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-00d08a1f3453> in <module>
      1 sync_obj = Synchrotool([st2], spread=2, sampling_rate=1*pq.Hz)
----> 2 sync_obj.delete_synchrofacts(threshold=2, in_place=True)

~/src/elephant/elephant/spike_train_synchrony.py in delete_synchrofacts(self, threshold, in_place, mode)
    349 
    350                 # replace link to spiketrain in segment
--> 351                 new_index = self._get_spiketrain_index(
    352                     segment.spiketrains, st)
    353                 segment.spiketrains[new_index] = new_st

~/src/elephant/elephant/spike_train_synchrony.py in _get_spiketrain_index(self, spiketrain_list, spiketrain)
    402             if item is spiketrain:
    403                 return index
--> 404         raise ValueError("Spiketrain is not found in the list")

ValueError: Spiketrain is not found in the list
```

since `st2` is not in `segment.spiketrains` even though it has an uplink `st2.segment = segment`.

I will account for this in elephant for now and only warn the user in such a case where the structure contains a unidirectional link. However, copying the uplink is not the behaviour I would expect personally, so I wanted to put this out here and ask what the reasoning behind it is. Sorry if this has already been discussed, I couldn't find anything matching issues.

**Comment by samuelgarcia** [comment]
Hi Alexander.
I agree I would remove the `obj.segment = self.segment` in rescale.
