### ISSUE TITLE
Tried to open and 'old' (2015) .smr file and got Unicode Error

### ISSUE THREAD

**Issue by eduardacenteno** [NeuralEnsemble/python-neo#948]
When I tried to read / work with an old .smr file (from 2015), I got this error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 23: ordinal not in range(128)
This was related to the line 519 of spike2rawio.py. 

I was able to solve it by changing the labels = labels.astype('U') to labels = labels.astype('S')

**Comment by samuelgarcia** [comment]
Hi Edourda.
I think this is already fix.

Could you update your neo package ?
`pip install --upgrade neo`

and if it still failling get neo from source with:
`pip uninstall neo`
`pip install https://github.com/NeuralEnsemble/python-neo/archive/master.zip`

and if this is still failing contact me by mail with file.

**Comment by JuliaSprenger** [comment]
@eduardacenteno Did @samuelgarcia suggestions fix the issue? Tell us if you need more detailed instructions for the update.

**Comment by eduardacenteno** [comment]
Hey @JuliaSprenger @samuelgarcia ! Only today I had the time to check this again, sorry for the delay. I installed neo directly from github/setup.py but the issue persists. Now moving to line 566 (still the same code, though): labels = labels.astype('U')
I can send an example file if you'd like, but basically changing it to 'S' solves the issue.
![image](https://user-images.githubusercontent.com/47068116/112007857-4d306480-8b25-11eb-955a-0807f892ff2a.png)

**Comment by eduardacenteno** [comment]
Hey @JuliaSprenger @samuelgarcia ! Only today I had the time to check this again, sorry for the delay. I installed neo directly from github/setup.py but the issue persists. Now moving to line 566 (still the same code, though): labels = labels.astype('U')
I can send an example file if you'd like, but basically changing it to 'S' solves the issue.

**Comment by JuliaSprenger** [comment]
Status update: I reveived a test file and @samuelgarcia is having a look into this.

**Comment by samuelgarcia** [comment]
close by #982
