### ISSUE TITLE
Add support for multiple NcsSections - Neuralynx

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeuralEnsemble/python-neo#959]
Hi there,

I'm working on converting a directory of 64 `.ncs` files through spikeextractors, but it errors out at these lines of the `rawio` code: [https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio/neuralynxrawio.py#L535-L537](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio/neuralynxrawio.py#L535-L537)

Would it be possible to extend support to use neo for this? I'm also happy to help if you can guide me through the way neo operates (first time looking this deep into the neo ecosystem).

**Comment by samuelgarcia** [comment]
Hi Cody,
The format have many internal variant and sometimes there are some bugs.
@PeterNSteinmetz is more expert than me for this format maybe you could coordinate.
He is also make a PR than could solve your issue (I don't known): 
https://github.com/NeuralEnsemble/python-neo/pull/957

If you have a small file that cause the bug that could be public it would be perfect for testing.

**Comment by CodyCBakerPhD** [comment]
It looks like that PR might provide a roundabout fix if we can just loop through the files individually - the data I'm working on may not be open access but I'll see if I can find or make something else that can break it similarly.

**Comment by PeterNSteinmetz** [comment]
I believe that error in spikeextractors is arising because the current NeuralynxRawIO does not create proper groupings for the files.

**Comment by CodyCBakerPhD** [comment]
TBH I've found in my own work on the Neuroscope format that `filename` operability is almost always safer than imposing some internal structure by `dirname`.

In that regard, [PR #957](https://github.com/NeuralEnsemble/python-neo/pull/957) does therefore provide a safer workaround for my use case, and in general is a perfectly simple solution when using these IO's through `spikeextractors`, since we can just form a new `RecordingExtractor` via the `MultiChannelRecordingExtractor` class.
