### ISSUE TITLE
AssertionError: Signal do not have the same sampling rate

### ISSUE THREAD

**Issue by SAJinani** [NeuralEnsemble/python-neo#966]
I want to read analog signals in a plx file with different sample rates (31250 KHz and 1250 KHz). However I'm getting this error : **AssertionError: Signal do not have the same sampling rate**
Is there a way to fix this or just to read analog signals of one sampling frequency only out of these two?

**Comment by samuelgarcia** [comment]
At the moment, the reader handle only case were signal have the same sampling rate for plexon.
Maybe I could add an option to selec which channel we want to load. So you could one channel at once.

If the file is small could you send me ?

**Comment by SAJinani** [comment]
The plx file that I'm trying to read right now is about 6GB. I tried reading it by commenting line 177 of File "/opt/anaconda3/envs/NEO2/lib/python3.9/site-packages/neo/rawio/plexonrawio.py". 
It reads only a part of high sampling freq channel. Is there a way that I can read only the high sampling freq channel and the whole length of that signal only?
In my case; I just want Analogsignal with 31250Hz sampling rate here. Is it possible?
![image](https://user-images.githubusercontent.com/81603408/112979057-15797c00-9126-11eb-9033-feb02d9a3e9e.png)

**Comment by samuelgarcia** [comment]
I have started a fix here : https://github.com/NeuralEnsemble/python-neo/pull/967

**Comment by samuelgarcia** [comment]
Closed by #967
