### ISSUE TITLE
many warnings in our test

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#979]
When I set tests on github actions saw many warnings.
We should fix then before any problems occurs.

**Comment by samuelgarcia** [comment]
See this https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

We have several choice to replace np.int:
  1. int
  2. np.int_
  3. np.int32 or np.int64 depending the context and wanted precision.

Choice 1. et 2. don't change the behavior : the precission depend on the platform.

I would prefer choice 3. and fix the precision in the code for reader (IO implementation)
In many situtaion np.int64 is  needed and it is better to explicit.

In our test I will left np.int_ and np.float_ depending the context.

@apdavison @JuliaSprenger @mdenker ?

**Comment by JuliaSprenger** [comment]
Hi @samuelgarcia.
Thanks for looking into the warning, the output is indeed very verbose currently.
Regarding your preferred choice option 3, we should be careful not not use np.int64 in places where it unnecessarily drastically increases memory usage. So a reader specific choice is also the best option in my mind.

Regarding options 1 and 2: Why would you go for the more verbose option of `np.int_` in the tests if `int` would do the same job? In terms of readability `int` should be better, no?

**Comment by samuelgarcia** [comment]
Hi Julia,
I propose you have a look to the PR and make comments case by case because it depends.
you will see #991

**Comment by samuelgarcia** [comment]
close by #991 and #1010
