### ISSUE TITLE
How to obtain header information for a particular channel_index in a stream

### ISSUE THREAD

**Issue by PeterNSteinmetz** [NeuralEnsemble/python-neo#983]
@samuelgarcia So using the new BaseRawIO interface with streams containing analog signals and those signals being indexed by a channel_index relative to a stream, how are we supposed to obtain the corresponding elements of the header['signal_channels'] array? 

I was looking for a way to do this using the BaseRawIO API and it is not obvious. I need to do this to make the ephyviewer.datasource.neosource.AnalogSignalFromNeoRawIOSource work, particularly its get_gains and get_offsets methods. 

It seems frankly like a more general problem that may require a translation method from (stream_id, channel_index) to header offsets (similar to the old meaning of channel_index in BaseRawIO).

**Comment by samuelgarcia** [comment]
Hi Peter,
for ephyviewer have a look to the already started PR here https://github.com/NeuralEnsemble/ephyviewer/pull/151

Given a stream_id, to obtain corresponding header['signal_channels'] I use boolean mask like this 
```python
mask = header['signal_channels']['sgtream_id'] == stream_id
channel_in_stream = header['signal_channels'][mask]
```

**Comment by PeterNSteinmetz** [comment]
Hi Samuel, just created https://github.com/NeuralEnsemble/ephyviewer/pull/152 showing a slightly different approach. 

And why not go to Neo 1.0 rather than 0.10 ? I always find that ugly and frankly this has been in use enough that 1.0 does not seem inappropriate.

**Comment by samuelgarcia** [comment]
The plan was to make neo 1.0 two years ago.
But we are too slow.

We have a long list before this 1.0 grail:
  * merge AnalogSignal and irregularlySampleSignal
  * make a SpikeTrainList (or similar name)
  * rework the lazy object
  * implementation IOs from spikeextractors
  * totally rewrite the documentation with sphinx gallery
  * improve integration with NWB and NIX
  * clean very old code
  * simplify test suite

We are so lazy that it could take one or two years more.

**Comment by PeterNSteinmetz** [comment]
I know if is just a matter of style with the numbering, but it does seem like Neo has been at a basic functional level for some time, which to me is a 1.0.

But then there is the Linux style of numbering...
